{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.119.986.0 (23.07)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Calls\",\"Cases\",\"Case Metrics\",\"Agent Product Assignment\",\"Departments\",\"Employee\",\"Employee Site\",\"PrimaryProduct\",\"PrimaryProductGroup\",\"Products\",\"Regions\",\"Category Code Description\",\"Complaint Type Description\",\"Customer Contacts\",\"IBase\",\"Knowledge Article\",\"Materials\",\"Minutes to Close Bucket\",\"MLC\",\"Priority Description\",\"Status Description\",\"Actual VQ\",\"DNIS\",\"Handle Type\",\"Interaction Type\",\"Requested VQ\",\"Resource Role\",\"Required Skill\",\"Resource Type\",\"Result Reason\",\"Technical Result\",\"Queue\",\"KPI Calls\",\"KPI Cases\",\"KPI Calls Dynamic Measures Cnt\",\"KPI Calls Dynamic Legend\",\"KPI Calls Dynamic Measures %\",\"KPI Cases Dynamic Measures Cnt\",\"KPI Cases Dynamic Legend\",\"KPI Cases Dynamic Measures %\",\"KPI Community Cases Dynamic Measures %\",\"KPI Community Cases Dynamic Measures Cnt\",\"KPI Time to Assign in Hours Dynamic Measures Cnt\",\"KPI Agent Metics by Day\",\"KPI AMBD Dynamic Legent\",\"KPI AMBD Dynamic Measures Cnt\",\"Labels\",\"Slicers\",\"CallsProduct\",\"CasesProduct\",\"RV_mms_canonical_bdx_customer_master\",\"CallsCustomer\",\"CasesCustomer\",\"Customers\",\"RV_canonical_calendar\",\"CallsEmployee\",\"CasesEmployee\",\"ModelStartDate\",\"Today\",\"DateList\",\"StartDate\",\"Transaction Dates\",\"AgentProductMapping\",\"Calls Abandoned\",\"Agent Metrics By Day\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "CallsProduct",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Calls,",
          "    #\"Choose columns\" = Table.SelectColumns(Source,{\"Product Category\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Choose columns\",{{\"Product Category\", \"ProductCategory\"}}),",
          "    #\"Grouped rows\" = Table.Group(#\"Renamed Columns\", {\"ProductCategory\"}, {{\"Count\", each Table.RowCount(_), Int64.Type}}),",
          "    #\"Removed columns\" = Table.RemoveColumns(#\"Grouped rows\", {\"Count\"}),",
          "    #\"Renamed columns\" = Table.RenameColumns(#\"Removed columns\", {{\"ProductCategory\", \"Products\"}})",
          "in",
          "    #\"Renamed columns\""
        ],
        "kind": "m",
        "lineageTag": "ff5316d5-87e8-44a5-93e8-934c3a27901c",
        "queryGroup": "Staging"
      },
      {
        "name": "CasesProduct",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Cases,",
          "    #\"Choose columns\" = Table.SelectColumns(Source,{\"Product Sub Category\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Choose columns\",{{\"Product Sub Category\", \"Products\"}}),",
          "    #\"Grouped rows\" = Table.Group(#\"Renamed Columns\", {\"Products\"}, {{\"Count\", each Table.RowCount(_), Int64.Type}}),",
          "    #\"Removed columns\" = Table.RemoveColumns(#\"Grouped rows\", {\"Count\"})",
          "in",
          "    #\"Removed columns\""
        ],
        "kind": "m",
        "lineageTag": "972b5a4d-79c8-4f92-9a3e-0629637f4c3e",
        "queryGroup": "Staging"
      },
      {
        "name": "RV_mms_canonical_bdx_customer_master",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "  Source = PowerPlatform.Dataflows(null),",
          "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
          "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
          "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
          "    [Data],",
          "  #\"8bc11fbb-87d0-490d-ac7e-533062a85e3f\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
          "    {[dataflowId = \"8bc11fbb-87d0-490d-ac7e-533062a85e3f\"]}",
          "    [Data],",
          "  RV_mms_canonical_bdx_customer_master_ = #\"8bc11fbb-87d0-490d-ac7e-533062a85e3f\"",
          "    {[entity = \"RV_mms_canonical_bdx_customer_master\", version = \"\"]}",
          "    [Data]",
          "in",
          "  RV_mms_canonical_bdx_customer_master_"
        ],
        "kind": "m",
        "lineageTag": "f37ac36a-c855-4a12-969c-b94e9ad36600",
        "queryGroup": "Staging"
      },
      {
        "name": "CallsCustomer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Calls,",
          "    #\"Choose columns\" = Table.SelectColumns(Source,{\"Customer ID\"}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Choose columns\"),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Duplicates\",{{\"Customer ID\", \"CustomerID\"}})",
          "in",
          "    #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "826409ed-4240-4dd8-a68e-e59f230069b0",
        "queryGroup": "Staging"
      },
      {
        "name": "CasesCustomer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "  Source = Cases, ",
          "  #\"Choose columns\" = Table.SelectColumns(Source,{\"Ship to Customer\"}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Choose columns\"),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Duplicates\",{{\"Ship to Customer\", \"CustomerID\"}})",
          "in",
          "    #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "e8e68a24-b4dd-4bd0-846a-159236ee0a6d",
        "queryGroup": "Staging"
      },
      {
        "name": "CallsEmployee",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Calls,",
          "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Employee ID\"})",
          "in",
          "    #\"Removed Other Columns\""
        ],
        "kind": "m",
        "lineageTag": "8518fcb7-6b83-4902-9cc3-55207c97a85a",
        "queryGroup": "Staging"
      },
      {
        "name": "CasesEmployee",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "  Source = Cases,",
          "  #\"Choose columns\" = Table.SelectColumns(",
          "    Source,",
          "    {\"Opened by Employee ID\", \"Closed by Employee ID\"}",
          "  ),",
          "  #\"Unpivoted Columns\" = Table.UnpivotOtherColumns(#\"Choose columns\", {}, \"Attribute\", \"Value\"),",
          "  #\"Filtered Rows\" = Table.SelectRows(",
          "    #\"Unpivoted Columns\",",
          "    each ([Attribute] = \"Closed by Employee ID\")",
          "  ),",
          "  #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows\", {\"Value\"}),",
          "  #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Other Columns\", {{\"Value\", \"Employee ID\"}})",
          "in",
          "  #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "8517ba49-0847-44b2-a2be-d77df7c93765",
        "queryGroup": "Staging"
      },
      {
        "name": "DateList",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = List.Dates",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "cdfdbbd2-3652-40de-9715-eb53b0090e69",
        "queryGroup": "Staging\\DateRange"
      },
      {
        "name": "StartDate",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": "#date(2011, 1, 31) meta [IsParameterQuery=true, Type=\"Date\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "3122e94b-7a04-46c7-bc48-aa3794789f70",
        "queryGroup": "Staging\\DateRange"
      },
      {
        "name": "ModelStartDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMjDUNzbUNzIwNFSKjQUA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Date = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Date\", type date}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "0d23df30-315e-4619-a629-1bed1a383b60",
        "queryGroup": "Staging\\DateRange"
      },
      {
        "name": "Today",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": [
          "let",
          "    Source = DateTime.LocalNow(),",
          "    #\"Extracted Date\" = Date.From(Source)",
          "in",
          "    #\"Extracted Date\""
        ],
        "kind": "m",
        "lineageTag": "5ab19c04-7994-4084-ae52-eaabd0c6990f",
        "queryGroup": "Staging\\DateRange"
      },
      {
        "name": "RV_canonical_calendar",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "  Source = PowerPlatform.Dataflows(),",
          "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
          "  #\"8002b6b6-3a67-4bb0-82f9-e38851e04e8f\" = Workspaces",
          "    {[workspaceId = \"8002b6b6-3a67-4bb0-82f9-e38851e04e8f\"]}",
          "    [Data],",
          "  #\"26ec83ee-cd97-49d6-8186-553e7629d769\" = #\"8002b6b6-3a67-4bb0-82f9-e38851e04e8f\"",
          "    {[dataflowId = \"26ec83ee-cd97-49d6-8186-553e7629d769\"]}",
          "    [Data],",
          "  RV_canonical_calendar_ = #\"26ec83ee-cd97-49d6-8186-553e7629d769\"",
          "    {[entity = \"RV_canonical_calendar\", version = \"\"]}",
          "    [Data]",
          "in",
          "  RV_canonical_calendar_"
        ],
        "kind": "m",
        "lineageTag": "2d5dcacb-f6a4-4af1-be2c-eed66aff9f86",
        "queryGroup": "Staging"
      },
      {
        "name": "Calls Abandoned",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "  Source = Table.FromRows(",
          "    Json.Document(",
          "      Binary.Decompress(",
          "        Binary.FromText(\"i45Wck7MySlWcExKzEvJz0tNUdJRMlaKjQUA\", BinaryEncoding.Base64),",
          "        Compression.Deflate",
          "      )",
          "    ),",
          "    let",
          "      _t = ((type nullable text) meta [Serialized.Text = true])",
          "    in",
          "      type table [#\"DM Cnt Selections Calls\" = _t, Sort = _t]",
          "  ),",
          "  #\"Changed Type\" = Table.TransformColumnTypes(",
          "    Source,",
          "    {{\"DM Cnt Selections Calls\", type text}, {\"Sort\", Int64.Type}}",
          "  ),",
          "  #\"Renamed Columns\" = Table.RenameColumns(",
          "    #\"Changed Type\",",
          "    {{\"DM Cnt Selections Calls\", \"DM Cnt Selection Calls\"}}",
          "  ),",
          "  #\"Replaced Value\" = Table.ReplaceValue(",
          "    #\"Renamed Columns\",",
          "    \"Abandoned\",",
          "    \"Handled\",",
          "    Replacer.ReplaceText,",
          "    {\"DM Cnt Selection Calls\"}",
          "  )",
          "in",
          "  #\"Replaced Value\""
        ],
        "kind": "m",
        "lineageTag": "0a6249ea-332c-44c3-929a-de73fd3b9d66"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Fact"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Dim"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Dim\\Calls"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Dim\\Cases"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Dim\\Common"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Staging"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Staging\\DateRange"
      }
    ],
    "relationships": [
      {
        "name": "80a45f5f-4112-4879-9475-5e7384fddc01",
        "fromColumn": "IObject ID No Leading Zeros",
        "fromTable": "Cases",
        "toColumn": "IObject ID No Leading Zeros",
        "toTable": "IBase"
      },
      {
        "name": "2a0d7a5e-93d1-49d6-bdc1-2163086c85ba",
        "fromColumn": "Reference Product No Leading Zero",
        "fromTable": "IBase",
        "toColumn": "Reference Product No Leading Zero",
        "toTable": "Materials"
      },
      {
        "name": "5b8d158f-4368-495f-989e-27c5e14ffc3f",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Service Request ID",
        "fromTable": "Cases",
        "toColumn": "Service Request ID",
        "toTable": "MLC"
      },
      {
        "name": "f635f4b2-6841-448b-8129-a4be24f24659",
        "fromColumn": "Knowledge Article ID",
        "fromTable": "Cases",
        "toColumn": "KnowledgeArticleId",
        "toTable": "Knowledge Article"
      },
      {
        "name": "5da450cb-6bed-4e0c-a07e-a870213aa64a",
        "fromColumn": "CategoryCodeDescription",
        "fromTable": "Cases",
        "toColumn": "Index",
        "toTable": "Category Code Description"
      },
      {
        "name": "628c8bad-e1a2-471f-8db3-c1ec85d40f6d",
        "fromColumn": "ComplaintTypeDescription",
        "fromTable": "Cases",
        "toColumn": "Index",
        "toTable": "Complaint Type Description"
      },
      {
        "name": "d5f56248-cd17-4a99-94c4-eca912fa6191",
        "fromColumn": "Minutes to Close Bucket",
        "fromTable": "Cases",
        "toColumn": "Index",
        "toTable": "Minutes to Close Bucket"
      },
      {
        "name": "cfcbd123-606b-48ef-9556-d40ea80141c9",
        "fromColumn": "PriorityDescription",
        "fromTable": "Cases",
        "toColumn": "Index",
        "toTable": "Priority Description"
      },
      {
        "name": "05217bbb-46d0-4ade-8d0e-39d87b68374c",
        "fromColumn": "StatusDescription",
        "fromTable": "Cases",
        "toColumn": "Index",
        "toTable": "Status Description"
      },
      {
        "name": "bac84ffa-898b-4505-adb5-1089d3a40b83",
        "fromColumn": "ActualVQ",
        "fromTable": "Calls",
        "toColumn": "Index",
        "toTable": "Actual VQ"
      },
      {
        "name": "0fee944f-d0f3-41a7-b106-59cbb652e87a",
        "fromColumn": "DNIS",
        "fromTable": "Calls",
        "toColumn": "Index",
        "toTable": "DNIS"
      },
      {
        "name": "8151cfc1-d4c0-451d-bf13-e9de76867073",
        "fromColumn": "Handle Type",
        "fromTable": "Calls",
        "toColumn": "Index",
        "toTable": "Handle Type"
      },
      {
        "name": "25869e3f-6ab2-489e-9e02-ad58d1ecdf4c",
        "fromColumn": "InteractionType",
        "fromTable": "Calls",
        "toColumn": "Index",
        "toTable": "Interaction Type"
      },
      {
        "name": "fd871776-84ec-4192-9370-818a6fccf875",
        "fromColumn": "RequestedVQ",
        "fromTable": "Calls",
        "toColumn": "Index",
        "toTable": "Requested VQ"
      },
      {
        "name": "76a57be1-80bb-4d2c-844d-4de0df35983e",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "RequiredSkill",
        "fromTable": "Calls",
        "toColumn": "Index",
        "toTable": "Required Skill"
      },
      {
        "name": "dd9da3f8-093b-4119-a59f-b1c0aa52106d",
        "fromColumn": "ResourceRole",
        "fromTable": "Calls",
        "toColumn": "Index",
        "toTable": "Resource Role"
      },
      {
        "name": "6fd333f7-aa21-4ddf-8276-01a46d3ce287",
        "fromColumn": "ResourceType",
        "fromTable": "Calls",
        "toColumn": "Index",
        "toTable": "Resource Type"
      },
      {
        "name": "d39389c8-f6c5-4f58-b1dc-46e563f707a1",
        "fromColumn": "ResultReason",
        "fromTable": "Calls",
        "toColumn": "Index",
        "toTable": "Result Reason"
      },
      {
        "name": "e68f706f-b9ac-4458-92a1-e29919c12b27",
        "fromColumn": "TechnicalResult",
        "fromTable": "Calls",
        "toColumn": "Index",
        "toTable": "Technical Result"
      },
      {
        "name": "233fe406-ff59-4132-8b5b-85d55b4dbe38",
        "fromColumn": "Service Request ID",
        "fromTable": "Case Metrics",
        "toColumn": "Service Request ID",
        "toTable": "Cases"
      },
      {
        "name": "aa61f8d7-e15f-4724-8433-6c69570eddb7",
        "fromColumn": "Employee ID",
        "fromTable": "Calls",
        "toColumn": "Employee ID",
        "toTable": "Employee"
      },
      {
        "name": "b5d68337-97f9-4cbc-abe7-17a6613595b4",
        "fromColumn": "Employee ID",
        "fromTable": "Case Metrics",
        "toColumn": "Employee ID",
        "toTable": "Employee"
      },
      {
        "name": "c8f8a85e-5dfd-43aa-a0df-be3a7a9fe13a",
        "fromColumn": "Business Site Name",
        "fromTable": "Employee",
        "toColumn": "BusinessSiteName",
        "toTable": "Employee Site"
      },
      {
        "name": "0632cd65-ee37-4a72-bf8e-3a2672138366",
        "fromColumn": "Primary Product Group",
        "fromTable": "Calls",
        "toColumn": "PrimaryProductGroup",
        "toTable": "PrimaryProductGroup"
      },
      {
        "name": "5c1c2bed-32c0-4557-a948-69ab05fe558b",
        "fromColumn": "Primary Product Group",
        "fromTable": "Case Metrics",
        "toColumn": "PrimaryProductGroup",
        "toTable": "PrimaryProductGroup"
      },
      {
        "name": "1f07caf7-889f-4ae0-865c-70e5eec32b59",
        "fromColumn": "Primary Product",
        "fromTable": "Calls",
        "toColumn": "PrimaryProduct",
        "toTable": "PrimaryProduct"
      },
      {
        "name": "21f8d33c-f70f-40d3-b02e-278c0d83533d",
        "fromColumn": "Primary Product",
        "fromTable": "Case Metrics",
        "toColumn": "PrimaryProduct",
        "toTable": "PrimaryProduct"
      },
      {
        "name": "250c8ea8-46a2-4aaa-8bdf-4b3d5103d4be",
        "fromColumn": "Customer ID",
        "fromTable": "Calls",
        "toColumn": "Customer ID",
        "toTable": "Customers"
      },
      {
        "name": "d748f29d-dd9c-40a2-8877-56eb40ef6370",
        "fromColumn": "Customer ID",
        "fromTable": "Case Metrics",
        "toColumn": "Customer ID",
        "toTable": "Customers"
      },
      {
        "name": "5245411e-0c44-4095-81ee-9a24a4e8bd03",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "State",
        "fromTable": "Customers",
        "toColumn": "State",
        "toTable": "Regions"
      },
      {
        "name": "480e3e39-d5ff-4f21-8ed2-09a35ad90d96",
        "fromColumn": "Product Sub Category",
        "fromTable": "Cases",
        "toColumn": "Products",
        "toTable": "Products"
      },
      {
        "name": "7f3d29a8-4804-4c27-8b7a-19620a73dc71",
        "fromColumn": "Department ID",
        "fromTable": "Case Metrics",
        "toColumn": "DepartmentID",
        "toTable": "Departments"
      },
      {
        "name": "1e2af911-4ddb-40a0-bfd9-1aece7d4247c",
        "fromColumn": "Employee Department",
        "fromTable": "Calls",
        "toColumn": "DepartmentID",
        "toTable": "Departments"
      },
      {
        "name": "2db8ac87-92ff-461a-97cc-ec2dd8b683f0",
        "fromColumn": "Call Date",
        "fromTable": "Calls",
        "toColumn": "Date",
        "toTable": "Transaction Dates"
      },
      {
        "name": "423c3419-4bdd-46dc-b183-c13214a0d595",
        "fromColumn": "Transaction Date",
        "fromTable": "Case Metrics",
        "toColumn": "Date",
        "toTable": "Transaction Dates"
      },
      {
        "name": "7fbedb63-d630-4c54-9d88-7228a4769676",
        "fromColumn": "Product Category",
        "fromTable": "Calls",
        "toColumn": "Products",
        "toTable": "Products"
      },
      {
        "name": "e38e67db-63c3-403b-be4a-3bb4fa2eb648",
        "fromColumn": "QueueNameIndex",
        "fromTable": "Calls",
        "toColumn": "Queue Name Index",
        "toTable": "Queue"
      },
      {
        "name": "d1f412fe-69fb-4735-bc65-fda7cd64d453",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Service Request ID",
        "fromTable": "Cases",
        "toColumn": "Service Request ID",
        "toTable": "Cases Closed"
      },
      {
        "name": "12a4c9bb-f3fc-44f5-b281-b413f93a5ba3",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Service Request ID",
        "fromTable": "Cases",
        "toColumn": "Service Request ID",
        "toTable": "Cases Open"
      },
      {
        "name": "8fed12f4-bcf9-4f85-9fd8-090e50796526",
        "fromColumn": "Product Category",
        "fromTable": "Calls",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendCalls"
      },
      {
        "name": "3beed6fd-903e-4f08-8dde-19e0719fa022",
        "fromColumn": "Skills",
        "fromTable": "Calls",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendCalls"
      },
      {
        "name": "6ce585f9-13cd-48c9-afab-1ba589fa2b6d",
        "fromColumn": "Mgr1",
        "fromTable": "Calls",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendCalls"
      },
      {
        "name": "64592b33-db86-487d-ab4a-8b24252b706e",
        "fromColumn": "Agent",
        "fromTable": "Calls",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendCalls"
      },
      {
        "name": "3233433b-2a57-429e-b487-d1dd74c2abad",
        "fromColumn": "QueueNameIndex",
        "fromTable": "Calls",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendCalls"
      },
      {
        "name": "48f1d1b8-7127-40e1-9b42-b8dc3692e645",
        "fromColumn": "Product",
        "fromTable": "Case Metrics",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendCases"
      },
      {
        "name": "3071763a-77dd-409c-bb12-81aa2860e09d",
        "fromColumn": "Category Code Description",
        "fromTable": "Case Metrics",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendCases"
      },
      {
        "name": "a75070bc-36ac-4fd9-a528-bb19ad615bfe",
        "fromColumn": "Priority Description",
        "fromTable": "Case Metrics",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendCases"
      },
      {
        "name": "8b94fd7c-9b6e-4921-b33c-7439e6565556",
        "fromColumn": "Community Case Flag",
        "fromTable": "Case Metrics",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendCases"
      },
      {
        "name": "65bcbcce-8bb2-48b0-8027-f6fa2d385534",
        "fromColumn": "PHL4",
        "fromTable": "Case Metrics",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendCases"
      },
      {
        "name": "29bff6b9-5392-4de2-a06d-c8216f57645c",
        "fromColumn": "PHL5",
        "fromTable": "Case Metrics",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendCases"
      },
      {
        "name": "7a4e7a92-6080-4424-bcd3-7195b9131d71",
        "fromColumn": "Mngr Level 1",
        "fromTable": "Case Metrics",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendCases"
      },
      {
        "name": "7d2b0a8c-685c-4912-beef-a7b9658ee7c7",
        "fromColumn": "Agent",
        "fromTable": "Case Metrics",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendCases"
      },
      {
        "name": "6e932e8c-6881-4256-ac8c-a234b0d3b2e7",
        "fromColumn": "Priority Description",
        "fromTable": "Case Metrics",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendCommunityCases"
      },
      {
        "name": "9fe38a76-c597-4d28-b4a4-fd1f26e40487",
        "fromColumn": "Product",
        "fromTable": "Case Metrics",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendCommunityCases"
      },
      {
        "name": "8e336a8e-9bd7-4bf5-a1fc-913dc98f5a8b",
        "fromColumn": "Call Date",
        "fromTable": "WaitDurations for ASA Calculations",
        "toColumn": "Date",
        "toTable": "Transaction Dates"
      },
      {
        "name": "5163d244-e564-421a-a98b-1e505fe1b2d5",
        "fromColumn": "ContactCustomerBPartner",
        "fromTable": "Cases",
        "toColumn": "ContactBPartner",
        "toTable": "Customer Contacts"
      },
      {
        "name": "0b34f84c-45b2-4eb5-b651-101774b0fa86",
        "fromColumn": "Date",
        "fromTable": "Agent Metrics By Day",
        "toColumn": "Date",
        "toTable": "Transaction Dates"
      },
      {
        "name": "8a2de5ed-1fbe-432c-8c05-409552fbbb14",
        "fromColumn": "PrimaryProduct",
        "fromTable": "Agent Metrics By Day",
        "toColumn": "PrimaryProduct",
        "toTable": "PrimaryProduct"
      },
      {
        "name": "745c7737-a2dd-4893-b607-e41762017f0f",
        "fromColumn": "PrimaryProductGroup",
        "fromTable": "Agent Metrics By Day",
        "toColumn": "PrimaryProductGroup",
        "toTable": "PrimaryProductGroup"
      },
      {
        "name": "35c6d1c8-f7fd-41ef-85cd-dbd0e13cf5d5",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "EmployeeID|ExtractDate",
        "fromTable": "AgentProductMapping",
        "toColumn": "EmployeeID|Date",
        "toTable": "Agent Metrics By Day"
      },
      {
        "name": "dedb98ae-edb0-4735-8b0e-633e4bb4da8a",
        "fromColumn": "Employee ID",
        "fromTable": "Agent Metrics By Day",
        "toColumn": "Employee ID",
        "toTable": "Employee"
      },
      {
        "name": "ccd425c5-7ac3-4d7b-abf5-0f99db2310b8",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "EmployeeID|ExtractDate",
        "fromTable": "Agent Product Assignment",
        "toColumn": "EmployeeID|Date",
        "toTable": "Agent Metrics By Day"
      },
      {
        "name": "fa168526-e820-44e4-952f-c99163134f15",
        "fromColumn": "PP",
        "fromTable": "Agent Metrics By Day",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendAgentMetricsbyDay"
      },
      {
        "name": "4b265002-cad2-46aa-87dd-8d93747e53ee",
        "fromColumn": "PPG",
        "fromTable": "Agent Metrics By Day",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendAgentMetricsbyDay"
      },
      {
        "name": "89094e81-5869-478f-9183-6b390e6b9704",
        "fromColumn": "Agent",
        "fromTable": "Agent Metrics By Day",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendAgentMetricsbyDay"
      },
      {
        "name": "f85727e8-8aec-4727-9524-d4c93c1f7ba1",
        "fromColumn": "Mngr Level 1",
        "fromTable": "Agent Metrics By Day",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendAgentMetricsbyDay"
      },
      {
        "name": "f6692782-68df-4981-a2ef-1fcdef53f7e8",
        "fromColumn": "Mngr Level 1",
        "fromTable": "Agent Metrics By Day",
        "isActive": false,
        "toColumn": "CategoryValueIndex",
        "toTable": "DynamicLegendCommunityCases"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Actual VQ",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Actual VQ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03616654-cea3-435b-a97b-2b8df21da987",
            "sourceColumn": "Actual VQ",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5b7b203f-d430-453e-9477-763a279b8d96",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "50b99260-09a1-4878-8607-a880a359f7a9",
        "partitions": [
          {
            "name": "Actual VQ-5f45b6b4-a939-4145-80ee-7beeefdcddeb",
            "mode": "import",
            "queryGroup": "Dim\\Calls",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null), ",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data], ",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data], ",
                "  #\"7bc93924-f969-421b-923c-4548c9c73b7e\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"7bc93924-f969-421b-923c-4548c9c73b7e\"]}",
                "    [Data], ",
                "  RV_trafero_semantic_canonical_tsc_actualvq_ = #\"7bc93924-f969-421b-923c-4548c9c73b7e\"",
                "    {[entity = \"RV_trafero_semantic_canonical_tsc_actualvq\", version = \"\"]}",
                "    [Data], ",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    RV_trafero_semantic_canonical_tsc_actualvq_, ",
                "    {{\"ActualVQ\", \"Actual VQ\"}}",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Agent Metrics By Day",
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "ACW Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "137d6882-7821-4494-85bd-d0148ed886ad",
            "sourceColumn": "ACW Time",
            "summarizeBy": "sum"
          },
          {
            "name": "AUX Case Escalation Duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cc97524d-a7f8-43b7-990f-4759eddff434",
            "sourceColumn": "AUX Case Escalation Duration",
            "summarizeBy": "sum"
          },
          {
            "name": "AUX Inbound Case Work Duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2d1ad7fe-0034-4c80-8957-89dc20db6409",
            "sourceColumn": "AUX Inbound Case Work Duration",
            "summarizeBy": "sum"
          },
          {
            "name": "AUX Ready For Case Duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fcd0a947-ccfa-4b25-97e9-7812424976db",
            "sourceColumn": "AUX Ready For Case Duration",
            "summarizeBy": "sum"
          },
          {
            "name": "Agent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    ISBLANK ( RELATED ( Employee[Agent (EmployeeID)] ) ),",
              "    \"Agent Not Found\",",
              "    RELATED ( Employee[Agent (EmployeeID)] )",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "db4bd939-5bb6-4fd4-b6eb-8663c486f7cc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Available Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "36d5be66-41d2-4472-95b4-9bca8101e81d",
            "sourceColumn": "Available Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Break Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "975f1562-e370-478c-a61d-d677deaf6743",
            "sourceColumn": "Break Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Call Consult",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "251b24d6-6887-435b-b38e-64692bc4056d",
            "sourceColumn": "Call Consult",
            "summarizeBy": "sum"
          },
          {
            "name": "Call Dialing",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3df8faab-e5f6-4498-a086-0885c16a74f7",
            "sourceColumn": "Call Dialing",
            "summarizeBy": "sum"
          },
          {
            "name": "Call InBound Talk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a6ec8325-f0bd-4bbf-8429-adda6eba3a79",
            "sourceColumn": "Call InBound Talk",
            "summarizeBy": "sum"
          },
          {
            "name": "Call Internal Talk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ee21f002-1e7c-404d-a9fd-4926a3c37e29",
            "sourceColumn": "Call Internal Talk",
            "summarizeBy": "sum"
          },
          {
            "name": "Call On Hold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2f72237b-8ca2-4b10-a9b4-e5abce5c48a9",
            "sourceColumn": "Call On Hold",
            "summarizeBy": "sum"
          },
          {
            "name": "Call Ringing",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8638836b-ee3f-4ab8-94e6-a51eec628ed4",
            "sourceColumn": "Call Ringing",
            "summarizeBy": "sum"
          },
          {
            "name": "Calls Answered",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "67033b0f-5656-4740-845f-594917274653",
            "sourceColumn": "Calls Answered",
            "summarizeBy": "sum"
          },
          {
            "name": "CaseWorkTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "67decebc-5cdd-4fc7-8d92-0bf429efe035",
            "sourceColumn": "CaseWorkTime",
            "summarizeBy": "sum"
          },
          {
            "name": "Cases Closed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "'Agent Metrics By Day'[Cases Closed Dispatched] + 'Agent Metrics By Day'[Cases Closed Non Dispatched]"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a3c4c95f-7469-44c8-8371-382fd8e74e2f",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Cases Closed Dispatched",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "87d7d3ff-fdc9-4210-9db0-e6c225acf305",
            "sourceColumn": "Cases Closed Dispatched",
            "summarizeBy": "sum"
          },
          {
            "name": "Cases Closed Non Dispatched",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "825b5772-4340-458a-9b01-b82213a9fe51",
            "sourceColumn": "Cases Closed Non Dispatched",
            "summarizeBy": "sum"
          },
          {
            "name": "Cases Opened",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "577c89ae-6767-4653-8fb2-accca42dc8e6",
            "sourceColumn": "Cases Opened",
            "summarizeBy": "sum"
          },
          {
            "name": "CoachingTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "82b174f1-6d1b-4a15-8d3b-db8b7a1a40e7",
            "sourceColumn": "CoachingTime",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "67525f10-74a1-418b-a7b0-32a4e7d88ebf",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Date - Copy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dbc2cb42-c6b9-40e5-b6e0-4f51f21e7353",
            "sourceColumn": "Date - Copy",
            "summarizeBy": "none"
          },
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7680fb5c-71e1-4f30-a0f4-f0ce07672e24",
            "sourceColumn": "Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "EmployeeID|Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isKey": true,
            "lineageTag": "29a3bb81-2d8d-4e4a-a2dc-e6cc41e42764",
            "sourceColumn": "EmployeeID|Date",
            "summarizeBy": "none"
          },
          {
            "name": "Idle Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "928b4e77-e22c-40e3-8ca7-840a4560363b",
            "sourceColumn": "Idle Time",
            "summarizeBy": "sum"
          },
          {
            "name": "It Issue Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d6985db9-9326-4a4d-a109-871d66b5addb",
            "sourceColumn": "It Issue Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Logged In Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7de2f2fa-7406-40d8-a8b3-77147d9172ed",
            "sourceColumn": "Logged In Time",
            "summarizeBy": "sum"
          },
          {
            "name": "LunchTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f8640a72-4caa-4f0f-8b96-e2281258fad3",
            "sourceColumn": "LunchTime",
            "summarizeBy": "sum"
          },
          {
            "name": "MeetingTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e2c9f3c6-d713-400d-afb3-41dec620c77c",
            "sourceColumn": "MeetingTime",
            "summarizeBy": "sum"
          },
          {
            "name": "Mentor Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f8dde0b3-72d7-4703-a3ab-dab6c79bd994",
            "sourceColumn": "Mentor Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Mngr Level 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    ISBLANK ( RELATED ( Employee[Mgr1] ) ),",
              "    \"Mgr1 - Not Found\",",
              "    RELATED ( Employee[Mgr1] )",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "8cdc1e65-8e04-4b80-9714-53ba7ea21909",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "PCP Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a302a00f-f33f-441e-aed4-318deb9095e5",
            "sourceColumn": "PCP Time",
            "summarizeBy": "sum"
          },
          {
            "name": "PP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33271c38-c6c6-4ea9-b8ef-bbe3deba462a",
            "sourceColumn": "PP",
            "summarizeBy": "none"
          },
          {
            "name": "PPG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b001079-8bdc-4d34-bc90-6ad39a85caaa",
            "sourceColumn": "PPG",
            "summarizeBy": "none"
          },
          {
            "name": "Personal Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "430c2fda-9399-4abb-a155-7b0751b40972",
            "sourceColumn": "Personal Time",
            "summarizeBy": "sum"
          },
          {
            "name": "PrimaryProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d442935-2cd2-4105-8e7a-9e5b4c6f3484",
            "sourceColumn": "PrimaryProduct",
            "summarizeBy": "none"
          },
          {
            "name": "PrimaryProductGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd26cff2-36e9-4440-90b0-7d694f164f8c",
            "sourceColumn": "PrimaryProductGroup",
            "summarizeBy": "none"
          },
          {
            "name": "Special Projects Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "395eadea-cef3-435a-a13d-4ebc12f04db8",
            "sourceColumn": "Special Projects Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Talk Time Outbound Personal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d135d618-6e9f-4f49-bfbe-90542ac1a9c1",
            "sourceColumn": "Talk Time Outbound Personal",
            "summarizeBy": "sum"
          },
          {
            "name": "Training Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "760842f0-6001-44a1-b20d-7b98bb800561",
            "sourceColumn": "Training Time",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "29bdba7b-6b05-4162-bdf3-94f26f4839d4",
        "partitions": [
          {
            "name": "Agent Metrics By Day",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerBI.Dataflows(null),",
                "    #\"9a1d1e5d-e1a4-472c-8746-c8e79831dc62\" = Source{[workspaceId=\"9a1d1e5d-e1a4-472c-8746-c8e79831dc62\"]}[Data],",
                "    #\"8ff77f85-9fc5-43f9-9ac6-760c819ae620\" = #\"9a1d1e5d-e1a4-472c-8746-c8e79831dc62\"{[dataflowId=\"8ff77f85-9fc5-43f9-9ac6-760c819ae620\"]}[Data],",
                "    AgentMetricsByDay1 = #\"8ff77f85-9fc5-43f9-9ac6-760c819ae620\"{[entity=\"AgentMetricsByDay\"]}[Data]",
                "in",
                "    AgentMetricsByDay1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Agent Product Assignment",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2ee10a4-514f-4af8-9210-57ea7713cbb3",
            "sourceColumn": "Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "EmployeeID|ExtractDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isKey": true,
            "lineageTag": "17d8e363-b8d5-48db-a310-2311b2eda596",
            "sourceColumn": "EmployeeID|ExtractDate",
            "summarizeBy": "none"
          },
          {
            "name": "Extract Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6b4ab82e-a326-40ed-a40a-aeac3b7cb9af",
            "sourceColumn": "Extract Date",
            "summarizeBy": "none"
          },
          {
            "name": "ExtractDate - Copy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1bca96f3-3d29-4c86-ba83-0dc1442c4ba3",
            "sourceColumn": "ExtractDate - Copy",
            "summarizeBy": "none"
          },
          {
            "name": "Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14af8cdc-9ac0-4e52-b2d7-a7e308a3c59b",
            "sourceColumn": "Location",
            "summarizeBy": "none"
          },
          {
            "name": "Primary Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d4c11347-4dfc-4b31-9f74-b6757887c7c6",
            "sourceColumn": "Primary Product",
            "summarizeBy": "none"
          },
          {
            "name": "Primary Product Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ccf217e-3293-4010-b914-8648b02f202e",
            "sourceColumn": "Primary Product Group",
            "summarizeBy": "none"
          },
          {
            "name": "Secondary Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f68a6c41-03a5-41f3-a363-6d2eaa1b82b1",
            "sourceColumn": "Secondary Product",
            "summarizeBy": "none"
          },
          {
            "name": "Tertiary Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb1e8d24-0f35-4e6e-8f47-387830f0fd02",
            "sourceColumn": "Tertiary Product",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8c133427-b250-4f31-addd-41ba947c57b8",
        "measures": [
          {
            "name": "Max Extract Date",
            "expression": [
              "",
              "MAX ( 'Agent Product Assignment'[Extract Date] )",
              ""
            ],
            "formatString": "General Date",
            "lineageTag": "40c85543-507d-45ed-8356-2eb7472e7b7c"
          }
        ],
        "partitions": [
          {
            "name": "Agent Product Assignment-02d265de-df8c-46d1-b689-b3c395d6f0d5",
            "mode": "import",
            "queryGroup": "Dim\\Common",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"b85c5b01-590c-40a3-bdfb-610fa8b1429f\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"b85c5b01-590c-40a3-bdfb-610fa8b1429f\"]}",
                "    [Data],",
                "  AgentProductMapping_ = #\"b85c5b01-590c-40a3-bdfb-610fa8b1429f\"",
                "    {[entity = \"AgentProductMapping\", version = \"\"]}",
                "    [Data],",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    AgentProductMapping_,",
                "    {",
                "      {\"EmployeeId\", \"Employee ID\"},",
                "      {\"ExtractDate\", \"Extract Date\"},",
                "      {\"PrimaryProduct\", \"Primary Product\"},",
                "      {\"PrimaryProductGroup\", \"Primary Product Group\"},",
                "      {\"SecondaryProduct\", \"Secondary Product\"},",
                "      {\"TertiaryProduct\", \"Tertiary Product\"}",
                "    }",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "AgentProductMapping",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "EmployeeID|ExtractDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "261d2845-b0bf-4142-97e4-fc16168729ad",
            "sourceColumn": "EmployeeID|ExtractDate",
            "summarizeBy": "none"
          },
          {
            "name": "EmployeeId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6a879f8-0ddf-4894-adbb-e04c2a5fec74",
            "sourceColumn": "EmployeeId",
            "summarizeBy": "none"
          },
          {
            "name": "ExtractDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "84eda8e9-b988-4f96-84fc-c2099aa2e085",
            "sourceColumn": "ExtractDate",
            "summarizeBy": "none"
          },
          {
            "name": "ExtractDate - Copy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "152bd1a0-c2ca-4863-8391-874dfddcd882",
            "sourceColumn": "ExtractDate - Copy",
            "summarizeBy": "none"
          },
          {
            "name": "Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5b3a141-b23c-49ca-a1d7-23bbcb055699",
            "sourceColumn": "Location",
            "summarizeBy": "none"
          },
          {
            "name": "PP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "521f65f6-5d91-44d1-beb8-02e0b77d626c",
            "sourceColumn": "PP",
            "summarizeBy": "none"
          },
          {
            "name": "PPG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0e0d4d0-78d8-4115-a2b4-610880c86988",
            "sourceColumn": "PPG",
            "summarizeBy": "none"
          },
          {
            "name": "PrimaryProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29461e0c-4cda-47de-832e-5e5e5e45c305",
            "sourceColumn": "PrimaryProduct",
            "summarizeBy": "none"
          },
          {
            "name": "PrimaryProductGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2bb90960-a0af-4066-aacf-f655f5de4cad",
            "sourceColumn": "PrimaryProductGroup",
            "summarizeBy": "none"
          },
          {
            "name": "SecondaryProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46e72f72-76ee-4d9f-a7b9-9edd5367c6e4",
            "sourceColumn": "SecondaryProduct",
            "summarizeBy": "none"
          },
          {
            "name": "TertiaryProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dea56a8b-917f-4877-b2c8-10721e28297b",
            "sourceColumn": "TertiaryProduct",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a9a5e4bb-dbf7-4b4f-8c0f-8abd18414fda",
        "partitions": [
          {
            "name": "AgentProductMapping-1cf78bd2-88d6-4dd6-b284-160b813555aa",
            "mode": "import",
            "queryGroup": "Staging",
            "source": {
              "expression": [
                "let",
                "  Source = PowerBI.Dataflows(null),",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Source",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"b85c5b01-590c-40a3-bdfb-610fa8b1429f\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"b85c5b01-590c-40a3-bdfb-610fa8b1429f\"]}",
                "    [Data],",
                "  AgentProductMapping1 = #\"b85c5b01-590c-40a3-bdfb-610fa8b1429f\"",
                "    {[entity = \"AgentProductMapping\"]}",
                "    [Data],",
                "  #\"Replaced Value\" = Table.ReplaceValue(",
                "    AgentProductMapping1,",
                "    \"NULL\",",
                "    \"\",",
                "    Replacer.ReplaceText,",
                "    {\"PrimaryProduct\", \"PrimaryProductGroup\", \"SecondaryProduct\", \"TertiaryProduct\"}",
                "  ),",
                "  #\"Added Custom\" = Table.AddColumn(#\"Replaced Value\", \"PP\", each \"pp - \" & [PrimaryProduct]),",
                "  #\"Added Custom1\" = Table.AddColumn(#\"Added Custom\", \"PPG\", each \"ppg - \" & [PrimaryProductGroup]),",
                "  #\"Changed Type\" = Table.TransformColumnTypes(",
                "    #\"Added Custom1\",",
                "    {{\"PP\", type text}, {\"PPG\", type text}}",
                "  )",
                "in",
                "  #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Associate",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "fc0875adcf0746bcb619a999510c6c9e"
          }
        ],
        "columns": [
          {
            "name": "Business Site Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8a018da0-ef70-408c-9fb0-97c7064e8d91",
            "sourceColumn": "Employee[Business Site Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Display Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "82b9fdbb-8fdf-4168-ae17-dfaef912a8a6",
            "sourceColumn": "Employee[Display Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Employee Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fee5d1bc-b08d-44ae-91da-1ab85409720c",
            "sourceColumn": "Employee[Employee Status]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "EmployeeID|ExtractDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e42efb1d-587d-4b70-82db-5ffd4db749ea",
            "sourceColumn": "Agent Product Assignment[EmployeeID|ExtractDate]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Extract Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3c039dab-5e77-4031-83ce-1c9da80a5400",
            "sourceColumn": "Agent Product Assignment[Extract Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "597e0357-097b-4388-8bb9-7e0f68cd5a90",
            "sourceColumn": "Agent Product Assignment[Location]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Manager Level 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0f66a8c2-f9fe-45b7-94e0-1873e894f11e",
            "sourceColumn": "Employee[Manager Level 1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Manager Level 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3e6040bd-398f-497f-9e07-2d121bddc7e2",
            "sourceColumn": "Employee[Manager Level 2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Max Extract Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5a043905-00ee-4ad1-8720-a9c67128a95e",
            "sourceColumn": "[Max Extract Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Org Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "75f4d65d-8955-44e0-80fb-d9755c55b5c4",
            "sourceColumn": "Employee[Org Unit]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Primary Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8836e221-b588-47c5-b087-9572552ec20e",
            "sourceColumn": "Agent Product Assignment[Primary Product]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Primary Product Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d434c4d8-437b-43f5-9da7-a41b3bbb34e2",
            "sourceColumn": "Agent Product Assignment[Primary Product Group]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "5911656a-e132-41ef-90a4-0102e362ac3e",
        "partitions": [
          {
            "name": "Associate",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "    SUMMARIZECOLUMNS (",
                "        'Employee'[Display Name],",
                "        'Employee'[Employee Status],",
                "        'Employee'[Manager Level 1],",
                "        'Employee'[Manager Level 2],",
                "        'Employee'[Org Unit],",
                "        'Employee'[Business Site Name],",
                "        'Agent Product Assignment'[Location],",
                "        'Agent Product Assignment'[Primary Product],",
                "        'Agent Product Assignment'[Primary Product Group],",
                "        'Agent Product Assignment'[Extract Date],",
                "        'Agent Product Assignment'[EmployeeID|ExtractDate],",
                "        KEEPFILTERS (",
                "            TREATAS (",
                "                {",
                "                    \"A\"",
                "                },",
                "                'Employee'[Employee Status]",
                "            )",
                "        ),",
                "        \"Max Extract Date\", [Max Extract Date]",
                "        ",
                "    )"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Calls",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "ANI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b94397de-08f2-456c-98f3-cc4f9259e268",
            "sourceColumn": "ANI",
            "summarizeBy": "none"
          },
          {
            "name": "Actual Product Skill",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3b4f5da-2b1e-407b-9081-2740c314eeab",
            "sourceColumn": "Actual Product Skill",
            "summarizeBy": "none"
          },
          {
            "name": "ActualVQ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c3d8fc0f-3569-47b4-b7af-de4f19519ce2",
            "sourceColumn": "ActualVQ",
            "summarizeBy": "none"
          },
          {
            "name": "Agent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    ISBLANK ( RELATED ( Employee[Agent (EmployeeID)] ) ),",
              "    \"Agent Not Found\",",
              "    RELATED ( Employee[Agent (EmployeeID)] )",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "d56a214f-ea17-44e8-9aa9-d82b592b40fa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Answered Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15dc080d-0a7e-4c8a-ab94-4c7ebe2ceaf3",
            "sourceColumn": "Answered Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Call Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "e22dd603-a594-4927-ba1a-eeca7f6add48",
            "sourceColumn": "Call Date",
            "summarizeBy": "none"
          },
          {
            "name": "Call Rona",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d8a11a84-961a-4562-ba6a-583b3889b7c0",
            "sourceColumn": "Call Rona",
            "summarizeBy": "none"
          },
          {
            "name": "Calls Abandoned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "a9e6a9d1-5db1-4add-b305-4ddb8d86cb5c",
            "sourceColumn": "Calls Abandoned",
            "summarizeBy": "sum"
          },
          {
            "name": "Calls Answered",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "6fad37b3-7319-400f-8cdc-8828c8e2ea52",
            "sourceColumn": "Calls Answered",
            "summarizeBy": "sum"
          },
          {
            "name": "Calls Answered In 15 Minutes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "22a2141c-eada-4e81-8ad4-b241d24c8498",
            "sourceColumn": "Calls Answered In 15 Minutes",
            "summarizeBy": "sum"
          },
          {
            "name": "Calls Answered In 3 Minutes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "b325aec0-2e96-4e62-a909-0aacedd080d1",
            "sourceColumn": "Calls Answered In 3 Minutes",
            "summarizeBy": "sum"
          },
          {
            "name": "Calls Answered In 5 Minutes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "a64a23f4-7c47-41e9-9352-ae970e6b3cdd",
            "sourceColumn": "Calls Answered In 5 Minutes",
            "summarizeBy": "sum"
          },
          {
            "name": "Calls Handled",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "6480196b-d33e-4f1f-b08c-e86018b98186",
            "sourceColumn": "Calls Handled",
            "summarizeBy": "sum"
          },
          {
            "name": "Calls Offered",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "Calls[Calls Abandoned] + Calls[Calls Handled]",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "91b7f811-ead5-4e88-87d6-12f37807c8b2",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Case ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd502659-0144-481a-abd3-00470a848d0d",
            "sourceColumn": "Case ID",
            "summarizeBy": "none"
          },
          {
            "name": "Case Rona",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c9020ac2-247b-4e95-909e-57fec2a87d93",
            "sourceColumn": "Case Rona",
            "summarizeBy": "none"
          },
          {
            "name": "Connection ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e150b8b-9094-4065-9895-2f1e3c511e16",
            "sourceColumn": "Connection ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af1d1232-30b6-410a-b430-5fb76b306862",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "DNIS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0769909d-73e1-44c7-9fe5-7ca54e06a2e5",
            "sourceColumn": "DNIS",
            "summarizeBy": "none"
          },
          {
            "name": "DNIS Routing Modified",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44809df1-fd05-4a93-a677-e873328ea0bd",
            "sourceColumn": "DNIS Routing Modified",
            "summarizeBy": "none"
          },
          {
            "name": "Dial Duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "730b2c67-382a-43e2-94bb-74dc27ab313c",
            "sourceColumn": "Dial Duration",
            "summarizeBy": "sum"
          },
          {
            "name": "Direct Calls",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    AND (",
              "        Calls[Calls Answered] = 0,",
              "        AND (",
              "            Calls[Calls Offered] >= 1,",
              "            RELATED ( 'Technical Result'[Technical Result] ) = \"user\"",
              "        )",
              "    ),",
              "    \"Y\",",
              "    \"N\"",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "5327a67c-80b4-423e-ab70-f87b298d5867",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Employee Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "404687bd-ecdf-4474-baf9-765679032e29",
            "sourceColumn": "Employee Department",
            "summarizeBy": "none"
          },
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "863eae42-fe6a-4107-a8aa-217b016e1b1c",
            "sourceColumn": "Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "GMTEndTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d79499c9-fafe-4a65-bb52-258af0c1a361",
            "sourceColumn": "GMTEndTime",
            "summarizeBy": "none"
          },
          {
            "name": "GMTStartTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "094e2ef5-f49a-4634-93ed-55b83faab3da",
            "sourceColumn": "GMTStartTime",
            "summarizeBy": "none"
          },
          {
            "name": "Handle Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "68d8b435-333f-43b5-b001-c80053c5fc57",
            "sourceColumn": "Handle Type",
            "summarizeBy": "none"
          },
          {
            "name": "Hardware",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2527d31c-2e9f-4721-950c-743d809071ec",
            "sourceColumn": "Hardware",
            "summarizeBy": "none"
          },
          {
            "name": "Hold Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "c64c154b-1143-45fc-aa32-b7f525d644ee",
            "sourceColumn": "Hold Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Interaction ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "511348a6-1bc5-4297-9f59-a0c7a59ed0cd",
            "sourceColumn": "Interaction ID",
            "summarizeBy": "none"
          },
          {
            "name": "Interaction Resource ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "lineageTag": "47f8450c-22eb-41f9-a11c-98b5c7e2ed67",
            "sourceColumn": "Interaction Resource ID",
            "summarizeBy": "none"
          },
          {
            "name": "InteractionType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5545f4c6-ea78-4013-8e09-aa577c548d5b",
            "sourceColumn": "InteractionType",
            "summarizeBy": "none"
          },
          {
            "name": "Media Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7b1d86d-3a7d-45de-8bf5-284801022fd2",
            "sourceColumn": "Media Type",
            "summarizeBy": "none"
          },
          {
            "name": "Mgr1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    ISBLANK ( RELATED ( Employee[Mgr1] ) ),",
              "    \"Mgr1 - Not Found\",",
              "    RELATED ( Employee[Mgr1] )",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "dbb8d91a-8b82-44d9-bbd4-527f82896427",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Missing Wrap Up",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF ( AND ( Calls[Calls Answered] >= 1, Calls[Calls Offered] = 0 ), \"Y\", \"N\" )",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "29c47d7c-fe58-44c7-a176-7c402ef84c9d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Primary Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "602f1965-21c0-43cb-8145-15f37e44380f",
            "sourceColumn": "Primary Product",
            "summarizeBy": "none"
          },
          {
            "name": "Primary Product Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6d168aa-1a0c-49a3-b2d7-ceb8212b53b6",
            "sourceColumn": "Primary Product Group",
            "summarizeBy": "none"
          },
          {
            "name": "Product Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c39c89f4-5f4f-4414-b954-b9270406f6ea",
            "sourceColumn": "Product Category",
            "summarizeBy": "none"
          },
          {
            "name": "Queue Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d63facb1-9e9c-41eb-a9ce-6688a8319b8f",
            "sourceColumn": "Queue Name",
            "summarizeBy": "none"
          },
          {
            "name": "QueueNameIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "Calls[Queue Name] & \" (Queue)\"",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "29cda9d4-ce94-4559-aaa8-57ba9b6185e4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "RequestedVQ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a6bde9e2-1317-4901-a397-6923bbfb2c5c",
            "sourceColumn": "RequestedVQ",
            "summarizeBy": "none"
          },
          {
            "name": "RequiredSkill",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "52c86d21-cd25-4390-b1ed-d606320a75d3",
            "sourceColumn": "RequiredSkill",
            "summarizeBy": "none"
          },
          {
            "name": "ResourceRole",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "dd02454d-ea4e-459e-a934-124797685348",
            "sourceColumn": "ResourceRole",
            "summarizeBy": "none"
          },
          {
            "name": "ResourceType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ea6b0e89-1fcc-4bff-893f-cfc0f464c325",
            "sourceColumn": "ResourceType",
            "summarizeBy": "none"
          },
          {
            "name": "ResultReason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "001d91fa-07be-4c96-aadb-0878236bf8b7",
            "sourceColumn": "ResultReason",
            "summarizeBy": "none"
          },
          {
            "name": "Ring Duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "2ccba679-825c-4ede-94b8-61fc347458ab",
            "sourceColumn": "Ring Duration",
            "summarizeBy": "average"
          },
          {
            "name": "Skills",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "Calls[Actual Product Skill] & \" (Skill)\"",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "44164bbc-05b5-49cb-90c2-e2fc75d380cc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sort Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4db366bc-f9f2-4203-adf2-91cfd2ab48b9",
            "sourceColumn": "Sort Order",
            "summarizeBy": "sum"
          },
          {
            "name": "Talk Time Inbound",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "897b1ae6-6d33-43c1-bab1-2b72d8c7be8d",
            "sourceColumn": "Talk Time Inbound",
            "summarizeBy": "sum"
          },
          {
            "name": "Talk Time Internal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "66234f61-3830-4f16-a57a-34383148fa62",
            "sourceColumn": "Talk Time Internal",
            "summarizeBy": "sum"
          },
          {
            "name": "Talk Time Outbound",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "19ed9442-90d3-4213-821a-4de089e42ba9",
            "sourceColumn": "Talk Time Outbound",
            "summarizeBy": "sum"
          },
          {
            "name": "TechnicalResult",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "15d5576b-49d2-416e-8d0d-b595267ca0d9",
            "sourceColumn": "TechnicalResult",
            "summarizeBy": "none"
          },
          {
            "name": "Transfer Calls",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    AND (",
              "        Calls[Calls Answered] = 0,",
              "        AND (",
              "            Calls[Calls Offered] >= 1,",
              "            RELATED ( 'Technical Result'[Technical Result] ) = \"agent\"",
              "        )",
              "    ),",
              "    \"Y\",",
              "    \"N\"",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "88a75020-80f8-4571-a1e8-60448fd9c3fb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "VH Success Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7937d05-8be1-41eb-97b7-ba2f2d3be257",
            "sourceColumn": "VH Success Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Wait Duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "dc468534-3d50-43dd-a046-19d7c6746bd7",
            "sourceColumn": "Wait Duration",
            "summarizeBy": "sum"
          },
          {
            "name": "Wait Duration (Formatted)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "IF (",
              "    Calls[Calls Answered] = 1,",
              "    TIME ( TRUNC ( TRUNC ( Calls[Wait Duration] / 60 / 60 ) ), TRUNC (",
              "        TRUNC ( Calls[Wait Duration] ) / 60",
              "            - TRUNC ( TRUNC ( Calls[Wait Duration] / 60 / 60 ) ) * 60",
              "    ), MOD ( Calls[Wait Duration], 60 ) ),",
              "    TIME ( 0, 0, 0 )",
              ")",
              ""
            ],
            "formatString": "hh:nn:ss",
            "isDataTypeInferred": true,
            "lineageTag": "d3ea9489-8790-4785-9d03-b2e17c57f50b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "f5d9e425-eb6e-45f4-9a80-abb4c51c7e0c",
        "partitions": [
          {
            "name": "Calls-32899249-4687-4a64-9b98-38b66b34e645",
            "mode": "import",
            "queryGroup": "Fact",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces{[workspaceId=\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}[Data],",
                "    #\"2f604379-88e6-4253-b91e-33aa4068edae\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"{[dataflowId=\"2f604379-88e6-4253-b91e-33aa4068edae\"]}[Data],",
                "    Calls_ = #\"2f604379-88e6-4253-b91e-33aa4068edae\"{[entity=\"Calls\",version=\"\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(Calls_, each ([Media Type] = \"voice\")),",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    #\"Filtered Rows\",",
                "    {",
                "      {\"ActualProductSkill\", \"Actual Product Skill\"},",
                "      {\"CallDate\", \"Call Date\"},",
                "      {\"CallRona\", \"Call Rona\"},",
                "      {\"CallsAbandoned\", \"Calls Abandoned\"},",
                "      {\"CallsAnswered\", \"Calls Answered\"},",
                "      {\"CallsAnsweredIn15Minutes\", \"Calls Answered In 15 Minutes\"},",
                "      {\"CallsAnsweredIn3Minutes\", \"Calls Answered In 3 Minutes\"},",
                "      {\"CallsAnsweredIn5Minutes\", \"Calls Answered In 5 Minutes\"},",
                "      {\"CallsHandled\", \"Calls Handled\"},",
                "      {\"CaseId\", \"Case ID\"},",
                "      {\"CaseRona\", \"Case Rona\"},",
                "      {\"ConnectionId\", \"Connection ID\"},",
                "      {\"Customer_Id\", \"Customer ID\"},",
                "      {\"DialDuration\", \"Dial Duration\"},",
                "      {\"DNISRoutingModified\", \"DNIS Routing Modified\"},",
                "      {\"EmployeeDepartment\", \"Employee Department\"},",
                "      {\"EmployeeId\", \"Employee ID\"},",
                "      {\"HandleType\", \"Handle Type\"},",
                "      {\"HoldTime\", \"Hold Time\"},",
                "      {\"InteractionId\", \"Interaction ID\"},",
                "      {\"InteractionResourceId\", \"Interaction Resource ID\"},",
                "      {\"PrimaryProduct\", \"Primary Product\"},",
                "      {\"PrimaryProductGroup\", \"Primary Product Group\"},",
                "      {\"ProductCategory\", \"Product Category\"},",
                "      {\"RingDuration\", \"Ring Duration\"},",
                "      {\"TalktimeInbound\", \"Talk Time Inbound\"},",
                "      {\"TalktimeInternal\", \"Talk Time Internal\"},",
                "      {\"TalktimeOutbound\", \"Talk Time Outbound\"},",
                "      {\"VHSuccessFlag\", \"VH Success Flag\"},",
                "      {\"WaitDuration\", \"Wait Duration\"}",
                "    }",
                "  ),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",null,\"9999999999\",Replacer.ReplaceValue,{\"Employee ID\"})",
                "in",
                "  #\"Replaced Value\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Case Metrics",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Agent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    ISBLANK ( RELATED ( Employee[Agent (EmployeeID)] ) ),",
              "    \"N/A (9999999999)\",",
              "    RELATED ( Employee[Agent (EmployeeID)] )",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "c1fe1abb-33e5-4bd0-b442-f118da2f3f28",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Case Disposition",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4c691f5-9557-41d6-975c-b7f9f7975f50",
            "sourceColumn": "Case Disposition",
            "summarizeBy": "none"
          },
          {
            "name": "Category Code Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "RELATED ( 'Cases'[Category Code Description] )",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "93d19f42-6d2a-469b-b568-f3bcb5769184",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Close 24 Hour Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "dc62e89b-bdf2-48ab-a114-8d9cd18e353a",
            "sourceColumn": "Close 24 Hour Flag",
            "summarizeBy": "sum"
          },
          {
            "name": "Closed By Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    'Case Metrics'[Case Disposition] = \"ClosedBy\",",
              "    RELATED ( Departments[Employee Department] ),",
              "    \"n/a\"",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "886e6c6e-4c8b-44f4-91b5-7e58e2ab3f8f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Closed By Employee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    'Case Metrics'[Case Disposition] = \"ClosedBy\",",
              "    RELATED ( Employee[Display Name] ),",
              "    \"n/a\"",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "5cb24b48-bae8-4601-9e00-c6389c5ec0bb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Closed By ManagerLevel1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    'Case Metrics'[Case Disposition] = \"ClosedBy\",",
              "    RELATED ( Employee[Manager Level 1] ),",
              "    \"n/a\"",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "7546d677-eb0f-4d72-af61-fb4d398505f2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Community Case Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "RELATED ( 'Cases'[Self Service Flag] )",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "c213c852-b1a9-4a96-87cb-50b4dd993861",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CommunityCaseEligible",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "IF (",
              "    'Case Metrics'[Case Disposition] = \"OpenedBy\",",
              "    RELATED ( 'Cases'[Community Case Eligible] ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "6dee87a0-e62f-45f3-8804-4de21125d3df",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Created By Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    'Case Metrics'[Case Disposition] = \"OpenedBy\",",
              "    RELATED ( Departments[Employee Department] ),",
              "    \"n/a\"",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "a0bb7806-0151-4992-ae84-0c7a3b191302",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Created By Employee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    'Case Metrics'[Case Disposition] = \"OpenedBy\",",
              "    RELATED ( Employee[Display Name] ),",
              "    \"n/a\"",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "49988bd6-6921-4c61-8455-243f727546e3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Created By ManagerLevel1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    'Case Metrics'[Case Disposition] = \"OpenedBy\",",
              "    RELATED ( Employee[Manager Level 1] ),",
              "    \"n/a\"",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "f07dc87c-4283-4ee3-9b69-b98baa7b9e8d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc6707f8-2309-471e-a64f-61ac9c2a787a",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Department ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9622855-8603-4c8e-aeaf-713cdec728f1",
            "sourceColumn": "Department ID",
            "summarizeBy": "none"
          },
          {
            "name": "Dispatch Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d4fb7552-ff1e-4480-9077-2820272e1761",
            "sourceColumn": "Dispatch Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Dispensing/Infusion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    'Case Metrics'[Product Category]",
              "        IN {",
              "        \"CII Safe\",",
              "        \"Connect\",",
              "        \"ES\",",
              "        \"Hardware\",",
              "        \"IV Prep\",",
              "        \"Integration\",",
              "        \"Knowledge Portal\",",
              "        \"Legacy\",",
              "        \"Logistics\",",
              "        \"MedStation\",",
              "        \"Add-ons\",",
              "        \"PARx\",",
              "        \"Perioperative\"",
              "    },",
              "    \"Dispensing\",",
              "    IF ( 'Case Metrics'[Product Category] IN { \"Infusion\" }, \"Infusion\", \"Other\" )",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "2f4df256-e784-40cb-a019-1f9264b8e6cf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9d80381-9f48-4dd5-a998-903f8b7dc2d2",
            "sourceColumn": "Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Knowledge Article ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "RELATED ( 'Cases'[Knowledge Article ID] )",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "66bcaf11-bc45-449b-b97a-53ea6adae2ef",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Minutes To Close Service Request",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "f470eb96-f208-4865-8171-f4d5725b6acd",
            "sourceColumn": "Minutes To Close Service Request",
            "summarizeBy": "average"
          },
          {
            "name": "Mngr Level 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    ISBLANK ( RELATED ( Employee[Mgr1] ) ),",
              "    \"Mgr1 - NULL\",",
              "    RELATED ( Employee[Mgr1] )",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "cf6e0dcf-463f-420e-8383-3161e47428b5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Number of Reassignments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "ba2458d7-867c-4700-8a5e-b563e605adcf",
            "sourceColumn": "Number of Reassignments",
            "summarizeBy": "sum"
          },
          {
            "name": "PHL4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    LEN ( RELATED ( 'Cases'[PHL4] ) ) = 0,",
              "    \"PHL4 - NULL\",",
              "    RELATED ( 'Cases'[PHL4] )",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "3372ba74-dd96-46bd-98ae-308ca5198b2b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "PHL5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    LEN ( RELATED ( 'Cases'[PHL5] ) ) = 0,",
              "    \"PHL5 - NULL\",",
              "    RELATED ( 'Cases'[PHL5] )",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "b32628ee-6797-427a-b59c-472b9abdc49f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Primary Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14766624-70e8-43e8-82d4-2fd293266914",
            "sourceColumn": "Primary Product",
            "summarizeBy": "none"
          },
          {
            "name": "Primary Product Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8adbb04d-2bb4-4552-bcd8-96d0d2a0d95c",
            "sourceColumn": "Primary Product Group",
            "summarizeBy": "none"
          },
          {
            "name": "Priority Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "RELATED ( 'Cases'[Priority Description] )",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "5ae35f15-ba95-40ec-b4f0-5280b135083b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "RELATED ( 'Cases'[Product Sub Category] )",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "73b52b2a-7174-4d85-b08f-8dd177652d8f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Product Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "RELATED ( 'Cases'[Product Sub Category] )",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "cbae3f44-da1a-48ab-8528-4042274c09c9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Service Request ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "26e13ff2-7ae1-4043-bc6f-12ac6b76aa77",
            "sourceColumn": "Service Request ID",
            "summarizeBy": "none"
          },
          {
            "name": "TSC Complete Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67d8cb2b-1573-4e8e-8056-b1fb26457978",
            "sourceColumn": "TSC Complete Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Time To Assign Duration Minutes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "e9ecdef5-a06f-416f-b5f2-bb1d074a98b8",
            "sourceColumn": "Time To Assign Duration Minutes",
            "summarizeBy": "average"
          },
          {
            "name": "Transaction Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "06709739-8afe-4d3d-b16c-c9c551580e34",
            "sourceColumn": "Transaction Date",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1216b21e-4feb-440f-9768-9daa6fa7e165",
        "partitions": [
          {
            "name": "Case Metrics-2672db64-eac3-4f13-89e2-23cd3848d5ce",
            "mode": "import",
            "queryGroup": "Fact",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces{[workspaceId=\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}[Data],",
                "    #\"fc4fbbe3-2dd2-47ab-9249-1176eccad2a1\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"{[dataflowId=\"fc4fbbe3-2dd2-47ab-9249-1176eccad2a1\"]}[Data],",
                "    CaseMetrics_ = #\"fc4fbbe3-2dd2-47ab-9249-1176eccad2a1\"{[entity=\"CaseMetrics\",version=\"\"]}[Data],",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    CaseMetrics_,",
                "    {",
                "      {\"CaseDisposition\", \"Case Disposition\"},",
                "      {\"Close24HrFlag\", \"Close 24 Hour Flag\"},",
                "      {\"CustomerID\", \"Customer ID\"},",
                "      {\"DepartmentID\", \"Department ID\"},",
                "      {\"DispatchFlag\", \"Dispatch Flag\"},",
                "      {\"EmployeeID\", \"Employee ID\"},",
                "      {\"MinutesToCloseServiceRequest\", \"Minutes To Close Service Request\"},",
                "      {\"NoOfReassignment\", \"Number of Reassignments\"},",
                "      {\"PrimaryProduct\", \"Primary Product\"},",
                "      {\"PrimaryProductGroup\", \"Primary Product Group\"},",
                "      {\"ServiceRequestId\", \"Service Request ID\"},",
                "      {\"TimeToAssignDurationMins\", \"Time To Assign Duration Minutes\"},",
                "      {\"TransactionDate\", \"Transaction Date\"},",
                "      {\"TSCCompleteFlag\", \"TSC Complete Flag\"}",
                "    }",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Cases",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "CRM Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9084ddea-217f-4613-8fdb-b8b002c618e6",
            "sourceColumn": "CRM Description",
            "summarizeBy": "none"
          },
          {
            "name": "Category Code Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    ISTEXT ( RELATED ( 'Category Code Description'[Category Code Description] ) ),",
              "    RELATED ( 'Category Code Description'[Category Code Description] ),",
              "    \"Category - N/A\"",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "36e62ef7-72f5-4c43-91c0-6288ca5436bf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CategoryCodeDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f63ff30f-46ab-486e-9f1a-a6cdad8fc3af",
            "sourceColumn": "CategoryCodeDescription",
            "summarizeBy": "none"
          },
          {
            "name": "Close 24 Hour Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "19b9a42b-72eb-4c7a-89a9-fd92fc0e2b63",
            "sourceColumn": "Close 24 Hour Flag",
            "summarizeBy": "sum"
          },
          {
            "name": "Closed by Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39133eac-e63e-4fee-bad1-aca166b14bf2",
            "sourceColumn": "Closed by Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Community Case Eligible",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3650cd9-1bec-4a96-b687-43ffe68eb9ee",
            "sourceColumn": "Community Case Eligible",
            "summarizeBy": "none"
          },
          {
            "name": "ComplaintTypeDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "36e3bfc6-3532-4c07-9832-87c58bfb29e6",
            "sourceColumn": "ComplaintTypeDescription",
            "summarizeBy": "none"
          },
          {
            "name": "ContactCustomerBPartner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e116f6e8-521f-440f-8ce1-cfacb4e72e6e",
            "sourceColumn": "ContactCustomerBPartner",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Contact B Partner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0cc295c-16ec-4d0c-bdd2-97644435ea4b",
            "sourceColumn": "Customer Contact B Partner",
            "summarizeBy": "none"
          },
          {
            "name": "Dispatch Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e531cc1d-3aa9-41ff-a36e-92287f37a694",
            "sourceColumn": "Dispatch Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Employee Closed By",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1a4187b-5e3f-4c14-b788-298bb2436231",
            "sourceColumn": "Employee Closed By",
            "summarizeBy": "none"
          },
          {
            "name": "Employee Department Closed By",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8cdce0bd-3993-49a5-b515-37e0abd7f562",
            "sourceColumn": "Employee Department Closed By",
            "summarizeBy": "none"
          },
          {
            "name": "Employee Department Opened By",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b114b70-e3b8-4941-a09f-24df80d62a82",
            "sourceColumn": "Employee Department Opened By",
            "summarizeBy": "none"
          },
          {
            "name": "Employee Responsible",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d624d02-fe3d-4d53-982e-0ebdfb538def",
            "sourceColumn": "Employee Responsible",
            "summarizeBy": "none"
          },
          {
            "name": "First Non Queue Owner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70b5a094-4306-4d44-b307-4ab95db94a87",
            "sourceColumn": "First Non Queue Owner",
            "summarizeBy": "none"
          },
          {
            "name": "First Non Queue Owner Assign Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "40671541-185d-4a1f-a563-d0e56ff35f39",
            "sourceColumn": "First Non Queue Owner Assign Date",
            "summarizeBy": "none"
          },
          {
            "name": "IObject ID No Leading Zeros",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "179c6471-a7a0-4711-a54f-b09e0ab4554c",
            "sourceColumn": "IObject ID No Leading Zeros",
            "summarizeBy": "none"
          },
          {
            "name": "Knowledge Article ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a76508aa-dfff-4ba7-9b7f-124c0350ad17",
            "sourceColumn": "Knowledge Article ID",
            "summarizeBy": "none"
          },
          {
            "name": "Minutes to Close Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c30fc5d3-d035-468b-8ca9-10059c4d7aed",
            "sourceColumn": "Minutes to Close Bucket",
            "summarizeBy": "none"
          },
          {
            "name": "Minutes to Close Service Request",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "ed3d3e0f-3f9e-4099-8ebb-434f336d33dc",
            "sourceColumn": "Minutes to Close Service Request",
            "summarizeBy": "average"
          },
          {
            "name": "Number of Reassignments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "e95b8b96-bb7f-42ee-b3c5-befbc0a65650",
            "sourceColumn": "Number of Reassignments",
            "summarizeBy": "sum"
          },
          {
            "name": "Opened by Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79ffc460-eaff-4f65-98b5-01bcba79c08e",
            "sourceColumn": "Opened by Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Original Minutes to Close Service Request",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.00",
            "lineageTag": "04767e2a-fbf4-4374-ab58-7908f3540a2e",
            "sourceColumn": "Original Minutes to Close Service Request",
            "summarizeBy": "average"
          },
          {
            "name": "PHL4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "RELATED ( Materials[PHL4] )",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "f624f7cd-c7c5-4179-a4ee-4eae8f7f066d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "PHL5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "RELATED ( Materials[PHL5] )",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "0cfc546f-5286-4a1b-a7c6-a88afe61488f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Priority Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "RELATED ( 'Priority Description'[Priority Description] )",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "6168f936-656e-497e-86e9-0356a4e6033b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "PriorityDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "81a09dd0-2295-4362-90d7-bbdf708acbba",
            "sourceColumn": "PriorityDescription",
            "summarizeBy": "none"
          },
          {
            "name": "Product Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bbd133bf-91d0-4868-8309-1c476dd5c348",
            "sourceColumn": "Product Category",
            "summarizeBy": "none"
          },
          {
            "name": "Product Hierarchy Level 5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f74a0e02-d74a-4640-84d1-1dc88251e8d4",
            "sourceColumn": "Product Hierarchy Level 5",
            "summarizeBy": "none"
          },
          {
            "name": "Product Sub Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70d8a2da-a8ac-48ec-8740-ed7376f6379c",
            "sourceColumn": "Product Sub Category",
            "summarizeBy": "none"
          },
          {
            "name": "Self Service Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f171a776-341d-4383-a484-88e46594fe2e",
            "sourceColumn": "Self Service Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Service Order Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d3cf42d0-3713-4590-9180-e5fd99d69de3",
            "sourceColumn": "Service Order Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Service Request ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7d8ced4-4a4a-4d79-9654-6b778841c8d0",
            "sourceColumn": "Service Request ID",
            "summarizeBy": "none"
          },
          {
            "name": "Service Request Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "bd4d3a7e-a5e5-4e04-9f5d-53b6e949631a",
            "sourceColumn": "Service Request Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Ship to Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e1775c8-d015-4403-a9da-2720823a2e3f",
            "sourceColumn": "Ship to Customer",
            "summarizeBy": "none"
          },
          {
            "name": "StatusDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "139e7bf1-2d1a-472f-aacc-ebee0091fc7a",
            "sourceColumn": "StatusDescription",
            "summarizeBy": "none"
          },
          {
            "name": "TSC Closed by Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "e60dc0d9-eda7-440d-9677-ff8945f0b562",
            "sourceColumn": "TSC Closed by Date",
            "summarizeBy": "none"
          },
          {
            "name": "TSC Complete Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "743ee816-75df-48bb-8ba4-7cb7ac8517f4",
            "sourceColumn": "TSC Complete Flag",
            "summarizeBy": "none"
          },
          {
            "name": "TSCClosedByDate - Copy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isHidden": true,
            "lineageTag": "4ad8be6b-9523-4d42-ad1a-b8eccd830b6b",
            "sourceColumn": "TSCClosedByDate - Copy",
            "summarizeBy": "none"
          },
          {
            "name": "Time to Assign Duration Minutess",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "340a6726-71d8-4b70-baa4-f32040e1e54a",
            "sourceColumn": "Time to Assign Duration Minutess",
            "summarizeBy": "average"
          },
          {
            "name": "iObject ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc995903-4753-44fb-951a-69821bd77df7",
            "sourceColumn": "iObject ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fb456fb0-c03b-465b-9c80-de38221fca56",
        "partitions": [
          {
            "name": "Cases-54ad02ea-27fd-43d5-b4ef-572de8e30b52",
            "mode": "import",
            "queryGroup": "Fact",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces{[workspaceId=\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}[Data],",
                "    #\"02333bff-5df3-4bee-bbca-1c2aea2a33ba\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"{[dataflowId=\"02333bff-5df3-4bee-bbca-1c2aea2a33ba\"]}[Data],",
                "    Cases_ = #\"02333bff-5df3-4bee-bbca-1c2aea2a33ba\"{[entity=\"Cases\",version=\"\"]}[Data],",
                "  #\"Removed Columns\" = Table.RemoveColumns(",
                "    Cases_,",
                "    {",
                "      \"ComplaintType\",",
                "      \"CategoryCode\",",
                "      \"EmployeeFieldReporterId\",",
                "      \"SoftwareVersion\",",
                "      \"Priority\",",
                "      \"StatusCode\"",
                "    }",
                "  ),",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    #\"Removed Columns\",",
                "    {",
                "      {\"Close24HrFlag\", \"Close 24 Hour Flag\"},",
                "      {\"ClosedByEmployeeId\", \"Closed by Employee ID\"},",
                "      {\"CommunityCaseEligible\", \"Community Case Eligible\"},",
                "      {\"CRMDescription\", \"CRM Description\"},",
                "      {\"CustomerContactBPartner\", \"Customer Contact B Partner\"},",
                "      {\"DispatchFlag\", \"Dispatch Flag\"},",
                "      {\"EmployeeClosedBy\", \"Employee Closed By\"},",
                "      {\"EmployeeDepartmentClosedBy\", \"Employee Department Closed By\"},",
                "      {\"EmployeeDepartmentOpenedBy\", \"Employee Department Opened By\"},",
                "      {\"EmployeeRsponsible\", \"Employee Responsible\"},",
                "      {\"FirstNonQueueOwner\", \"First Non Queue Owner\"},",
                "      {\"FirstNonQueueOwnerAssignDate\", \"First Non Queue Owner Assign Date\"},",
                "      {\"iObjectId\", \"iObject ID\"},",
                "      {\"IObjectIdNoLeadingZeros\", \"IObject ID No Leading Zeros\"},",
                "      {\"KnowledgeArticleId\", \"Knowledge Article ID\"},",
                "      {\"MinutesToCloseBucket\", \"Minutes to Close Bucket\"},",
                "      {\"MinutesToCloseServiceRequest\", \"Minutes to Close Service Request\"},",
                "      {\"NoOfReassignment\", \"Number of Reassignments\"},",
                "      {\"OpenedByEmployeeId\", \"Opened by Employee ID\"},",
                "      {\"OriginalMinutesToClosesr\", \"Original Minutes to Close Service Request\"},",
                "      {\"Product_Category\", \"Product Category\"},",
                "      {\"Product_Sub_Category\", \"Product Sub Category\"},",
                "      {\"ProductHierarchyLevel5\", \"Product Hierarchy Level 5\"},",
                "      {\"SelfServiceFlag\", \"Self Service Flag\"},",
                "      {\"ServiceOrderFlag\", \"Service Order Flag\"},",
                "      {\"ServiceRequestId\", \"Service Request ID\"},",
                "      {\"ServiceRequestStartDate\", \"Service Request Start Date\"},",
                "      {\"ShipToCustomer\", \"Ship to Customer\"},",
                "      {\"TimeToAssignDurationMins\", \"Time to Assign Duration Minutess\"},",
                "      {\"TSCClosedByDate\", \"TSC Closed by Date\"},",
                "      {\"TSCCompleteFlag\", \"TSC Complete Flag\"}",
                "    }",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Cases Closed",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3cf441043f224d67924a484b17ca2740"
          }
        ],
        "columns": [
          {
            "name": "Closed By Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0aee8db7-1bd1-4b0c-96ef-55025ce0c45e",
            "sourceColumn": "Case Metrics[Closed By Department]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Closed By Employee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5ee553ca-0cd6-4a0c-a793-e04a528a248a",
            "sourceColumn": "Case Metrics[Closed By Employee]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Closed By Manager Level 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "96b558ed-f497-41c1-86c5-568d16987af5",
            "sourceColumn": "Case Metrics[Closed By ManagerLevel1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Service Request ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "981bdded-deb3-4847-8bef-ec2cb50a02de",
            "sourceColumn": "Case Metrics[Service Request ID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "74c42a4c-a378-4a40-809b-5bac821e98a4",
        "partitions": [
          {
            "name": "Cases Closed-0e50eb31-5bcd-45d1-89a4-d44ded0a2012",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZECOLUMNS (",
                "    'Case Metrics'[Service Request Id],",
                "    'Case Metrics'[Closed By Employee],",
                "    'Case Metrics'[Closed By ManagerLevel1],",
                "    'Case Metrics'[Closed By Department],",
                "    KEEPFILTERS ( TREATAS ( { \"ClosedBy\" }, 'Case Metrics'[Case Disposition] ) )",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Cases Open",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "36c31c3cf0854c2eb305f66b4db049ff"
          }
        ],
        "columns": [
          {
            "name": "Created By Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "90ecc611-1d87-494f-9eb4-29a22d223b7e",
            "sourceColumn": "Case Metrics[Created By Department]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Created By Employee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e3d4bd0b-8c01-427f-b1bb-79b6597b759d",
            "sourceColumn": "Case Metrics[Created By Employee]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Created By Manager Level 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "b3487248-ff76-444b-959c-8e83b9123f48",
            "sourceColumn": "Case Metrics[Created By ManagerLevel1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Service Request ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4c160bfa-bec7-4f3a-9e21-262aab970e9a",
            "sourceColumn": "Case Metrics[Service Request ID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "6ad8aa12-2d8c-4d0e-9e00-c60e226cb929",
        "partitions": [
          {
            "name": "Cases Open-51b3c4e8-d292-4bd3-9188-0bae07bcf0d2",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZECOLUMNS (",
                "    'Case Metrics'[Service Request Id],",
                "    'Case Metrics'[Created By Employee],",
                "    'Case Metrics'[Created By ManagerLevel1],",
                "    'Case Metrics'[Created By Department],",
                "    KEEPFILTERS ( TREATAS ( { \"OpenedBy\" }, 'Case Metrics'[Case Disposition] ) )",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Category Code Description",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Category Code Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7593bee6-cdf6-46ae-a8ca-dc0f8f10c5db",
            "sourceColumn": "Category Code Description",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "77b08a59-edf2-400c-8f92-6a7fe1dbfbcb",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c076ef49-9b32-477a-a15c-0dc7d0d65550",
        "partitions": [
          {
            "name": "Category Code Description-26dea123-3a33-48f9-b1c1-6472be18bd3e",
            "mode": "import",
            "queryGroup": "Dim\\Cases",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"cae4cbc8-6439-4f0e-82cb-342d18175d63\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"cae4cbc8-6439-4f0e-82cb-342d18175d63\"]}",
                "    [Data],",
                "  RV_trafero_semantic_canonical_tsc_categorycodedescription_",
                "    = #\"cae4cbc8-6439-4f0e-82cb-342d18175d63\"",
                "    {[entity = \"RV_trafero_semantic_canonical_tsc_categorycodedescription\", version = \"\"]}",
                "    [Data],",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    RV_trafero_semantic_canonical_tsc_categorycodedescription_,",
                "    {{\"CategoryCodeDescription\", \"Category Code Description\"}}",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Complaint Type Description",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Complaint Type Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a96fb16d-5eb1-4f74-9f8d-604b96c3f2fd",
            "sourceColumn": "Complaint Type Description",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "948df186-47ea-41ad-9ef0-4bb8bbeec676",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6d0f0745-3de7-4124-b6bb-68bf00274c08",
        "partitions": [
          {
            "name": "Complaint Type Description-a94abb7b-ec2e-4154-80a3-76ed4f04e633",
            "mode": "import",
            "queryGroup": "Dim\\Cases",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"0429b8e8-8415-405f-9c92-7fb368cd9911\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"0429b8e8-8415-405f-9c92-7fb368cd9911\"]}",
                "    [Data],",
                "  RV_trafero_semantic_canonical_tsc_complainttypedescription_",
                "    = #\"0429b8e8-8415-405f-9c92-7fb368cd9911\"",
                "    {[entity = \"RV_trafero_semantic_canonical_tsc_complainttypedescription\", version = \"\"]}",
                "    [Data],",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    RV_trafero_semantic_canonical_tsc_complainttypedescription_,",
                "    {{\"ComplaintTypeDescription\", \"Complaint Type Description\"}}",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer Contacts",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Competency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ead8574-664d-4362-8023-cea99f83463c",
            "sourceColumn": "Competency",
            "summarizeBy": "none"
          },
          {
            "name": "ContactBPartner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3d3e89a-3647-45aa-9710-961f8ca28045",
            "sourceColumn": "ContactBPartner",
            "summarizeBy": "none"
          },
          {
            "name": "ContactCustomerBPartner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bbb3433b-d375-4341-bb09-6267e8c45827",
            "sourceColumn": "ContactCustomerBPartner",
            "summarizeBy": "none"
          },
          {
            "name": "ContactName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2c348cf-c151-49e5-ab96-ceb09d81c42f",
            "sourceColumn": "ContactName",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "74e53bdc-c391-4a38-a425-5aa35e48c504",
            "sourceColumn": "CreatedDate",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerContactsIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "19e1cdc9-fa1c-42d3-9cd9-93f9d69bfb3e",
            "sourceColumn": "CustomerContactsIndex",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57d62f1f-a845-42d9-929d-49404250b1d5",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "EmailAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "156702af-5e52-40f0-8577-d5c27487fa00",
            "sourceColumn": "EmailAddress",
            "summarizeBy": "none"
          },
          {
            "name": "FaxNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8997255a-704e-4dec-8022-56a1f66076bf",
            "sourceColumn": "FaxNumber",
            "summarizeBy": "none"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6442d75f-b7e9-4abb-871a-87269f9c9417",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2769b83-0a73-4de2-8d5b-b7342669df91",
            "sourceColumn": "LastName",
            "summarizeBy": "none"
          },
          {
            "name": "MiddleName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00ff9979-9743-48e4-8996-233e88a162b9",
            "sourceColumn": "MiddleName",
            "summarizeBy": "none"
          },
          {
            "name": "SourceSystem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c6ffeb0-499e-446e-ac66-2a364de52176",
            "sourceColumn": "SourceSystem",
            "summarizeBy": "none"
          },
          {
            "name": "TelePhoneNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e2617ea-d197-412b-9a46-7b6e9ad96394",
            "sourceColumn": "TelePhoneNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c037eeec-dcb3-4ec4-8a02-e0dbf61bf796",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "46380dee-c383-44f1-9e46-93cc9b494a18",
        "partitions": [
          {
            "name": "Customer Contacts-84128ddd-61bb-4ed5-ad34-7f9c364ebb11",
            "mode": "import",
            "queryGroup": "Dim\\Cases",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces{[workspaceId=\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}[Data],",
                "    #\"e350b2dd-f310-41bf-adba-a82238ec5e2d\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"{[dataflowId=\"e350b2dd-f310-41bf-adba-a82238ec5e2d\"]}[Data],",
                "    ContactCustomerBPartner_ = #\"e350b2dd-f310-41bf-adba-a82238ec5e2d\"{[entity=\"ContactCustomerBPartner\",version=\"\"]}[Data]",
                "in",
                "    ContactCustomerBPartner_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customers",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Account Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af2142ea-d3e7-4dc3-82a5-432079eeffc6",
            "sourceColumn": "Account Group",
            "summarizeBy": "none"
          },
          {
            "name": "Account Group Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d8e98d6-b593-4e88-b403-22e3d645dcb6",
            "sourceColumn": "Account Group Name",
            "summarizeBy": "none"
          },
          {
            "name": "Account Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "231bcbb1-16b2-442c-8fe5-cdf9805b96ad",
            "sourceColumn": "Account Type",
            "summarizeBy": "none"
          },
          {
            "name": "Account Type Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6e1c35b-5c44-4c2b-be39-2e40bfcdb43d",
            "sourceColumn": "Account Type Description",
            "summarizeBy": "none"
          },
          {
            "name": "Active ISMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12578f75-5f9c-46f9-a5a3-95f6af613b69",
            "sourceColumn": "Active ISMS",
            "summarizeBy": "none"
          },
          {
            "name": "Active SW Maintenance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5aa0063f-cc69-49ae-bdc4-9cc4d07ac51c",
            "sourceColumn": "Active SW Maintenance",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b0f93dce-87e2-4660-a9c9-be730596fdc5",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Classification Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77b234f0-47ea-4e56-9de6-6dc144dcce30",
            "sourceColumn": "Classification Code",
            "summarizeBy": "none"
          },
          {
            "name": "Classification Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3d94fa8-2f5d-4437-93c1-dfdaa3cefe56",
            "sourceColumn": "Classification Description",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61852cc2-544d-4f47-b790-c133ea39f0e7",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isKey": true,
            "lineageTag": "de64b154-0a0c-4c84-ace8-2ddbba02993b",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer ID No Leading Zero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72d3f891-d03a-40f9-a480-1fd991dac9b7",
            "sourceColumn": "Customer ID No Leading Zero",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Name - Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "Customers[Name] & \" (\" & Customers[Customer ID No Leading Zero] & \")\"",
            "isDataTypeInferred": true,
            "lineageTag": "d77b1297-b2c0-490d-9304-7f0ef9c6caa6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Customer Software Version Infusion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3bbe5cc-3ed9-4c55-a6dd-f1303cc87a72",
            "sourceColumn": "Customer Software Version Infusion",
            "summarizeBy": "none"
          },
          {
            "name": "Deletion Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54516e78-9612-4d41-b2ea-2a5d854ff5a3",
            "sourceColumn": "Deletion Flag",
            "summarizeBy": "none"
          },
          {
            "name": "Enterprise Account Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db0ac067-a746-46e8-bc08-f1e4155984eb",
            "sourceColumn": "Enterprise Account Name",
            "summarizeBy": "none"
          },
          {
            "name": "Enterprise Account Network",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82e142f2-64c6-4431-a3ed-15d337134236",
            "sourceColumn": "Enterprise Account Network",
            "summarizeBy": "none"
          },
          {
            "name": "Enterprise Account Network Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b13aa381-ef23-4dca-9f7e-af346eb5cbb5",
            "sourceColumn": "Enterprise Account Network Name",
            "summarizeBy": "none"
          },
          {
            "name": "Enterprise Account Network Parent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee02257a-b2f1-4b69-a316-47a6bb1a23bb",
            "sourceColumn": "Enterprise Account Network Parent",
            "summarizeBy": "none"
          },
          {
            "name": "Enterprise Account Network Parent Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac8b58d0-3135-43ff-8c3c-33879d88231e",
            "sourceColumn": "Enterprise Account Network Parent Name",
            "summarizeBy": "none"
          },
          {
            "name": "Enterprise Account Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e61650d8-e5fc-4c5c-ae3b-f8ed70caee03",
            "sourceColumn": "Enterprise Account Number",
            "summarizeBy": "none"
          },
          {
            "name": "Enterprise Account Number SFID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4fbd0639-5134-474d-b8f9-325364f4b11b",
            "sourceColumn": "Enterprise Account Number SFID",
            "summarizeBy": "none"
          },
          {
            "name": "FSM Employee ID Dispensing",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a31510a0-ac0d-4b0d-b9ed-ccd94314f50d",
            "sourceColumn": "FSM Employee ID Dispensing",
            "summarizeBy": "none"
          },
          {
            "name": "FSM Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2413f8a-8ad5-46f9-a402-758395588d71",
            "sourceColumn": "FSM Name",
            "summarizeBy": "none"
          },
          {
            "name": "Industry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76ff7e0e-5534-4b54-88ce-0b2d45f80d0e",
            "sourceColumn": "Industry",
            "summarizeBy": "none"
          },
          {
            "name": "Industry Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c932887c-ed44-477c-834c-3d6ab2eda654",
            "sourceColumn": "Industry Code",
            "summarizeBy": "none"
          },
          {
            "name": "Infusion Area Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9be174e-4d77-48df-8096-c8195c0ea6fc",
            "sourceColumn": "Infusion Area Name",
            "summarizeBy": "none"
          },
          {
            "name": "Infusion Area Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5539ba4-28de-499d-b368-2fbbc1e9bcd5",
            "sourceColumn": "Infusion Area Number",
            "summarizeBy": "none"
          },
          {
            "name": "Infusion Area Rep Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb299a9e-2864-49a9-a73e-194f77be33a3",
            "sourceColumn": "Infusion Area Rep Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Infusion Area Rep Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ffc80fa8-e1bd-409c-b2e0-9c9512ef272a",
            "sourceColumn": "Infusion Area Rep Name",
            "summarizeBy": "none"
          },
          {
            "name": "Infusion Region Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e9e9727-4738-462e-a4a5-41b0a0e429b4",
            "sourceColumn": "Infusion Region Name",
            "summarizeBy": "none"
          },
          {
            "name": "Infusion Region Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ac01da6-9495-495b-8b04-3a4aba862bf2",
            "sourceColumn": "Infusion Region Number",
            "summarizeBy": "none"
          },
          {
            "name": "Infusion Region Rep Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47a41638-89a9-4f98-8883-3cc082e777ef",
            "sourceColumn": "Infusion Region Rep Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Infusion Region Rep Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8755064c-eae3-4e41-a1be-9d46476eee5d",
            "sourceColumn": "Infusion Region Rep Name",
            "summarizeBy": "none"
          },
          {
            "name": "Infusion Territory Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "acdb25ee-fdb7-46ff-bcc1-60b4e2f29c82",
            "sourceColumn": "Infusion Territory Name",
            "summarizeBy": "none"
          },
          {
            "name": "Infusion Territory Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "849f255d-8aed-4138-ba24-f703fc021617",
            "sourceColumn": "Infusion Territory Number",
            "summarizeBy": "none"
          },
          {
            "name": "Infusion Territory Rep Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f0e0624-bf11-4f1a-b586-5014eee10c8c",
            "sourceColumn": "Infusion Territory Rep Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Infusion Territory Rep Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8592e3c4-6785-4e2f-93c8-d00d66527ba3",
            "sourceColumn": "Infusion Territory Rep Name",
            "summarizeBy": "none"
          },
          {
            "name": "Latest Server Software Version",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ed6d272-a7dd-47a1-9b4f-66ce42ce70ec",
            "sourceColumn": "Latest Server Software Version",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f8380c9-9809-4b17-a465-17ac001e49b6",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Server Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cad7df79-3f7e-4184-8b47-5641c3f800b8",
            "sourceColumn": "Server Customer",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6b1052d-819c-4b58-b5d4-fa6683614f8f",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "With Alaris PCU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1536d50e-c837-4076-9bf4-4a00bcdac782",
            "sourceColumn": "With Alaris PCU",
            "summarizeBy": "none"
          },
          {
            "name": "ZSC3 Contract End Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "320d9b5b-eb3a-4496-9558-bbcb55f40103",
            "sourceColumn": "ZSC3 Contract End Date",
            "summarizeBy": "none"
          },
          {
            "name": "ZSC3 Contract Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "f2475499-c788-42fc-834b-4f8f2c1e6af8",
            "sourceColumn": "ZSC3 Contract Start Date",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "806c8513-a677-4eda-a3cf-0ab15a5bc4f7",
        "partitions": [
          {
            "name": "Customers-4792cf0e-d28a-4095-9051-95a73bf1920d",
            "mode": "import",
            "queryGroup": "Dim\\Common",
            "source": {
              "expression": [
                "let",
                "  Source = Table.Combine({#\"CallsCustomer\", CasesCustomer}),",
                "  #\"Grouped rows\" = Table.Group(",
                "    Source,",
                "    {\"CustomerID\"},",
                "    {{\"Count\", each Table.RowCount(_), Int64.Type}}",
                "  ),",
                "  #\"Filtered Rows\" = Table.SelectRows(#\"Grouped rows\", each ([CustomerID] <> null)),",
                "  #\"Removed columns\" = Table.RemoveColumns(#\"Filtered Rows\", {\"Count\"}),",
                "  #\"Merged queries\" = Table.NestedJoin(",
                "    #\"Removed columns\",",
                "    {\"CustomerID\"},",
                "    RV_mms_canonical_bdx_customer_master,",
                "    {\"Customer_ID\"},",
                "    \"RV_mms_canonical_bdx_customer_master\",",
                "    JoinKind.LeftOuter",
                "  ),",
                "  #\"Expanded RV_mms_canonical_bdx_customer_master\" = Table.ExpandTableColumn(",
                "    #\"Merged queries\",",
                "    \"RV_mms_canonical_bdx_customer_master\",",
                "    {",
                "      \"CustomerIdNoLeadingZero\",",
                "      \"Name\",",
                "      \"City\",",
                "      \"State\",",
                "      \"Country\",",
                "      \"IndustryCode\",",
                "      \"Industry\",",
                "      \"AccountGroup\",",
                "      \"AccountGroupName\",",
                "      \"ClassificationCode\",",
                "      \"ClassificationDescription\",",
                "      \"AccountType\",",
                "      \"AccountTypeDescription\",",
                "      \"DeletionFlag\",",
                "      \"CustomerSWVersion_Infusion\",",
                "      \"InfusionTerritoryRepName\",",
                "      \"InfusionTerritoryName\",",
                "      \"InfusionTerritoryNumber\",",
                "      \"InfusionTerritoryRepEmployeeId\",",
                "      \"InfusionAreaRepName\",",
                "      \"InfusionAreaName\",",
                "      \"InfusionAreaNumber\",",
                "      \"InfusionAreaRepEmployeeId\",",
                "      \"InfusionRegionRepName\",",
                "      \"InfusionRegionName\",",
                "      \"InfusionRegionNumber\",",
                "      \"InfusionRegionRepEmployeeId\",",
                "      \"EnterpriseAccountNumberSFID\",",
                "      \"EnterpriseAccountName\",",
                "      \"EnterpriseAccountNetwork\",",
                "      \"EnterpriseAccountNetworkName\",",
                "      \"EnterpriseAccountNetworkParent\",",
                "      \"EnterpriseAccountNetworkParentName\",",
                "      \"EnterpriseAccountNumber\",",
                "      \"WithAlarisPCU\",",
                "      \"ServerCustomer\",",
                "      \"LatestServerSWVersion\",",
                "      \"ActiveSWMaintenance\",",
                "      \"ZSC3ContractStartDate\",",
                "      \"ZSC3ContractEndDate\",",
                "      \"ActiveISMS\",",
                "      \"FSMEmployeeId_Dispensing\",",
                "      \"FSMName\"",
                "    },",
                "    {",
                "      \"CustomerIdNoLeadingZero\",",
                "      \"Name\",",
                "      \"City\",",
                "      \"State\",",
                "      \"Country\",",
                "      \"IndustryCode\",",
                "      \"Industry\",",
                "      \"AccountGroup\",",
                "      \"AccountGroupName\",",
                "      \"ClassificationCode\",",
                "      \"ClassificationDescription\",",
                "      \"AccountType\",",
                "      \"AccountTypeDescription\",",
                "      \"DeletionFlag\",",
                "      \"CustomerSWVersion_Infusion\",",
                "      \"InfusionTerritoryRepName\",",
                "      \"InfusionTerritoryName\",",
                "      \"InfusionTerritoryNumber\",",
                "      \"InfusionTerritoryRepEmployeeId\",",
                "      \"InfusionAreaRepName\",",
                "      \"InfusionAreaName\",",
                "      \"InfusionAreaNumber\",",
                "      \"InfusionAreaRepEmployeeId\",",
                "      \"InfusionRegionRepName\",",
                "      \"InfusionRegionName\",",
                "      \"InfusionRegionNumber\",",
                "      \"InfusionRegionRepEmployeeId\",",
                "      \"EnterpriseAccountNumberSFID\",",
                "      \"EnterpriseAccountName\",",
                "      \"EnterpriseAccountNetwork\",",
                "      \"EnterpriseAccountNetworkName\",",
                "      \"EnterpriseAccountNetworkParent\",",
                "      \"EnterpriseAccountNetworkParentName\",",
                "      \"EnterpriseAccountNumber\",",
                "      \"WithAlarisPCU\",",
                "      \"ServerCustomer\",",
                "      \"LatestServerSWVersion\",",
                "      \"ActiveSWMaintenance\",",
                "      \"ZSC3ContractStartDate\",",
                "      \"ZSC3ContractEndDate\",",
                "      \"ActiveISMS\",",
                "      \"FSMEmployeeId_Dispensing\",",
                "      \"FSMName\"",
                "    }",
                "  ),",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    #\"Expanded RV_mms_canonical_bdx_customer_master\",",
                "    {",
                "      {\"CustomerID\", \"Customer ID\"},",
                "      {\"EnterpriseAccountNetworkName\", \"Enterprise Account Network Name\"},",
                "      {\"ClassificationDescription\", \"Classification Description\"},",
                "      {\"EnterpriseAccountNetworkParentName\", \"Enterprise Account Network Parent Name\"},",
                "      {\"FSMName\", \"FSM Name\"},",
                "      {\"AccountGroup\", \"Account Group\"},",
                "      {\"AccountGroupName\", \"Account Group Name\"},",
                "      {\"CustomerIdNoLeadingZero\", \"Customer ID No Leading Zero\"},",
                "      {\"EnterpriseAccountNumber\", \"Enterprise Account Number\"},",
                "      {\"IndustryCode\", \"Industry Code\"},",
                "      {\"ClassificationCode\", \"Classification Code\"},",
                "      {\"AccountType\", \"Account Type\"},",
                "      {\"AccountTypeDescription\", \"Account Type Description\"},",
                "      {\"InfusionTerritoryRepName\", \"Infusion Territory Rep Name\"},",
                "      {\"InfusionAreaRepName\", \"Infusion Area Rep Name\"},",
                "      {\"InfusionAreaNumber\", \"Infusion Area Number\"},",
                "      {\"InfusionAreaRepEmployeeId\", \"Infusion Area Rep Employee ID\"},",
                "      {\"InfusionRegionRepName\", \"Infusion Region Rep Name\"},",
                "      {\"InfusionRegionName\", \"Infusion Region Name\"},",
                "      {\"InfusionRegionNumber\", \"Infusion Region Number\"},",
                "      {\"EnterpriseAccountNumberSFID\", \"Enterprise Account Number SFID\"},",
                "      {\"EnterpriseAccountNetworkParent\", \"Enterprise Account Network Parent\"},",
                "      {\"InfusionAreaName\", \"Infusion Area Name\"},",
                "      {\"WithAlarisPCU\", \"With Alaris PCU\"},",
                "      {\"ServerCustomer\", \"Server Customer\"},",
                "      {\"ZSC3ContractStartDate\", \"ZSC3 Contract Start Date\"},",
                "      {\"ZSC3ContractEndDate\", \"ZSC3 Contract End Date\"},",
                "      {\"FSMEmployeeId_Dispensing\", \"FSM Employee ID Dispensing\"},",
                "      {\"ActiveISMS\", \"Active ISMS\"},",
                "      {\"InfusionRegionRepEmployeeId\", \"Infusion Region Rep Employee ID\"},",
                "      {\"InfusionTerritoryName\", \"Infusion Territory Name\"},",
                "      {\"InfusionTerritoryNumber\", \"Infusion Territory Number\"},",
                "      {\"InfusionTerritoryRepEmployeeId\", \"Infusion Territory Rep Employee ID\"},",
                "      {\"ActiveSWMaintenance\", \"Active SW Maintenance\"},",
                "      {\"CustomerSWVersion_Infusion\", \"Customer Software Version Infusion\"},",
                "      {\"DeletionFlag\", \"Deletion Flag\"},",
                "      {\"EnterpriseAccountName\", \"Enterprise Account Name\"},",
                "      {\"EnterpriseAccountNetwork\", \"Enterprise Account Network\"},",
                "      {\"LatestServerSWVersion\", \"Latest Server Software Version\"}",
                "    }",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DNIS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DNIS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca5c57ac-07fa-4d11-88a2-08d77cff4ad9",
            "sourceColumn": "DNIS",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a422af3e-eb4e-4340-ba5e-a46aef67cec7",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "59d28a14-60d3-4409-a72e-88e59f562b9f",
        "partitions": [
          {
            "name": "DNIS-586fb2ab-0b60-488d-bd73-0bb8a0636da9",
            "mode": "import",
            "queryGroup": "Dim\\Calls",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"17bdee7b-f79c-46e3-90e0-42c51e1583cb\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"17bdee7b-f79c-46e3-90e0-42c51e1583cb\"]}",
                "    [Data],",
                "  RV_trafero_semantic_canonical_tsc_dnis_ = #\"17bdee7b-f79c-46e3-90e0-42c51e1583cb\"",
                "    {[entity = \"RV_trafero_semantic_canonical_tsc_dnis\", version = \"\"]}",
                "    [Data]",
                "in",
                "  RV_trafero_semantic_canonical_tsc_dnis_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Departments",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DepartmentID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isKey": true,
            "lineageTag": "fb50ae2d-7f23-4a61-b78a-4f16d3bd2939",
            "sourceColumn": "DepartmentID",
            "summarizeBy": "none"
          },
          {
            "name": "Employee Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e739d9f-3f9e-461e-a678-75edd77b5716",
            "sourceColumn": "Employee Department",
            "summarizeBy": "none"
          },
          {
            "name": "Employee Org Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ddb2f3bc-0fc6-46d7-a306-afabaff5cdc8",
            "sourceColumn": "Employee Org Description",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e887e2fe-7cda-4f3c-ac79-035f04b640d7",
        "partitions": [
          {
            "name": "Departments-918e2e8f-c874-4035-82ae-cc122cd66fc1",
            "mode": "import",
            "queryGroup": "Dim\\Common",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"73591bbd-0604-4f13-9d05-04508587cee7\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"73591bbd-0604-4f13-9d05-04508587cee7\"]}",
                "    [Data],",
                "  RV_trafero_semantic_canonical_tsc_scorecard_departments_ = #\"73591bbd-0604-4f13-9d05-04508587cee7\"",
                "    {[entity = \"RV_trafero_semantic_canonical_tsc_scorecard_departments\", version = \"\"]}",
                "    [Data],",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    RV_trafero_semantic_canonical_tsc_scorecard_departments_,",
                "    {",
                "      {\"EmployeeOrgDesc\", \"Employee Org Description\"},",
                "      {\"Mapping\", \"Employee Department\"},",
                "      {\"EmployeeOrg\", \"DepartmentID\"}",
                "    }",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DynamicLegendAgentMetricsbyDay",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cb85f91d4b874015bfb62788158dd287"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "69b7d1dc-29a8-4fbf-a480-5989b890f2e4",
            "sourceColumn": "dl_aht_01_primaryproductgroup[CategoryValue]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "915d5a33-176c-4c4f-9e91-97080be1380e",
            "sourceColumn": "dl_aht_01_primaryproductgroup[CategoryValueIndex]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c6994633-be0a-466d-b57e-36719ac17497",
            "sortByColumn": "Sort",
            "sourceColumn": "dl_aht_01_primaryproductgroup[Field]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "69e7a33b-07c5-4be5-b97e-5591709987a0",
            "sourceColumn": "dl_aht_01_primaryproductgroup[Sort]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "7c818529-e420-4e07-b48d-8f1280a9d0f7",
        "partitions": [
          {
            "name": "DynamicLegendAgentMetricsbyDay-d6c9d1c9-d984-4e1e-9b24-51d7c1cd9d1c",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "UNION (",
                "    dl_aht_01_primaryproductgroup,",
                "    dl_aht_02_primaryproduct,",
                "    dl_calls_03_mgr1,",
                "    dl_calls_04_agent",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DynamicLegendCallStats",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e18a21accf4647c7ac6de1b5045d6c84"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "66e5df51-131a-44eb-91dc-b9bc4341a84f",
            "sourceColumn": "dl_calls_00_queuename[CategoryValue]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bc70b0d3-fc98-4712-894a-50cad47084f6",
            "sourceColumn": "dl_calls_00_queuename[CategoryValueIndex]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bbcf5c0c-3d0b-4541-a36a-aef6644316fc",
            "sortByColumn": "Sort",
            "sourceColumn": "dl_calls_00_queuename[Field]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3c8acb59-c042-431d-920c-e856de4c18ec",
            "sourceColumn": "dl_calls_00_queuename[Sort]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "805a7495-5ca8-4efa-9a58-60770c741d8d",
        "partitions": [
          {
            "name": "DynamicLegendCallStats-289eba86-c42a-46d9-a381-de1b055c8601",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "UNION ( dl_calls_00_queuename, dl_calls_01_productcategory, dl_calls_02_skill )",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DynamicLegendCalls",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cc8c4bdd3c0a4d03b917a780840a4b10"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cdeef37c-57b0-4cfd-bd45-13a40d6fc926",
            "sourceColumn": "dl_calls_00_queuename[CategoryValue]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ab2f4904-75aa-47ba-8ed9-c53346a9192d",
            "sourceColumn": "dl_calls_00_queuename[CategoryValueIndex]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9c6f1723-292a-40cd-8154-11bf08ba6788",
            "sortByColumn": "Sort",
            "sourceColumn": "dl_calls_00_queuename[Field]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "87b4ea46-0fbd-4c85-b46a-8cbfae6a7164",
            "sourceColumn": "dl_calls_00_queuename[Sort]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "fb875d53-f8fd-4cdd-b832-fe93b44c0245",
        "partitions": [
          {
            "name": "DynamicLegendCalls-8b7805bb-1c05-43ec-807a-52f3d6901730",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "UNION (",
                "    dl_calls_00_queuename,",
                "    dl_calls_01_productcategory,",
                "    dl_calls_02_skill,",
                "    dl_calls_03_mgr1,",
                "    dl_calls_04_agent",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DynamicLegendCases",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "66521e65fae346ebb196848f6c545c2f"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4a7fdefd-4a9b-4d9a-8fbd-7ec13c32720b",
            "sourceColumn": "dl_cases_01_productcategory[CategoryValue]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "875a0685-11f2-4455-aed6-8bc49eebfcbf",
            "sourceColumn": "dl_cases_01_productcategory[CategoryValueIndex]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e3b5d38e-4f52-43d6-b8bb-53259ce2766f",
            "sortByColumn": "Sort",
            "sourceColumn": "dl_cases_01_productcategory[Field]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6d1f610d-34d8-4b1f-a4c8-05086d319345",
            "sourceColumn": "dl_cases_01_productcategory[Sort]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "3755bbda-7a10-4617-bc53-098ebac92147",
        "partitions": [
          {
            "name": "DynamicLegendCases-be7b3551-73b9-4658-9284-c261e5a27e45",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "UNION (",
                "    dl_cases_01_productcategory,",
                "    dl_cases_02_category,",
                "    dl_cases_03_priority,",
                "    dl_cases_04_community,",
                "    'dl_cases_05_phl4',",
                "    'dl_cases_06_phl5',",
                "    DISTINCT ( 'dl_cases_07_mgr1' ),",
                "    DISTINCT ( 'dl_cases_08_agent' )",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DynamicLegendCommunityCases",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a106a542e4bb42f089a9fa68f83bdbaf"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2687308f-28bb-4f76-af3f-6e203d01611a",
            "sourceColumn": "dl_cases_01_productcategory[CategoryValue]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3757adb7-54b7-4dad-90ea-5dc93e298ca0",
            "sourceColumn": "dl_cases_01_productcategory[CategoryValueIndex]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e1d29f20-440c-4228-bc00-ec65e4e809a2",
            "sourceColumn": "dl_cases_01_productcategory[Field]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3f5ce4b1-095b-4e25-a5f7-b5c827012174",
            "sourceColumn": "dl_cases_01_productcategory[Sort]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "ad35c845-455b-4972-9aae-ccd94e4a5ca5",
        "partitions": [
          {
            "name": "DynamicLegendCommunityCases-01098630-6dcf-4c0e-a049-6673b7a27c63",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "UNION ( dl_cases_01_productcategory, dl_cases_03_priority )",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Employee",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Agent (EmployeeID)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f4527a4-30af-4f24-850d-9866ecb3d64b",
            "sourceColumn": "Agent (EmployeeID)",
            "summarizeBy": "none"
          },
          {
            "name": "Business Site Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b1a98c63-9d8d-48a0-b98c-8b6cdc7d73d1",
            "sourceColumn": "Business Site Name",
            "summarizeBy": "none"
          },
          {
            "name": "Display Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3db4db61-af70-423a-9446-93e74cee8824",
            "sourceColumn": "Display Name",
            "summarizeBy": "none"
          },
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isKey": true,
            "lineageTag": "2ae4c418-a6d0-4ff0-9c4a-4e15127953db",
            "sourceColumn": "Employee ID",
            "summarizeBy": "none"
          },
          {
            "name": "Employee Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4f5bc3b-0c14-459e-bd10-9e748a81a07c",
            "sourceColumn": "Employee Status",
            "summarizeBy": "none"
          },
          {
            "name": "EmployeeIdLatest",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb4a801a-e60f-4d1d-833e-35f6f22ddd29",
            "sourceColumn": "EmployeeIdLatest",
            "summarizeBy": "none"
          },
          {
            "name": "Manager Level 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5bf0e84e-0ae0-4dbb-8bcf-aecb37ed5de1",
            "sourceColumn": "Manager Level 1",
            "summarizeBy": "none"
          },
          {
            "name": "Manager Level 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "058e4604-4e8b-494c-8e01-6ca4efa9733d",
            "sourceColumn": "Manager Level 2",
            "summarizeBy": "none"
          },
          {
            "name": "Manager Level 3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f943b9f5-4f03-4317-990f-40b2fa02a792",
            "sourceColumn": "Manager Level 3",
            "summarizeBy": "none"
          },
          {
            "name": "Manager Level 4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "490764e9-788a-4af5-a939-85fddf70494a",
            "sourceColumn": "Manager Level 4",
            "summarizeBy": "none"
          },
          {
            "name": "Mgr1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "308f210a-0840-4f3e-9a4d-308e22493687",
            "sourceColumn": "Mgr1",
            "summarizeBy": "none"
          },
          {
            "name": "Org Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "26b94b05-08f3-48ee-b66c-b07c86594cbf",
            "sourceColumn": "Org Unit",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "796505ba-13bd-4a2c-ad07-ac953a66e32b",
        "partitions": [
          {
            "name": "Employee-7bc4120a-50df-4867-8ccf-1166af5e1905",
            "mode": "import",
            "queryGroup": "Dim\\Common",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"e2f343bf-d0c3-4299-b5aa-06f19929669c\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"e2f343bf-d0c3-4299-b5aa-06f19929669c\"]}",
                "    [Data],",
                "  Employee_ = #\"e2f343bf-d0c3-4299-b5aa-06f19929669c\"{[entity = \"Employee\", version = \"\"]}[Data],",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    Employee_,",
                "    {",
                "      {\"BusinessSiteName\", \"Business Site Name\"},",
                "      {\"EmployeeID\", \"Employee ID\"},",
                "      {\"EmployeeStatus\", \"Employee Status\"},",
                "      {\"ManagerFullNameLevel1\", \"Manager Level 1\"},",
                "      {\"ManagerFullNameLevel2\", \"Manager Level 2\"},",
                "      {\"ManagerFullNameLevel3\", \"Manager Level 3\"},",
                "      {\"ManagerFullNameLevel4\", \"Manager Level 4\"},",
                "      {\"OrgUnit\", \"Org Unit\"},",
                "      {\"DisplayName\", \"Display Name\"}",
                "    }",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Employee Site",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "BusinessSiteName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf7b244e-d79a-40c5-9b99-a4d2e01bfd9f",
            "sourceColumn": "BusinessSiteName",
            "summarizeBy": "none"
          },
          {
            "name": "Employee Site",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee155520-8cb7-4545-8d8a-27bb3e6f52c0",
            "sourceColumn": "Employee Site",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "24ee7913-0b3a-441e-b872-10e8abed61f3",
        "partitions": [
          {
            "name": "Employee Site-04c9d72b-bd5d-4fc7-aedf-2c11564f77c3",
            "mode": "import",
            "queryGroup": "Dim\\Common",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"e2f343bf-d0c3-4299-b5aa-06f19929669c\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"e2f343bf-d0c3-4299-b5aa-06f19929669c\"]}",
                "    [Data],",
                "  #\"Employee Site_\" = #\"e2f343bf-d0c3-4299-b5aa-06f19929669c\"",
                "    {[entity = \"Employee Site\", version = \"\"]}",
                "    [Data],",
                "  #\"Renamed Columns\" = Table.RenameColumns(#\"Employee Site_\", {{\"Mapping\", \"Employee Site\"}})",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Handle Type",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "HandleType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "49cf4a0a-350d-4c6e-ac06-a5cb76a5f550",
            "sourceColumn": "HandleType",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ac46f399-b5f4-48d5-9dbc-bbda6c525c0c",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "56808302-b90c-4b12-9b78-43e9ffaa081c",
        "partitions": [
          {
            "name": "Handle Type-2c0f1766-3f1f-4bae-aaa2-424a18c7e97c",
            "mode": "import",
            "queryGroup": "Dim\\Calls",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"dbff21c5-20d0-47bb-9a3a-d006032e86f3\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"dbff21c5-20d0-47bb-9a3a-d006032e86f3\"]}",
                "    [Data],",
                "  RV_trafero_semantic_canonical_tsc_handletype_ = #\"dbff21c5-20d0-47bb-9a3a-d006032e86f3\"",
                "    {[entity = \"RV_trafero_semantic_canonical_tsc_handletype\", version = \"\"]}",
                "    [Data]",
                "in",
                "  RV_trafero_semantic_canonical_tsc_handletype_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "IBase",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Destroyed Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "6ca155ce-d7f8-4668-b9a0-eb17777a7075",
            "sourceColumn": "Destroyed Date",
            "summarizeBy": "none"
          },
          {
            "name": "IObject ID No Leading Zeros",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a263617-0023-4854-873e-70404cc564a2",
            "sourceColumn": "IObject ID No Leading Zeros",
            "summarizeBy": "none"
          },
          {
            "name": "In Transit Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a42c76e0-555a-4ff6-ad13-229f35330c48",
            "sourceColumn": "In Transit Date",
            "summarizeBy": "none"
          },
          {
            "name": "Iobject Id No Leading Zero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6fec4ad-eab8-4733-a211-26d7f42771ed",
            "sourceColumn": "Iobject Id No Leading Zero",
            "summarizeBy": "none"
          },
          {
            "name": "Live Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "74e5172d-1cda-4691-a1b0-ee26a0a58bce",
            "sourceColumn": "Live Date",
            "summarizeBy": "none"
          },
          {
            "name": "Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d129ded1-6a04-4c74-9c9b-087fffef65f2",
            "sourceColumn": "Location",
            "summarizeBy": "none"
          },
          {
            "name": "Pending Return Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "7d41e0ea-e728-48df-8af4-3cdfec4f0ad9",
            "sourceColumn": "Pending Return Date",
            "summarizeBy": "none"
          },
          {
            "name": "Reference Product No Leading Zero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b0776af-74a5-4b23-b763-5a84b62cd136",
            "sourceColumn": "Reference Product No Leading Zero",
            "summarizeBy": "none"
          },
          {
            "name": "Serial Number No Leading Zero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6be5ac90-4a32-41c3-9678-a02e1043c183",
            "sourceColumn": "Serial Number No Leading Zero",
            "summarizeBy": "none"
          },
          {
            "name": "Ship To Customer Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cacf840e-f349-4ce9-ad1a-687311b07d6f",
            "sourceColumn": "Ship To Customer Id",
            "summarizeBy": "none"
          },
          {
            "name": "Software Versions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1f23220-cccf-4f98-b207-8ad8d1af5963",
            "sourceColumn": "Software Versions",
            "summarizeBy": "none"
          },
          {
            "name": "Sold To Customer Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b04e84d-d026-4273-a9b4-62c473845fbb",
            "sourceColumn": "Sold To Customer Id",
            "summarizeBy": "none"
          },
          {
            "name": "User Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e4547cd-2e76-4099-85b5-5cb49e8fc24f",
            "sourceColumn": "User Status",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f31427e1-9b9b-47f3-a8a8-7c87957a1d32",
        "partitions": [
          {
            "name": "IBase-9afa2de7-cb84-4dff-9c3c-6795f232453d",
            "mode": "import",
            "queryGroup": "Dim\\Cases",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"79e504d4-45fb-4224-a774-b1871c6fdb1b\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"79e504d4-45fb-4224-a774-b1871c6fdb1b\"]}",
                "    [Data],",
                "  IObject_ = #\"79e504d4-45fb-4224-a774-b1871c6fdb1b\"{[entity = \"IObject\", version = \"\"]}[Data],",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    IObject_,",
                "    {{\"IObjectIdNoLeadingZeros\", \"IObject ID No Leading Zeros\"}}",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Interaction Type",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "97140887-d909-4b0e-911e-6fb175c537e0",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          },
          {
            "name": "InteractionType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8956cf9d-e16e-4f0e-9903-b954a487e6e0",
            "sourceColumn": "InteractionType",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "86714178-f5c3-4d60-bc04-44868591fb3b",
        "partitions": [
          {
            "name": "Interaction Type-011dfed3-c58b-4beb-bbc8-0afd68fac9ff",
            "mode": "import",
            "queryGroup": "Dim\\Calls",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces{[workspaceId=\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}[Data],",
                "    #\"a85e91e0-0866-440d-9074-7ff1a5d7029d\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"{[dataflowId=\"a85e91e0-0866-440d-9074-7ff1a5d7029d\"]}[Data],",
                "    RV_trafero_semantic_canonical_tsc_interactiontype_ = #\"a85e91e0-0866-440d-9074-7ff1a5d7029d\"{[entity=\"RV_trafero_semantic_canonical_tsc_interactiontype\",version=\"\"]}[Data]",
                "in",
                "    RV_trafero_semantic_canonical_tsc_interactiontype_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI AMBD Dynamic Legent",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "isHidden": true,
        "lineageTag": "314dcf47-642a-4abc-a38e-a4db523be7c7",
        "measures": [
          {
            "name": "ACW Avg (DL)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Primary Product Group\",",
              "        CALCULATE (",
              "            [ACW Avg],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[PPG] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Primary Product\",",
              "        CALCULATE (",
              "            [ACW Avg],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[PP] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [ACW Avg],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[Mngr Level 1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [ACW Avg],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[Agent] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "isHidden": true,
            "lineageTag": "3fbf968a-c7b6-49b4-8a94-27eb4d9d98ae"
          },
          {
            "name": "Call Handle Time Avg (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Primary Product Group\",",
              "        CALCULATE (",
              "            [Call Handle Time],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[PPG] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Primary Product\",",
              "        CALCULATE (",
              "            [Call Handle Time],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[PP] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [Call Handle Time],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[Mngr Level 1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [Call Handle Time],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[Agent] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "lineageTag": "7e23055b-dc5c-4340-a791-989c60361499"
          },
          {
            "name": "Calls and Cases Rate (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Primary Product Group\",",
              "        CALCULATE (",
              "            [Call and Case Rate],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[PPG] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Primary Product\",",
              "        CALCULATE (",
              "            [Call and Case Rate],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[PP] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [Call and Case Rate],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[Mngr Level 1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [Call and Case Rate],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[Agent] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "lineageTag": "39d52bab-d4f7-4df4-b00a-71b1c104f42d"
          },
          {
            "name": "Case Work Time (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Primary Product Group\",",
              "        CALCULATE (",
              "            [Case Work Time w/o Escalation & Inbound Case Work],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[PPG] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Primary Product\",",
              "        CALCULATE (",
              "            [Case Work Time w/o Escalation & Inbound Case Work],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[PP] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [Case Work Time w/o Escalation & Inbound Case Work],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[Mngr Level 1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [Case Work Time w/o Escalation & Inbound Case Work],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[Agent] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "lineageTag": "05c2c3cc-a83b-4a67-8778-889acf013104"
          },
          {
            "name": "CWT + Escalation & Inbound (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Primary Product Group\",",
              "        CALCULATE (",
              "            [Case Work Time with Escalation & Inbound Case Work],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[PPG] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Primary Product\",",
              "        CALCULATE (",
              "            [Case Work Time with Escalation & Inbound Case Work],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[PP] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [Case Work Time with Escalation & Inbound Case Work],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[Mngr Level 1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [Case Work Time with Escalation & Inbound Case Work],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[Agent] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "lineageTag": "ed6598ed-c210-4c88-b5b3-7cb8401cb541"
          },
          {
            "name": "Talk Time Avg (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Primary Product Group\",",
              "        CALCULATE (",
              "            [Talk Time Avg],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[PPG] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Primary Product\",",
              "        CALCULATE (",
              "            [Talk Time Avg],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[PP] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [Talk Time Avg],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[Mngr Level 1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendAgentMetricsbyDay[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [Talk Time Avg],",
              "            USERELATIONSHIP ( 'DynamicLegendAgentMetricsbyDay'[CategoryValueIndex], 'Agent Metrics by Day'[Agent] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "lineageTag": "7d3e632d-9a97-48db-a8d0-28b51a731b34"
          }
        ],
        "partitions": [
          {
            "name": "KPI AMBD Dynamic Legent-d43df5ea-3eb1-425e-9091-4f344251c96d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "  Source = Table.FromRows(",
                "    Json.Document(",
                "      Binary.Decompress(Binary.FromText(\"i45WMlSKjQUA\", BinaryEncoding.Base64), Compression.Deflate)",
                "    ),",
                "    let",
                "      _t = ((type nullable text) meta [Serialized.Text = true])",
                "    in",
                "      type table [Column1 = _t]",
                "  ),",
                "  #\"Changed Type\" = Table.TransformColumnTypes(Source, {{\"Column1\", Int64.Type}}),",
                "  #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\", {\"Column1\"})",
                "in",
                "  #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI AMBD Dynamic Measures Cnt",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "DM Cnt Selection AMBD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b96bab4c-25a6-4818-8beb-f5af4810af31",
            "sortByColumn": "Sort",
            "sourceColumn": "DM Cnt Selection AMBD",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5ecdcc12-eaea-495a-865c-09eef2d19aa1",
            "sourceColumn": "Sort",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "f49cb9a5-523f-4c73-8b06-93dc75a7964d",
        "measures": [
          {
            "name": "Dynamic Measures Cnt AHT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR selection =",
              "    SELECTEDVALUE ( 'KPI AMBD Dynamic Measures Cnt'[DM Cnt Selection AMBD] )",
              "RETURN",
              "    SWITCH (",
              "        selection,",
              "        \"Call Handle Time Avg\", [Call Handle Time Avg (DL)],",
              "        \"ACW Avg\", [ACW Avg (DL)],",
              "        \"Talk Time Avg\", [Talk Time Avg (DL)],",
              "        \"Case Work Time\", [Case Work Time (DL)],",
              "        \"CWT + Escalation & Inbound\", [CWT + Escalation & Inbound (DL)],",
              "        BLANK ()",
              "    )",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "f4dde5ef-c4d6-4415-9552-cd288e098f31"
          }
        ],
        "partitions": [
          {
            "name": "KPI AMBD Dynamic Measures Cnt-f51acc24-4ebc-4edb-8a7b-c9e4b279f291",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "  Source = Table.FromRows(",
                "    Json.Document(",
                "      Binary.Decompress(",
                "        Binary.FromText(",
                "          \"TYq5CoAwDEB/JWTVwXuXIuhe6FA7RC0ixha8vl9RB8d3aI2CmKEmN7AFOS0WynPEEGM0ocZSqI+ThyXx/L/SxwraLCi/vunW2auVhACqrSemffIO2iOKkgIa1/nDDfeXozEX\",",
                "          BinaryEncoding.Base64",
                "        ),",
                "        Compression.Deflate",
                "      )",
                "    ),",
                "    let",
                "      _t = ((type nullable text) meta [Serialized.Text = true])",
                "    in",
                "      type table [#\"DM Cnt Selection AMBD\" = _t, Sort = _t]",
                "  ),",
                "  #\"Changed Type\" = Table.TransformColumnTypes(",
                "    Source,",
                "    {{\"DM Cnt Selection AMBD\", type text}, {\"Sort\", Int64.Type}}",
                "  )",
                "in",
                "  #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI Agent Metics by Day",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "9887d012-12f7-4714-ad9f-dec2a9a990a0",
        "measures": [
          {
            "name": "Calls Inbound",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUM ( 'Agent Metrics by Day'[Call Inbound Talk] )",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "a618aadd-9e59-4167-b98c-aee9856f4536"
          },
          {
            "name": "Calls Internal",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUM ( 'Agent Metrics by Day'[Call Internal Talk] )",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "3d07ee3f-e825-4101-8a35-161525270390"
          },
          {
            "name": "Talk Time Avg",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE (",
              "    [Calls Inbound] + [Calls Internal],",
              "    [Calls Answered per Agent and Day],",
              "    0",
              ") / 60",
              ""
            ],
            "lineageTag": "28783129-fe99-47a7-9af1-dd0a1f431754"
          },
          {
            "name": "Calls Answered per Agent and Day",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUM ( 'Agent Metrics by Day'[Calls Answered] )",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "76c41495-b448-44cf-b19a-dd071c347854"
          },
          {
            "name": "ACW Time",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUM ( 'Agent Metrics by Day'[ACW Time] )",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "6f724ce2-fd73-4649-936f-d7ebd1421a3b"
          },
          {
            "name": "Calls Dialing",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUM ( 'Agent Metrics by Day'[Call Dialing] )",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "cff52411-e36e-4ea8-b0bf-d79d2e2198b7"
          },
          {
            "name": "Calls Ringing",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUM ( 'Agent Metrics by Day'[Call Ringing] )",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "9dcf809e-32da-4f8e-ae7b-f254b5c37a0b"
          },
          {
            "name": "Calls OnHold",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUM ( 'Agent Metrics by Day'[Call On Hold] )",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "d5c0f1a6-7cc5-4452-889a-6e1a3a28466c"
          },
          {
            "name": "Calls Consult",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUM ( 'Agent Metrics by Day'[Call Consult] )",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "5f16a515-5a53-4316-98c2-449e48690b6d"
          },
          {
            "name": "Case Handle Time",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "DIVIDE ( [Case Work Time], [Non Dispatched Completed Cases] ) / 60",
              ""
            ],
            "formatString": "0",
            "lineageTag": "5a60d581-d809-4878-8e84-6b8a88c419fd"
          },
          {
            "name": "Case Work Time",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUM ( 'Agent Metrics by Day'[CaseWorkTime] )",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "8ce30ea2-1694-4774-9187-5c2c9dbea59d"
          },
          {
            "name": "Aux Case Escalation",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUM ( 'Agent Metrics by Day'[AUX Case Escalation Duration] )",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "64c0b278-660a-4ce4-87b8-7380c7c10887"
          },
          {
            "name": "Aux Inbound Case Work",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUM ( 'Agent Metrics by Day'[AUX Inbound Case Work Duration] )",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "94cf4d2e-fd3a-41cd-9fe1-72fe62bbd1cd"
          },
          {
            "name": "Non Dispatched Completed Cases",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUM ( 'Agent Metrics by Day'[Cases Closed Non Dispatched] )",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "2ef4a4f1-ebf5-40ba-8368-f1985e9f9370"
          },
          {
            "name": "Call Handle Time",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "DIVIDE (",
              "    [Calls Dialing] + [Calls Ringing] + [Calls OnHold] + [Calls Inbound] + [Calls Internal] + [Calls Consult] + [ACW Time],",
              "    [Calls Answered per Agent and Day]",
              ") / 60",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "2d1ee16f-5ecb-4f8c-88a2-995cd9a66b1c"
          },
          {
            "name": "ACW Avg",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE ( [ACW Time], [Calls Answered per Agent and Day] ) / 60",
              ""
            ],
            "lineageTag": "f5db7715-847d-4695-805e-3e515ef0d8d4"
          },
          {
            "name": "Call and Case Rate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE ( [Calls and Case Rate Numerator], [Calls and Case Rate Denominator] )",
              ""
            ],
            "lineageTag": "ea40a01e-69f8-4aaa-8c4a-a5ce32b43b5c"
          },
          {
            "name": "PCP Time",
            "expression": [
              "",
              "SUM ( 'Agent Metrics by Day'[PCP Time] )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "43a75088-2485-4131-9bc1-1792aa325424"
          },
          {
            "name": "Personal Time",
            "expression": [
              "",
              "SUM ( 'Agent Metrics by Day'[Personal Time] )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "dcbf808d-1df3-43ea-a0e1-b143c1c45d3a"
          },
          {
            "name": "Talk Time Inbound Personal",
            "expression": [
              "",
              "SUM ( 'Agent Metrics by Day'[Call Inbound Talk] )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "72f89753-ee09-485d-aef5-f985f0eea3e1"
          },
          {
            "name": "Calls and Case Rate Denominator",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "( ( [PCP Time] + [Personal Time] + [Talk Time Inbound Personal] + [ACW Time] + [Calls Dialing] + [Calls Ringing] + [Calls Inbound] + [Calls Internal] + [Calls OnHold] + [Calls Consult] + [Aux Case Escalation] + [Aux Inbound Case Work] ) / 60 ) / 60",
              ""
            ],
            "lineageTag": "4a5a64eb-5e16-4c87-b837-8d6f1deb50c7"
          },
          {
            "name": "Calls and Case Rate Numerator",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[Calls Answered per Agent and Day] + [Cases Closed per Agent and Day]",
              ""
            ],
            "lineageTag": "2cfbf760-fba3-4bb9-b4ac-a09535647863"
          },
          {
            "name": "Cases Closed per Agent and Day",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUM ( 'Agent Metrics by Day'[Cases Closed] )",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "98c082db-bde5-4635-8312-b75671b14e17"
          },
          {
            "name": "Case Work Time with Escalation & Inbound Case Work",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE (",
              "    [Case Work Time] + [Aux Case Escalation] + [Aux Inbound Case Work],",
              "    [Non Dispatched Completed Cases]",
              ") / 60",
              ""
            ],
            "lineageTag": "4836db63-cf6b-4abb-9889-406822d4e1ca"
          },
          {
            "name": "Case Work Time w/o Escalation & Inbound Case Work",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE ( [Case Work Time], [Non Dispatched Completed Cases] ) / 60",
              ""
            ],
            "lineageTag": "7b7a265b-e28b-4521-b6fe-7fb9931a3577"
          },
          {
            "name": "Agent Metics by Day (max)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "MAX ( 'Agent Metrics by Day'[Date] )",
              ""
            ],
            "formatString": "Short Date",
            "lineageTag": "8e28f6d3-ec7d-4385-88cb-d4cd35e1fd3b"
          }
        ],
        "partitions": [
          {
            "name": "KPI Agent Metics by Day-8e035f5e-5f58-4d3b-9255-523db86d0e62",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "  Source = Table.FromRows(",
                "    Json.Document(",
                "      Binary.Decompress(Binary.FromText(\"i45WMlSKjQUA\", BinaryEncoding.Base64), Compression.Deflate)",
                "    ),",
                "    let",
                "      _t = ((type nullable text) meta [Serialized.Text = true])",
                "    in",
                "      type table [Column1 = _t]",
                "  ),",
                "  #\"Changed Type\" = Table.TransformColumnTypes(Source, {{\"Column1\", Int64.Type}}),",
                "  #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\", {\"Column1\"})",
                "in",
                "  #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI Calls",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "cce6ba1d-adec-40de-89eb-8de566ef38e2",
        "measures": [
          {
            "name": "< 15 Mins",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUMX (",
              "    FILTER ( Calls, RELATED ( 'Interaction Type'[InteractionType] ) = \"Inbound\" ),",
              "    Calls[Calls Answered In 15 Minutes]",
              ")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "9bca3c6b-030a-4677-916a-5c20c699f042"
          },
          {
            "name": "< 15 Mins %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "DIVIDE ( 'KPI Calls'[< 15 Mins], 'KPI Calls'[Calls Offered] )",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "2d238bc7-a812-4b2d-bee0-cafcad988803"
          },
          {
            "name": "Calls Offered",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUMX (",
              "    FILTER ( Calls, RELATED ( 'Interaction Type'[InteractionType] ) = \"Inbound\" ),",
              "    Calls[Calls Abandoned]",
              ")",
              "    + SUMX (",
              "        FILTER ( Calls, RELATED ( 'Interaction Type'[InteractionType] ) = \"Inbound\" ),",
              "        Calls[Calls Handled]",
              "    )",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "a0f53f25-a789-4038-8ea1-33f5182d3e7e"
          },
          {
            "name": "Calls Handled",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUMX (",
              "    FILTER ( Calls, RELATED ( 'Interaction Type'[InteractionType] ) = \"Inbound\" ),",
              "    Calls[Calls Handled]",
              ")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "080af7e9-8299-4090-a297-4a1c77b9bb87"
          },
          {
            "name": "Calls Abandoned",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUMX (",
              "    FILTER ( Calls, RELATED ( 'Interaction Type'[InteractionType] ) = \"Inbound\" ),",
              "    Calls[Calls Abandoned]",
              ")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "0e534a89-e29b-434b-a584-eb916e9e6df0"
          },
          {
            "name": "< 3 Mins",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUMX (",
              "    FILTER ( Calls, RELATED ( 'Interaction Type'[InteractionType] ) = \"Inbound\" ),",
              "    Calls[Calls Answered In 3 Minutes]",
              ")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "b89b82ed-f5ef-4816-97df-0a3fa50583ed"
          },
          {
            "name": "< 3 Mins %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "DIVIDE ( 'KPI Calls'[< 3 Mins], 'KPI Calls'[Calls Offered] )",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "0e587247-eb3f-439f-b625-5e9e3ab30c16"
          },
          {
            "name": "< 5 Mins",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUMX (",
              "    FILTER ( Calls, RELATED ( 'Interaction Type'[InteractionType] ) = \"Inbound\" ),",
              "    Calls[Calls Answered In 5 Minutes]",
              ")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "d3643645-1e84-4024-ae2e-c269960c766b"
          },
          {
            "name": "< 5 Mins %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "DIVIDE ( 'KPI Calls'[< 5 Mins], 'KPI Calls'[Calls Offered] )",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "460afd31-5e0c-455d-9178-3a7ea43992e2"
          },
          {
            "name": "Avg Speed of Answer Decimal",
            "expression": [
              "",
              "    ROUNDUP( CALCULATE (",
              "        AVERAGEX ( Calls, [Wait Duration] ),",
              "        Calls[Answered Flag] = \"Y\",",
              "        'Interaction Type'[InteractionType] = \"Inbound\"",
              "    ),0)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "270e7b56-33f9-4e56-9239-237e448db786"
          },
          {
            "name": "Avg Speed of Answer Std Dev Decimal",
            "expression": [
              "",
              "    ROUNDUP( CALCULATE (",
              "        STDEV.P ( Calls[Wait Duration] ),",
              "        Calls[Answered Flag] = \"Y\",",
              "        'Interaction Type'[InteractionType] = \"Inbound\"",
              "    ),0)"
            ],
            "formatString": "0",
            "lineageTag": "5bbb02ca-fc74-444b-a1dc-7d1b1c1ad05b"
          },
          {
            "name": "Call Date (max)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "MAX ( Calls[Call Date] )",
              ""
            ],
            "formatString": "Short Date",
            "lineageTag": "6416d811-661e-4f45-9361-9a9769c2f629"
          },
          {
            "name": "Call Date (min)",
            "expression": [
              "",
              "MIN ( Calls[Call Date] )",
              ""
            ],
            "formatString": "General Date",
            "lineageTag": "78421bf1-2802-4ea9-b2c0-5fdf6b491f19"
          },
          {
            "name": "Calls Answered",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUMX (",
              "    FILTER ( Calls, RELATED ( 'Interaction Type'[InteractionType] ) = \"Inbound\" ),",
              "    Calls[Calls Answered]",
              ")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "c12ea020-ad86-4c03-8c2a-9f3c6330ca99"
          },
          {
            "name": "Connect Rate %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "DIVIDE ( 'KPI Calls'[Calls Answered], 'KPI Calls'[Calls Offered] )",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "f5888173-894f-4e5e-bf52-274dd5c8dcd6"
          },
          {
            "name": "RONA % (Call Detail)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "DIVIDE ( 'KPI Calls'[Rona Calls], 'KPI Calls'[Calls Offered] )",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "666035d8-adc4-467e-bfe0-1136d79c4937"
          },
          {
            "name": "RONA % (Overall Call )",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "DIVIDE (",
              "    ( 'KPI Calls'[Rona Calls] + 'KPI Calls'[Rona Case] ),",
              "    'KPI Calls'[Calls Offered]",
              ")",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "74843738-c80b-4ebe-baec-dd2ba48eaf39"
          },
          {
            "name": "Rona Calls",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUMX (",
              "    FILTER ( Calls, RELATED ( 'Interaction Type'[InteractionType] ) = \"Inbound\" ),",
              "    Calls[Call Rona]",
              ")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "c40dcb6d-32c9-415a-873b-2038ee384220"
          },
          {
            "name": "Target % < 15 Mins",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              ".98",
              ""
            ],
            "lineageTag": "788750fe-3447-4a6a-8946-c03e377998f5"
          },
          {
            "name": "Target % < 3 Mins",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              ".7",
              ""
            ],
            "lineageTag": "7b0b1838-0eba-4cf5-9693-faedd1833206"
          },
          {
            "name": "Target % < 5 Mins",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              ".9",
              ""
            ],
            "lineageTag": "c14b5ded-81eb-45f7-8127-02a6e5a369d1"
          },
          {
            "name": "Wait Duration",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUMX (",
              "    FILTER ( Calls, RELATED ( 'Interaction Type'[InteractionType] ) = \"Inbound\" ),",
              "    Calls[Wait Duration]",
              ") / 60",
              ""
            ],
            "lineageTag": "b69e0f77-ed7e-4e10-8fb9-2414230f4327"
          },
          {
            "name": "Wait Duration Max",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "MAXX (",
              "    FILTER ( Calls, RELATED ( 'Interaction Type'[InteractionType] ) = \"Inbound\" ),",
              "    Calls[Wait Duration]",
              ") / 60",
              ""
            ],
            "formatString": "0",
            "lineageTag": "47056b2d-2a6d-4255-8519-6457d602197e"
          },
          {
            "name": "Wait Duration Mean",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "AVERAGEX (",
              "    FILTER ( Calls, RELATED ( 'Interaction Type'[InteractionType] ) = \"Inbound\" ),",
              "    Calls[Wait Duration] / 60",
              ")",
              ""
            ],
            "isHidden": true,
            "lineageTag": "12d093cb-0a8e-425d-b138-565e272b6511"
          },
          {
            "name": "Wait Duration Median",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "MEDIANX (",
              "    FILTER ( Calls, RELATED ( 'Interaction Type'[InteractionType] ) = \"Inbound\" ),",
              "    Calls[Wait Duration]",
              ") / 60",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "lineageTag": "55e670bf-0ab1-4561-a132-a280ddfa6da0"
          },
          {
            "name": "Wait Duration P25",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "PERCENTILEX.EXC (",
              "    FILTER ( Calls, RELATED ( 'Interaction Type'[InteractionType] ) = \"Inbound\" ),",
              "    Calls[Wait Duration],",
              "    0.25",
              ") / 60",
              ""
            ],
            "isHidden": true,
            "lineageTag": "b796dfe7-ec4c-46fd-a01b-d7cd6129724d"
          },
          {
            "name": "Wait Duration P75",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "PERCENTILEX.EXC (",
              "    FILTER ( Calls, RELATED ( 'Interaction Type'[InteractionType] ) = \"Inbound\" ),",
              "    Calls[Wait Duration],",
              "    0.75",
              ") / 60",
              ""
            ],
            "formatString": "0.00",
            "isHidden": true,
            "lineageTag": "b8a5a3ba-6755-447e-a319-0e38b7b36a53"
          },
          {
            "name": "Wait Duration P95",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "PERCENTILEX.EXC (",
              "    FILTER ( Calls, RELATED ( 'Interaction Type'[InteractionType] ) = \"Inbound\" ),",
              "    Calls[Wait Duration],",
              "    0.95",
              ") / 60",
              ""
            ],
            "formatString": "0.00",
            "isHidden": true,
            "lineageTag": "7bfbcff1-c849-4281-93d8-8e9622283c9a"
          },
          {
            "name": "Rona Case",
            "expression": [
              "",
              "SUMX (",
              "    FILTER ( Calls, RELATED ( 'Interaction Type'[InteractionType] ) = \"Inbound\" ),",
              "    Calls[Case Rona]",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "0a059183-5377-4258-8266-3e38bf555427"
          },
          {
            "name": "Wait Duration P25 Filtered",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATETABLE (",
              "    ROW ( \"Wait Duration P25\", [Wait Duration P25] ),",
              "    KEEPFILTERS ( TREATAS ( { \"Inbound\" }, 'Interaction Type'[InteractionType] ) ),",
              "    KEEPFILTERS (",
              "        FILTER ( ALL ( Calls[Wait Duration] ), Calls[Wait Duration] > 0 )",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "ac4fad28-0931-4c78-ade4-dd425b183b31"
          },
          {
            "name": "Wait Duration Mean Filtered",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATETABLE (",
              "    ROW ( \"Wait Duration Mean\", [Wait Duration Mean] ),",
              "    KEEPFILTERS ( TREATAS ( { \"Inbound\" }, 'Interaction Type'[InteractionType] ) ),",
              "    KEEPFILTERS (",
              "        FILTER ( ALL ( Calls[Wait Duration] ), Calls[Wait Duration] > 0 )",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "06511335-9ff6-4995-b365-826b6d2e02c3"
          },
          {
            "name": "Wait Duration P75 Filtered",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATETABLE (",
              "    ROW ( \"Wait Duration P75\", [Wait Duration P75] ),",
              "    KEEPFILTERS ( TREATAS ( { \"Inbound\" }, 'Interaction Type'[InteractionType] ) ),",
              "    KEEPFILTERS (",
              "        FILTER ( ALL ( Calls[Wait Duration] ), Calls[Wait Duration] > 0 )",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "15452b11-6e9d-4916-a04a-9e8124dae058"
          },
          {
            "name": "Wait Duration P95 Filtered",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATETABLE (",
              "    ROW ( \"Wait Duration P95\", [Wait Duration P95] ),",
              "    KEEPFILTERS ( TREATAS ( { \"Inbound\" }, 'Interaction Type'[InteractionType] ) ),",
              "    KEEPFILTERS (",
              "        FILTER ( ALL ( Calls[Wait Duration] ), Calls[Wait Duration] > 0 )",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "462783bb-c5cb-46ea-87b0-1da05cc77136"
          },
          {
            "name": "Wait Duration Median Filtered",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATETABLE (",
              "    ROW ( \"Wait Duration Median\", [Wait Duration Median] ),",
              "    KEEPFILTERS ( TREATAS ( { \"Inbound\" }, 'Interaction Type'[InteractionType] ) ),",
              "    KEEPFILTERS (",
              "        FILTER ( ALL ( Calls[Wait Duration] ), Calls[Wait Duration] > 0 )",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "3378aeb9-e9ba-446d-b44d-904564a46376"
          },
          {
            "name": "Wait Duration STDDEV",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "STDEVX.P ( Calls, [Wait Duration] ) / 60",
              ""
            ],
            "isHidden": true,
            "lineageTag": "9598104a-4ec8-4039-93f0-9acece068114"
          },
          {
            "name": "Wait Duration STDDEV Filtered",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATETABLE (",
              "    ROW ( \"Wait Duration STDEV\", [Wait Duration STDDEV] ),",
              "    KEEPFILTERS ( TREATAS ( { \"Inbound\" }, 'Interaction Type'[InteractionType] ) ),",
              "    KEEPFILTERS (",
              "        FILTER ( ALL ( Calls[Wait Duration] ), Calls[Wait Duration] > 0 )",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "7e70ac70-8893-43f7-852e-825bf6842a4b"
          },
          {
            "name": "Avg Speed of Answer Minutes",
            "expression": [
              "",
              "    QUOTIENT( [Avg Speed of Answer Decimal], 60)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "15211b03-fa84-4550-9b8a-b2ff06c42872"
          },
          {
            "name": "Avg Speed of Answer Seconds",
            "expression": [
              "",
              "    MOD( [Avg Speed of Answer Decimal],60)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "7546e1a2-62b2-4b67-b4a9-e081c36b5e43"
          },
          {
            "name": "Avg Speed of Answer",
            "expression": "FORMAT([Avg Speed of Answer Minutes], \"00\") & \":\" & FORMAT([Avg Speed of Answer Seconds], \"00\")",
            "lineageTag": "e9375670-e96a-46f7-b654-cd4cb4d1b78f"
          },
          {
            "name": "Avg Speed of Answer Std Dev Minutes",
            "expression": [
              "",
              "    QUOTIENT( [Avg Speed of Answer Std Dev Decimal], 60)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "83d9b1e5-38cc-4e66-99e4-aad8901fa9f4"
          },
          {
            "name": "Avg Speed of Answer Std Dev Seconds",
            "expression": [
              "",
              "    MOD( [Avg Speed of Answer Std Dev Decimal],60)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "cc63cc86-0dcd-45b5-9596-b50248cbc84a"
          },
          {
            "name": "Avg Speed of Answer Std Dev",
            "expression": "FORMAT([Avg Speed of Answer Std Dev Minutes], \"00\") & \":\" & FORMAT([Avg Speed of Answer Std Dev Seconds], \"00\")",
            "lineageTag": "985de47f-51bc-40c0-a0c9-8beb7a06c4cc"
          }
        ],
        "partitions": [
          {
            "name": "KPI Calls-5a2ba9c0-d974-43e5-b934-c603b3630b40",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "  Source = Table.FromRows(",
                "    Json.Document(",
                "      Binary.Decompress(Binary.FromText(\"i45WMlSKjQUA\", BinaryEncoding.Base64), Compression.Deflate)",
                "    ),",
                "    let",
                "      _t = ((type nullable text) meta [Serialized.Text = true])",
                "    in",
                "      type table [Column1 = _t]",
                "  ),",
                "  #\"Changed Type\" = Table.TransformColumnTypes(Source, {{\"Column1\", Int64.Type}}),",
                "  #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\", {\"Column1\"})",
                "in",
                "  #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI Calls Dynamic Legend",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "isHidden": true,
        "lineageTag": "d30fbf24-2e32-4bfe-afc7-7861e3b1724d",
        "measures": [
          {
            "name": "Calls Answered (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [Calls Answered],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Mgr1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [Calls Answered],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Agent] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Skill\",",
              "        CALCULATE (",
              "            [Calls Answered],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Skills] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [Calls Answered],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Product Category] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Queue\",",
              "        CALCULATE (",
              "            [Calls Answered],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[QueueNameIndex] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "lineageTag": "b7532ba6-808f-43dd-b95f-0a40d671ee89"
          },
          {
            "name": "< 15 Mins % (DL)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [< 15 Mins %],",
              "            USERELATIONSHIP ( DynamicLegendCalls[CategoryValueIndex], Calls[Mgr1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [< 15 Mins %],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Agent] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Skill\",",
              "        CALCULATE (",
              "            [< 15 Mins %],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Skills] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [< 15 Mins %],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Product Category] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Queue\",",
              "        CALCULATE (",
              "            [< 15 Mins %],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[QueueNameIndex] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "isHidden": true,
            "lineageTag": "6cef1fdd-b48d-4f94-b198-c69773e5395b"
          },
          {
            "name": "< 3 Mins % (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [< 3 Mins %],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Mgr1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [< 3 Mins %],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Agent] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Skill\",",
              "        CALCULATE (",
              "            [< 3 Mins %],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Skills] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [< 3 Mins %],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Product Category] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Queue\",",
              "        CALCULATE (",
              "            [< 3 Mins %],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[QueueNameIndex] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "isHidden": true,
            "lineageTag": "f0aee038-eac2-46d5-b0d7-21817ea77d0f"
          },
          {
            "name": "< 5 Mins % (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [< 5 Mins %],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Mgr1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [< 5 Mins %],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Agent] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Skill\",",
              "        CALCULATE (",
              "            [< 5 Mins %],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Skills] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [< 5 Mins %],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Product Category] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Queue\",",
              "        CALCULATE (",
              "            [< 5 Mins %],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[QueueNameIndex] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "isHidden": true,
            "lineageTag": "91423863-26a9-4150-bea1-bde915214e26"
          },
          {
            "name": "Connect Rate % (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [Connect Rate %],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Mgr1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [Connect Rate %],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Agent] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Skill\",",
              "        CALCULATE (",
              "            [Connect Rate %],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Skills] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [Connect Rate %],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Product Category] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Queue\",",
              "        CALCULATE (",
              "            [Connect Rate %],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[QueueNameIndex] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "isHidden": true,
            "lineageTag": "02f27329-ce3d-4a2a-8257-105a0e9cc5bc"
          },
          {
            "name": "Overall Call RONA % (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [RONA % (Overall Call )],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Mgr1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [RONA % (Overall Call )],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Agent] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Skill\",",
              "        CALCULATE (",
              "            [RONA % (Overall Call )],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Skills] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [RONA % (Overall Call )],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Product Category] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Queue\",",
              "        CALCULATE (",
              "            [RONA % (Overall Call )],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[QueueNameIndex] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "isHidden": true,
            "lineageTag": "3d0d75c4-f283-4983-842f-8682685a26ad"
          },
          {
            "name": "Calls Offered (DL)",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [Calls Offered],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Mgr1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [Calls Offered],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Agent] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Skill\",",
              "        CALCULATE (",
              "            [Calls Offered],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Skills] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [Calls Offered],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Product Category] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Queue\",",
              "        CALCULATE (",
              "            [Calls Offered],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[QueueNameIndex] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "84614ba7-77ca-4d27-b0a8-aa53cd551aad"
          },
          {
            "name": "Calls Handled (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [Calls Handled],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Mgr1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [Calls Handled],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Agent] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Skill\",",
              "        CALCULATE (",
              "            [Calls Handled],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Skills] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [Calls Handled],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[Product Category] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCalls[Field] ) = \"Queue\",",
              "        CALCULATE (",
              "            [Calls Handled],",
              "            USERELATIONSHIP ( 'DynamicLegendCalls'[CategoryValueIndex], Calls[QueueNameIndex] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d6e514ac-47c9-4208-b0f7-d0e818882093"
          }
        ],
        "partitions": [
          {
            "name": "KPI Calls Dynamic Legend-83cbdd1c-e211-4c5f-bd3d-cfa4d964a297",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "  Source = Table.FromRows(",
                "    Json.Document(",
                "      Binary.Decompress(Binary.FromText(\"i45WMlSKjQUA\", BinaryEncoding.Base64), Compression.Deflate)",
                "    ),",
                "    let",
                "      _t = ((type nullable text) meta [Serialized.Text = true])",
                "    in",
                "      type table [Column1 = _t]",
                "  ),",
                "  #\"Changed Type\" = Table.TransformColumnTypes(Source, {{\"Column1\", Int64.Type}}),",
                "  #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\", {\"Column1\"})",
                "in",
                "  #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI Calls Dynamic Measures %",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "DM % Selection Calls",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f72a0c4a-d20f-466a-ae09-6d6001566332",
            "sortByColumn": "Sort",
            "sourceColumn": "DM % Selection Calls",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "070e8003-e95b-40f4-a5c3-55b19085b06f",
            "sourceColumn": "Sort",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "4b64be7e-f84d-4b60-87e7-805a5c300866",
        "measures": [
          {
            "name": "Dynamic Measures % Calls",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR selection =",
              "    SELECTEDVALUE ( 'KPI Calls Dynamic Measures %'[DM % Selection Calls] )",
              "RETURN",
              "    SWITCH (",
              "        selection,",
              "        \"% < 3 Mins\", [< 3 Mins % (DL)],",
              "        \"% < 5 Mins\", [< 5 Mins % (DL)],",
              "        \"% < 15 Mins\", [< 15 Mins % (DL)],",
              "        \"% Connect Rate\", [Connect Rate % (DL)],",
              "        \"% Overall Call RONA\", [Overall Call RONA % (DL)],",
              "        BLANK ()",
              "    )",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "isHidden": true,
            "lineageTag": "502f7db1-56ea-4267-a71e-e4f0caedc3d1"
          },
          {
            "name": "Dynamic Measures % Calls (All)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR selection =",
              "    SELECTEDVALUE ( 'KPI Calls Dynamic Measures %'[DM % Selection Calls] )",
              "RETURN",
              "    SWITCH (",
              "        selection,",
              "        \"% < 3 Mins\", [< 3 Mins %],",
              "        \"% < 5 Mins\", [< 5 Mins %],",
              "        \"% < 15 Mins\", [< 15 Mins %],",
              "        \"% Connect Rate\", [Connect Rate %],",
              "        \"% Overall Call RONA\", [RONA % (Overall Call )],",
              "        BLANK ()",
              "    )",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "isHidden": true,
            "lineageTag": "1bf6e364-388c-4c49-91bb-f7bce4668a49"
          }
        ],
        "partitions": [
          {
            "name": "KPI Calls Dynamic Measures %-68c2bdef-6474-4856-8284-fd2ec4417d0d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "  Source = Table.FromRows(",
                "    Json.Document(",
                "      Binary.Decompress(",
                "        Binary.FromText(",
                "          \"i45WUlWIKTUwME5WMFbwzcwrVtJRMlSK1UESN4WJG6GKG8IljJViYwE=\",",
                "          BinaryEncoding.Base64",
                "        ),",
                "        Compression.Deflate",
                "      )",
                "    ),",
                "    let",
                "      _t = ((type nullable text) meta [Serialized.Text = true])",
                "    in",
                "      type table [#\"DM % Selection Calls\" = _t, Sort = _t]",
                "  ),",
                "  #\"Changed Type\" = Table.TransformColumnTypes(",
                "    Source,",
                "    {{\"DM % Selection Calls\", type text}, {\"Sort\", Int64.Type}}",
                "  )",
                "in",
                "  #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI Calls Dynamic Measures Cnt",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "DM Cnt Selection Calls",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b49464c8-e4a9-4e85-95d6-afeda6a66b8c",
            "sortByColumn": "Sort",
            "sourceColumn": "DM Cnt Selection Calls",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ad09dfa0-c333-43c8-89f4-8492ea461254",
            "sourceColumn": "Sort",
            "summarizeBy": "sum"
          }
        ],
        "isHidden": true,
        "lineageTag": "e6a538a1-5b82-443f-af33-b892dd79c3d2",
        "measures": [
          {
            "name": "Dynamic Measures Cnt Calls (All)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR selection =",
              "    SELECTEDVALUE ( 'KPI Calls Dynamic Measures Cnt'[DM Cnt Selection Calls] )",
              "RETURN",
              "    SWITCH (",
              "        selection,",
              "        \"Calls Answered\", [Calls Answered],",
              "        \"Calls Offered\", [Calls Offered],",
              "        \"Calls Handled\", [Calls Handled],",
              "        BLANK ()",
              "    )",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "cf83bd80-76c4-4a93-9787-f890a8a13cb5"
          },
          {
            "name": "Dynamic Measures Cnt Calls",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR selection =",
              "    SELECTEDVALUE ( 'KPI Calls Dynamic Measures Cnt'[DM Cnt Selection Calls] )",
              "RETURN",
              "    SWITCH (",
              "        selection,",
              "        \"Calls Answered\", [Calls Answered (DL)],",
              "        \"Calls Offered\", [Calls Offered (DL)],",
              "        \"Calls Handled\", [Calls Handled (DL)],",
              "        BLANK ()",
              "    )",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "401e31e0-ff43-4de4-a040-3c11676f4563"
          }
        ],
        "partitions": [
          {
            "name": "KPI Calls Dynamic Measures Cnt-362f20dd-fb9f-454e-911f-54e2d7de90e4",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "  Source = Table.FromRows(",
                "    Json.Document(",
                "      Binary.Decompress(",
                "        Binary.FromText(\"i45Wck7MySlWcMwrLk8tSk1R0lEyUorVgQn7p6VBRQ2VYmMB\", BinaryEncoding.Base64),",
                "        Compression.Deflate",
                "      )",
                "    ),",
                "    let",
                "      _t = ((type nullable text) meta [Serialized.Text = true])",
                "    in",
                "      type table [#\"DM Cnt Selection Calls\" = _t, Sort = _t]",
                "  ),",
                "  #\"Changed Type\" = Table.TransformColumnTypes(",
                "    Source,",
                "    {{\"DM Cnt Selection Calls\", type text}, {\"Sort\", Int64.Type}}",
                "  ),",
                "  #\"Appended Query\" = Table.Combine({#\"Changed Type\", #\"Calls Abandoned\"}),",
                "  #\"Sorted Rows\" = Table.Sort(#\"Appended Query\", {{\"Sort\", Order.Ascending}})",
                "in",
                "  #\"Sorted Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI Cases",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "7dd07cb7-e78a-4742-bd56-94d9f30e806a",
        "measures": [
          {
            "name": "Avg Days to Close",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "DIVIDE ( [Total Hours to Close], 'KPI Cases'[Cases Closed] ) / 24",
              ""
            ],
            "formatString": "0.00",
            "lineageTag": "1ea823f2-ff46-4f58-9317-1aaf7b5a27eb"
          },
          {
            "name": "Total Hours to Close",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUM ( 'Case Metrics'[Minutes to Close Service Request] ) / 60",
              ""
            ],
            "lineageTag": "92fd2279-339f-46b2-9e5f-29818e162d0b"
          },
          {
            "name": "Cases Closed",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATETABLE (",
              "    ROW ( \"Cases Total\", [Cases Total] ),",
              "    KEEPFILTERS ( TREATAS ( { \"ClosedBy\" }, 'Case Metrics'[Case Disposition] ) )",
              ")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "589d3a22-ea78-46e0-9824-dbafebdd521b"
          },
          {
            "name": "Cases Total",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "DISTINCTCOUNT ( 'Case Metrics'[Service Request Id] )",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "dde75201-c17a-44e8-82c2-13d726fe7689"
          },
          {
            "name": "Case Closed Max Date",
            "expression": [
              "",
              "FORMAT ( MAX ( 'Cases'[TSC Closed By Date] ), \"Short Date\" )",
              ""
            ],
            "lineageTag": "e2cee1ed-a3e6-4ad3-beb4-0abcd8bbaf51"
          },
          {
            "name": "Case Closed Min Date",
            "expression": [
              "",
              "CALCULATE (",
              "    FORMAT ( MIN ( 'Cases'[TSC Closed By Date] ), \"Short Date\" ),",
              "    'Cases'[TSC Closed By Date] <> 2",
              ")",
              ""
            ],
            "lineageTag": "027ff2ca-3ab0-4efd-b048-a2f836497b4e"
          },
          {
            "name": "Case Opened Max Date",
            "expression": [
              "",
              "FORMAT ( MAX ( 'Cases'[Service Request Start Date] ), \"Short Date\" )",
              ""
            ],
            "lineageTag": "714387d2-9c6e-4dbd-9e67-1f2a954caa63"
          },
          {
            "name": "Case Opened Min Date",
            "expression": [
              "",
              "FORMAT ( MIN ( 'Cases'[Service Request Start Date] ), \"Short Date\" )",
              ""
            ],
            "lineageTag": "6ffeb0e7-7154-4cc0-8c94-7b277ef98390"
          },
          {
            "name": "Cases Assigned",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATETABLE (",
              "    ROW ( \"Cases Total\", [Cases Total] ),",
              "    KEEPFILTERS ( TREATAS ( { \"OpenedBy\" }, 'Case Metrics'[Case Disposition] ) ),",
              "    KEEPFILTERS (",
              "        FILTER (",
              "            ALL ( 'Case Metrics'[Time To Assign Duration Minutes] ),",
              "            'Case Metrics'[Time To Assign Duration Minutes] > 0",
              "        )",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "53be83bc-db5f-41ab-853d-a2785bc3e40b"
          },
          {
            "name": "Cases Created",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATETABLE (",
              "    ROW ( \"Cases Total\", [Cases Total] ),",
              "    KEEPFILTERS ( TREATAS ( { \"OpenedBy\" }, 'Case Metrics'[Case Disposition] ) )",
              ")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "9fbf7ba3-6bd2-4ecc-9925-12cb2d4d4c64"
          },
          {
            "name": "Close 24 Hours",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATETABLE (",
              "    ROW ( \"Cases Closed\", [Cases Closed] ),",
              "    FILTER (",
              "        KEEPFILTERS ( VALUES ( 'Case Metrics'[Case Disposition] ) ),",
              "        'Case Metrics'[Case Disposition] = \"ClosedBy\"",
              "    ),",
              "    FILTER (",
              "        KEEPFILTERS ( VALUES ( 'Case Metrics'[TSC Complete Flag] ) ),",
              "        'Case Metrics'[TSC Complete Flag] = \"Y\"",
              "    ),",
              "    FILTER (",
              "        KEEPFILTERS ( VALUES ( 'Case Metrics'[Close 24 Hour Flag] ) ),",
              "        'Case Metrics'[Close 24 Hour Flag] = 1",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "a9e6a687-3878-4304-973a-c26ff54e2889"
          },
          {
            "name": "Close 24 Hours %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "DIVIDE ( 'KPI Cases'[Close 24 Hours], 'KPI Cases'[Cases Closed] )",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "b256063a-4019-4b7d-af72-6ba1467d9fbb"
          },
          {
            "name": "Close 5 Days",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATETABLE (",
              "    ROW ( \"Cases Closed\", [Cases Closed] ),",
              "    KEEPFILTERS (",
              "        TREATAS (",
              "            { \"0\", \"Within 24 hour\", \"Within 1-3 Days\", \"Within 4-5 Days\" },",
              "            'Minutes To Close Bucket'[Minutes To Close Bucket]",
              "        )",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "f6ed2a3d-ed22-4f97-94ca-fc83e392438f"
          },
          {
            "name": "Close 5 Days %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "DIVIDE ( 'KPI Cases'[Close 5 Days], 'KPI Cases'[Cases Closed] )",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "4eed4854-1375-4985-b02e-f8c486d531ae"
          },
          {
            "name": "Dispatched",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATETABLE (",
              "    ROW ( \"Cases Open\", [Cases Created] ),",
              "    KEEPFILTERS ( TREATAS ( { \"Y\" }, 'Case Metrics'[Dispatch Flag] ) ),",
              "    KEEPFILTERS ( TREATAS ( { \"OpenedBy\" }, 'Case Metrics'[Case Disposition] ) )",
              ")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "c67ded4a-cd09-44cf-83f9-2a38e11395f4"
          },
          {
            "name": "Dispatched %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "DIVIDE ( [Dispatched], 'KPI Cases'[Cases Created] )",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "200386ce-51a3-444c-93b5-eddc66c86389"
          },
          {
            "name": "Reassignments Average",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "DIVIDE ( [Reassignments Total], 'KPI Cases'[Cases Closed] )",
              ""
            ],
            "formatString": "0.00",
            "lineageTag": "606c0b56-8fa7-4ff3-aaf5-971d86b8f7c2"
          },
          {
            "name": "Reassignments Total",
            "expression": [
              "",
              "SUM ( 'Case Metrics'[Number of Reassignments] )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "bac1bb0f-2ee5-480f-8a0f-44a127340ad5"
          },
          {
            "name": "Time to Assign Average",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE (",
              "    [Time to Assign Duration Minutes (Total)],",
              "    'KPI Cases'[Cases Assigned]",
              ") / 60",
              ""
            ],
            "lineageTag": "6ed9a65b-4c9b-4816-a866-375cc17f04b6"
          },
          {
            "name": "Time to Assign Duration Minutes (Total)",
            "expression": [
              "",
              "SUM ( 'Case Metrics'[Time To Assign Duration Minutes] )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "095f84ef-903b-4824-aabe-8f16af378c67"
          },
          {
            "name": "Total Days to Close",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[Total Hours to Close] / 24",
              ""
            ],
            "lineageTag": "db468451-f757-4d54-9795-5b249c1ece63"
          },
          {
            "name": "Community Cases",
            "expression": [
              "",
              "CALCULATETABLE (",
              "    ROW ( \"Cases Created\", [Cases Created] ),",
              "    KEEPFILTERS ( TREATAS ( { \"Y\" }, 'Case Metrics'[Community Case Flag] ) )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "fe72f07a-d043-4dcb-969b-aa93a1f20f6b"
          },
          {
            "name": "Community Case Eligible",
            "expression": [
              "",
              "SUM ( 'Case Metrics'[CommunityCaseEligible] )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "bb2fd954-f674-4ebb-98b0-c5de60398aa8"
          },
          {
            "name": "Community Case %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "DIVIDE ( 'KPI Cases'[Community Cases], 'KPI Cases'[Community Case Eligible] )",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "72095a41-a991-4ba6-9460-a168126372c5"
          },
          {
            "name": "Cases Closed with KA",
            "expression": [
              "CALCULATETABLE(",
              "    ROW(",
              "    \"Cases Total\", [Cases Total]",
              "    ),",
              "    KEEPFILTERS( TREATAS( {\"ClosedBy\"}, 'Case Metrics'[Case Disposition] )),",
              "    KEEPFILTERS( FILTER( ALL( 'Case Metrics'[Knowledge Article ID] ), NOT( 'Case Metrics'[Knowledge Article ID] IN {\"9999999999\",\"999999999999999999\"} )))",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "3410d1d0-eb19-41d3-aff4-188b996bdb42"
          },
          {
            "name": "Cases Closed with KA %",
            "expression": "DIVIDE([Cases Closed with KA], [Cases Closed])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "c7409c24-7d18-464c-ad83-506ca311313d"
          }
        ],
        "partitions": [
          {
            "name": "KPI Cases-cf882da6-77aa-4793-aabd-1bc430bf618f",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "  Source = Table.FromRows(",
                "    Json.Document(",
                "      Binary.Decompress(Binary.FromText(\"i45WMlSKjQUA\", BinaryEncoding.Base64), Compression.Deflate)",
                "    ),",
                "    let",
                "      _t = ((type nullable text) meta [Serialized.Text = true])",
                "    in",
                "      type table [Column1 = _t]",
                "  ),",
                "  #\"Changed Type\" = Table.TransformColumnTypes(Source, {{\"Column1\", Int64.Type}}),",
                "  #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\", {\"Column1\"})",
                "in",
                "  #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI Cases Dynamic Legend",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "isHidden": true,
        "lineageTag": "c0c9dc80-620d-44ab-b1d9-aeee1bfd558f",
        "measures": [
          {
            "name": "Avg Days to Close (DL)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [Avg Days to Close],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Product] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Category\",",
              "        CALCULATE (",
              "            [Avg Days to Close],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Category Code Description] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Priority\",",
              "        CALCULATE (",
              "            [Avg Days to Close],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Priority Description] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Community\",",
              "        CALCULATE (",
              "            [Avg Days to Close],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Community Case Flag] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"PHL4\",",
              "        CALCULATE (",
              "            [Avg Days to Close],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[PHL4] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"PHL5\",",
              "        CALCULATE (",
              "            [Avg Days to Close],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[PHL5] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [Avg Days to Close],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Mngr Level 1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [Avg Days to Close],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Agent] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "isHidden": true,
            "lineageTag": "f828f4d8-d2c3-43ff-97f4-f3ed24a4e1ee"
          },
          {
            "name": "Cases Completed (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [Cases Closed],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Product] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Category\",",
              "        CALCULATE (",
              "            [Cases Closed],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Category Code Description] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Priority\",",
              "        CALCULATE (",
              "            [Cases Closed],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Priority Description] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Community\",",
              "        CALCULATE (",
              "            [Cases Closed],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Community Case Flag] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"PHL4\",",
              "        CALCULATE (",
              "            [Cases Closed],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[PHL4] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"PHL5\",",
              "        CALCULATE (",
              "            [Cases Closed],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[PHL5] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [Cases Closed],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Mngr Level 1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [Cases Closed],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Agent] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "0e687793-567d-4c8c-9cc2-ec92e082be3e"
          },
          {
            "name": "Cases Created (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [Cases Created],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Product] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Category\",",
              "        CALCULATE (",
              "            [Cases Created],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Category Code Description] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Priority\",",
              "        CALCULATE (",
              "            [Cases Created],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Priority Description] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Community\",",
              "        CALCULATE (",
              "            [Cases Created],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Community Case Flag] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"PHL4\",",
              "        CALCULATE (",
              "            [Cases Created],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[PHL4] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"PHL5\",",
              "        CALCULATE (",
              "            [Cases Created],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[PHL5] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [Cases Created],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Mngr Level 1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [Cases Created],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Agent] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "2df234c0-1e0d-49e0-bf08-9d0314faff59"
          },
          {
            "name": "Close 24 Hrs (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [Close 24 Hours],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Product] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Category\",",
              "        CALCULATE (",
              "            [Close 24 Hours],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Category Code Description] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Priority\",",
              "        CALCULATE (",
              "            [Close 24 Hours],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Priority Description] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Community\",",
              "        CALCULATE (",
              "            [Close 24 Hours],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Community Case Flag] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"PHL4\",",
              "        CALCULATE (",
              "            [Close 24 Hours],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[PHL4] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"PHL5\",",
              "        CALCULATE (",
              "            [Close 24 Hours],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[PHL5] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [Close 24 Hours],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Mngr Level 1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [Close 24 Hours],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Agent] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "7cc6d77d-9de6-4443-9920-b8aeba640235"
          },
          {
            "name": "Close 24 Hrs % (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [Close 24 Hours %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Product] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Category\",",
              "        CALCULATE (",
              "            [Close 24 Hours %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Category Code Description] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Priority\",",
              "        CALCULATE (",
              "            [Close 24 Hours %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Priority Description] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Community\",",
              "        CALCULATE (",
              "            [Close 24 Hours %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Community Case Flag] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"PHL4\",",
              "        CALCULATE (",
              "            [Close 24 Hours %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[PHL4] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"PHL5\",",
              "        CALCULATE (",
              "            [Close 24 Hours %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[PHL5] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [Close 24 Hours %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Mngr Level 1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [Close 24 Hours %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Agent] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "isHidden": true,
            "lineageTag": "ce343d3e-dc52-4b5a-bb6d-5a892dca1140"
          },
          {
            "name": "Close 5 (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [Close 5 Days],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Product] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Category\",",
              "        CALCULATE (",
              "            [Close 5 Days],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Category Code Description] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Priority\",",
              "        CALCULATE (",
              "            [Close 5 Days],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Priority Description] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Community\",",
              "        CALCULATE (",
              "            [Close 5 Days],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Community Case Flag] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"PHL4\",",
              "        CALCULATE (",
              "            [Close 5 Days],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[PHL4] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"PHL5\",",
              "        CALCULATE (",
              "            [Close 5 Days],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[PHL5] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [Close 5 Days],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Mngr Level 1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [Close 5 Days],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Agent] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "207f8463-242d-4bf9-920b-d14278a3ae47"
          },
          {
            "name": "Close 5 % (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [Close 5 Days %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Product] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Category\",",
              "        CALCULATE (",
              "            [Close 5 Days %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Category Code Description] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Priority\",",
              "        CALCULATE (",
              "            [Close 5 Days %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Priority Description] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Community\",",
              "        CALCULATE (",
              "            [Close 5 Days %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Community Case Flag] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"PHL4\",",
              "        CALCULATE (",
              "            [Close 5 Days %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[PHL4] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"PHL5\",",
              "        CALCULATE (",
              "            [Close 5 Days %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[PHL5] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [Close 5 Days %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Mngr Level 1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [Close 5 Days %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Agent] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "isHidden": true,
            "lineageTag": "bd1f491c-0b9d-4fc5-be75-11eaf5af5ded"
          },
          {
            "name": "Community Case % (DL)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCommunityCases[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [Community Case %],",
              "            USERELATIONSHIP ( 'DynamicLegendCommunityCases'[CategoryValueIndex], 'Case Metrics'[Product] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCommunityCases[Field] ) = \"Priority\",",
              "        CALCULATE (",
              "            [Community Case %],",
              "            USERELATIONSHIP ( 'DynamicLegendCommunityCases'[CategoryValueIndex], 'Case Metrics'[Priority Description] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "isHidden": true,
            "lineageTag": "e8434f5e-4940-4a37-bc54-d19c470e7f36"
          },
          {
            "name": "Community Cases (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCommunityCases[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [Community Cases],",
              "            USERELATIONSHIP ( 'DynamicLegendCommunityCases'[CategoryValueIndex], 'Case Metrics'[Product] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCommunityCases[Field] ) = \"Priority\",",
              "        CALCULATE (",
              "            [Community Cases],",
              "            USERELATIONSHIP ( 'DynamicLegendCommunityCases'[CategoryValueIndex], 'Case Metrics'[Priority Description] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "a6955a1e-cd54-49fa-bc3a-6e12e6b32a6a"
          },
          {
            "name": "Community Cases Eligible (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCommunityCases[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [Community Case Eligible],",
              "            USERELATIONSHIP ( 'DynamicLegendCommunityCases'[CategoryValueIndex], 'Case Metrics'[Product] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCommunityCases[Field] ) = \"Priority\",",
              "        CALCULATE (",
              "            [Community Case Eligible],",
              "            USERELATIONSHIP ( 'DynamicLegendCommunityCases'[CategoryValueIndex], 'Case Metrics'[Priority Description] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "295dfa07-840f-49b9-9c24-1c370da81859"
          },
          {
            "name": "Dispatched (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [Dispatched],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Product] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Category\",",
              "        CALCULATE (",
              "            [Dispatched],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Category Code Description] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Priority\",",
              "        CALCULATE (",
              "            [Dispatched],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Priority Description] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Community\",",
              "        CALCULATE (",
              "            [Dispatched],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Community Case Flag] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"PHL4\",",
              "        CALCULATE (",
              "            [Dispatched],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[PHL4] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"PHL5\",",
              "        CALCULATE (",
              "            [Dispatched],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[PHL5] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [Dispatched],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Mngr Level 1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [Dispatched],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Agent] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "dba144c0-3653-4618-8fa7-e35634a48424"
          },
          {
            "name": "Dispatched % (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [Dispatched %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Product] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Category\",",
              "        CALCULATE (",
              "            [Dispatched %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Category Code Description] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Priority\",",
              "        CALCULATE (",
              "            [Dispatched %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Priority Description] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Community\",",
              "        CALCULATE (",
              "            [Dispatched %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Community Case Flag] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"PHL4\",",
              "        CALCULATE (",
              "            [Dispatched %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[PHL4] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"PHL5\",",
              "        CALCULATE (",
              "            [Dispatched %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[PHL5] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Mngr Level 1\",",
              "        CALCULATE (",
              "            [Dispatched %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Mngr Level 1] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCases[Field] ) = \"Agent\",",
              "        CALCULATE (",
              "            [Dispatched %],",
              "            USERELATIONSHIP ( 'DynamicLegendCases'[CategoryValueIndex], 'Case Metrics'[Agent] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "isHidden": true,
            "lineageTag": "3ee56e62-5e38-4222-bdc7-4f4542df1aca"
          },
          {
            "name": "Time To Assig Avg in Hours (DL)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    SELECTEDVALUE ( DynamicLegendCommunityCases[Field] ) = \"Product\",",
              "        CALCULATE (",
              "            [Time To Assign Average],",
              "            USERELATIONSHIP ( 'DynamicLegendCommunityCases'[CategoryValueIndex], 'Case Metrics'[Product] )",
              "        ),",
              "    SELECTEDVALUE ( DynamicLegendCommunityCases[Field] ) = \"Priority\",",
              "        CALCULATE (",
              "            [Time To Assign Average],",
              "            USERELATIONSHIP ( 'DynamicLegendCommunityCases'[CategoryValueIndex], 'Case Metrics'[Priority Description] )",
              "        ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "lineageTag": "a831b132-539a-408a-bb63-cc6429037f61"
          }
        ],
        "partitions": [
          {
            "name": "KPI Cases Dynamic Legend-736eebfd-79a2-46c3-a48f-6e0cc6a31669",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "  Source = Table.FromRows(",
                "    Json.Document(",
                "      Binary.Decompress(Binary.FromText(\"i45WMlSKjQUA\", BinaryEncoding.Base64), Compression.Deflate)",
                "    ),",
                "    let",
                "      _t = ((type nullable text) meta [Serialized.Text = true])",
                "    in",
                "      type table [Column1 = _t]",
                "  ),",
                "  #\"Changed Type\" = Table.TransformColumnTypes(Source, {{\"Column1\", Int64.Type}}),",
                "  #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\", {\"Column1\"})",
                "in",
                "  #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI Cases Dynamic Measures %",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "DM % Selection Cases",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1b4f9d53-5206-4da7-bd50-d0f5f5abed76",
            "sourceColumn": "DM % Selection Cases",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "896ec96d-30e5-4ba5-b10c-b293314dd963",
            "sourceColumn": "Sort",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "82a3e7b1-3542-4690-956a-e0adea2d64c9",
        "measures": [
          {
            "name": "Dynamic Measures % Cases",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR selection =",
              "    SELECTEDVALUE ( 'KPI Cases Dynamic Measures %'[DM % Selection Cases] )",
              "RETURN",
              "    SWITCH (",
              "        selection,",
              "        \"Close 24 Hrs %\", [Close 24 Hrs % (DL)],",
              "        \"Close 5 Days %\", [Close 5 % (DL)],",
              "        \"Dispatched %\", [Dispatched % (DL)],",
              "        BLANK ()",
              "    )",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "isHidden": true,
            "lineageTag": "57d0f5df-a9bd-4447-b3ca-dd4f43bf67ac"
          },
          {
            "name": "Dynamic Measures % Cases (All)",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR selection =",
              "    SELECTEDVALUE ( 'KPI Cases Dynamic Measures %'[DM % Selection Cases] )",
              "RETURN",
              "    SWITCH (",
              "        selection,",
              "        \"Close 24 Hrs %\", [Close 24 Hours %],",
              "        \"Close 5 Days %\", [Close 5 Days %],",
              "        \"Dispatched %\", [Dispatched %],",
              "        BLANK ()",
              "    )",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "isHidden": true,
            "lineageTag": "5f054ae5-87db-4a07-b916-fa50ae71dba1"
          }
        ],
        "partitions": [
          {
            "name": "KPI Cases Dynamic Measures %-12103c03-95a5-4dbf-94c1-d035bc354b38",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "  Source = Table.FromRows(",
                "    Json.Document(",
                "      Binary.Decompress(",
                "        Binary.FromText(",
                "          \"i45Wcs7JL05VMDJR8CgqVlBV0lEyVIrVgQmbKrgkVkKEjcDCLpnFBYklyRmpKWBBY6XYWAA=\",",
                "          BinaryEncoding.Base64",
                "        ),",
                "        Compression.Deflate",
                "      )",
                "    ),",
                "    let",
                "      _t = ((type nullable text) meta [Serialized.Text = true])",
                "    in",
                "      type table [#\"DM % Selection Cases\" = _t, Sort = _t]",
                "  ),",
                "  #\"Changed Type\" = Table.TransformColumnTypes(",
                "    Source,",
                "    {{\"DM % Selection Cases\", type text}, {\"Sort\", Int64.Type}}",
                "  )",
                "in",
                "  #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI Cases Dynamic Measures Cnt",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "DM Cnt Selections Cases",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8c458016-202d-4f13-b4df-11150faac74f",
            "sortByColumn": "Sort",
            "sourceColumn": "DM Cnt Selections Cases",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fddb9806-9927-4a48-b6ff-c0dd2aa031fc",
            "sourceColumn": "Sort",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "a81083c3-5c29-4f92-bec3-db82f087d1d2",
        "measures": [
          {
            "name": "Dynamic Measures Cnt Cases",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR selection =",
              "    SELECTEDVALUE ( 'KPI Cases Dynamic Measures Cnt'[DM Cnt Selections Cases] )",
              "RETURN",
              "    SWITCH (",
              "        selection,",
              "        \"Avg Days to Close\", [Avg Days to Close (DL)],",
              "        \"Cases Created\", [Cases Created (DL)],",
              "        \"Cases Completed\", [Cases Completed (DL)],",
              "        \"Close 24 Hrs\", [Close 24 Hrs (DL)],",
              "        \"Close 5 Days\", [Close 5 (DL)],",
              "        \"Community Cases\", [Community Cases (DL)],",
              "        \"Avg Days to Close\", [Avg Days to Close (DL)],",
              "        \"Dispatched\", [Dispatched (DL)],",
              "        BLANK ()",
              "    )",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "ac94a9ac-64c1-4a31-bffa-676fd36bcd69"
          },
          {
            "name": "Dynamic Measures Cnt Cases (All)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR selection =",
              "    SELECTEDVALUE ( 'KPI Cases Dynamic Measures Cnt'[DM Cnt Selections Cases] )",
              "RETURN",
              "    SWITCH (",
              "        selection,",
              "        \"Avg Days to Close\", [Avg Days to Close],",
              "        \"Cases Created\", [Cases Created],",
              "        \"Cases Completed\", [Cases Closed],",
              "        \"Close 24 Hrs\", [Close 24 Hours],",
              "        \"Close 5 Days\", [Close 5 Days],",
              "        \"Community Cases\", [Community Cases],",
              "        \"Avg Days to Close\", [Avg Days to Close],",
              "        \"Dispatched\", [Dispatched],",
              "        BLANK ()",
              "    )",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "89ab219a-f841-48cf-b356-b26d3357354c"
          }
        ],
        "partitions": [
          {
            "name": "KPI Cases Dynamic Measures Cnt-f6c5bf0a-fbfd-4396-bc6a-07eaab27e4e6",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "  Source = Table.FromRows(",
                "    Json.Document(",
                "      Binary.Decompress(",
                "        Binary.FromText(",
                "          \"i45Wck4sTi1WcC5KTSxJTVHSUTJUitWBi+bnFuSkQsSNIOI5+cWpCkYmCh5FxUBBYyRBUwWXxEqQoAlY0LEsHSygUJKvAFYAlDEFy7hkFhckliRngI01U4qNBQA=\",",
                "          BinaryEncoding.Base64",
                "        ),",
                "        Compression.Deflate",
                "      )",
                "    ),",
                "    let",
                "      _t = ((type nullable text) meta [Serialized.Text = true])",
                "    in",
                "      type table [#\"DM Cnt Selections Cases\" = _t, Sort = _t]",
                "  ),",
                "  #\"Changed Type\" = Table.TransformColumnTypes(",
                "    Source,",
                "    {{\"DM Cnt Selections Cases\", type text}, {\"Sort\", Int64.Type}}",
                "  )",
                "in",
                "  #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI Community Cases Dynamic Measures %",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "DM % Selection Community Cases",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c95971fa-b74f-4ff6-b441-a490a264d05b",
            "sourceColumn": "DM % Selection Community Cases",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ec21767e-3fa3-40c5-b89b-1f5d2a1b4249",
            "sourceColumn": "Sort",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "efe9f229-62b4-47a0-abfe-8888583f3ee3",
        "measures": [
          {
            "name": "Dynamic Measures % Community Cases",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR selection =",
              "    SELECTEDVALUE ( 'KPI Community Cases Dynamic Measures %'[DM % Selection Community Cases] )",
              "RETURN",
              "    SWITCH ( selection, \"Community Case %\", [Community Case % (DL)], BLANK () )",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "isHidden": true,
            "lineageTag": "79105ce4-089b-44a8-a9eb-80e36eb05806"
          }
        ],
        "partitions": [
          {
            "name": "KPI Community Cases Dynamic Measures %-f4f98c37-bfcc-4ee7-a9a4-fbcf9cb5dda1",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "  Source = Table.FromRows(",
                "    Json.Document(",
                "      Binary.Decompress(",
                "        Binary.FromText(\"i45Wcs7PzS3NyyypVHBOLE5VUFXSUTJUio0FAA==\", BinaryEncoding.Base64),",
                "        Compression.Deflate",
                "      )",
                "    ),",
                "    let",
                "      _t = ((type nullable text) meta [Serialized.Text = true])",
                "    in",
                "      type table [#\"DM % Selection Community Cases\" = _t, Sort = _t]",
                "  ),",
                "  #\"Changed Type\" = Table.TransformColumnTypes(",
                "    Source,",
                "    {{\"DM % Selection Community Cases\", type text}, {\"Sort\", Int64.Type}}",
                "  )",
                "in",
                "  #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI Community Cases Dynamic Measures Cnt",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "DM Cnt Selection Community Cases",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "89c056f2-d99b-4a28-ad66-dde1c277c2e9",
            "sortByColumn": "Sort",
            "sourceColumn": "DM Cnt Selection Community Cases",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5a10fb0e-426a-4de5-b335-1c53408e57dd",
            "sourceColumn": "Sort",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "aac6f9b6-bdf5-4fae-b8ec-ebe1230720b9",
        "measures": [
          {
            "name": "Dynamic Measures Cnt Community Cases",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR selection =",
              "    SELECTEDVALUE ( 'KPI Community Cases Dynamic Measures Cnt'[DM Cnt Selection Community Cases] )",
              "RETURN",
              "    SWITCH (",
              "        selection,",
              "        \"Community Cases\", [Community Cases (DL)],",
              "        \"Cases Eligible\", [Community Cases Eligible (DL)],",
              "        BLANK ()",
              "    )",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "12e14f5e-a4fa-4843-b80f-dc0b2fca2b5c"
          }
        ],
        "partitions": [
          {
            "name": "KPI Community Cases Dynamic Measures Cnt-04b26466-e75e-4517-a810-a222b088206f",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "  Source = Table.FromRows(",
                "    Json.Document(",
                "      Binary.Decompress(",
                "        Binary.FromText(",
                "          \"i45Wcs7PzS3NyyypVHBOLE4tVtJRMlSK1QGKg3gKrjmZ6ZlJOalAYSOl2FgA\",",
                "          BinaryEncoding.Base64",
                "        ),",
                "        Compression.Deflate",
                "      )",
                "    ),",
                "    let",
                "      _t = ((type nullable text) meta [Serialized.Text = true])",
                "    in",
                "      type table [#\"DM Cnt Selection Community Cases\" = _t, Sort = _t]",
                "  ),",
                "  #\"Changed Type\" = Table.TransformColumnTypes(",
                "    Source,",
                "    {{\"DM Cnt Selection Community Cases\", type text}, {\"Sort\", Int64.Type}}",
                "  )",
                "in",
                "  #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI Time to Assign in Hours Dynamic Measures Cnt",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "DM Cnt Selection Time to Assign in Hours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "746bdc82-40f5-4ca9-a87c-2f820bc9b199",
            "sourceColumn": "DM Cnt Selection Time to Assign in Hours",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ff19ed41-7c7e-4188-a97b-d0130a23b06f",
            "sourceColumn": "Sort",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "c2089876-1831-4784-94dd-3302e43d9322",
        "measures": [
          {
            "name": "Dynamic Measures Cnt Time To Assign in Hours",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR selection =",
              "    SELECTEDVALUE ( 'KPI Time to Assign in Hours Dynamic Measures Cnt'[DM Cnt Selection Time To Assign in Hours] )",
              "RETURN",
              "    SWITCH (",
              "        selection,",
              "        \"Time To Assign in Hours\", [Time To Assig Avg in Hours (DL)],",
              "        BLANK ()",
              "    )",
              ""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "c8b32c6b-669e-4c58-aba8-77ba8d2b04c6"
          }
        ],
        "partitions": [
          {
            "name": "KPI Time to Assign in Hours Dynamic Measures Cnt-ac3bd3f8-8444-4999-9323-78ecd2c855fb",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "  Source = Table.FromRows(",
                "    Json.Document(",
                "      Binary.Decompress(",
                "        Binary.FromText(\"i45WCsnMTVUoyVdwLC7OTM9TyMxTyMgvLSpW0lEyVIqNBQA=\", BinaryEncoding.Base64),",
                "        Compression.Deflate",
                "      )",
                "    ),",
                "    let",
                "      _t = ((type nullable text) meta [Serialized.Text = true])",
                "    in",
                "      type table [#\"DM Cnt Selection Time to Assign in Hours\" = _t, Sort = _t]",
                "  ),",
                "  #\"Changed Type\" = Table.TransformColumnTypes(",
                "    Source,",
                "    {{\"DM Cnt Selection Time to Assign in Hours\", type text}, {\"Sort\", Int64.Type}}",
                "  )",
                "in",
                "  #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Knowledge Article",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Article Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0774543e-0505-4668-a5e7-08b863996f18",
            "sourceColumn": "Article Number",
            "summarizeBy": "none"
          },
          {
            "name": "KnowledgeArticleId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a7c88e4e-3290-45f3-bef8-c65768a10a6c",
            "sourceColumn": "KnowledgeArticleId",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "587ef657-6648-4549-8c65-4e4ad84cbbc7",
        "partitions": [
          {
            "name": "Knowledge Article-8738d78c-265d-403e-a595-726393008cb0",
            "mode": "import",
            "queryGroup": "Dim\\Cases",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"02333bff-5df3-4bee-bbca-1c2aea2a33ba\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"02333bff-5df3-4bee-bbca-1c2aea2a33ba\"]}",
                "    [Data],",
                "  #\"Knowledge Article_\" = #\"02333bff-5df3-4bee-bbca-1c2aea2a33ba\"",
                "    {[entity = \"Knowledge Article\", version = \"\"]}",
                "    [Data],",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    #\"Knowledge Article_\",",
                "    {{\"ArticleNumber\", \"Article Number\"}}",
                "  ),",
                "  #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns\", each true)",
                "in",
                "  #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Labels",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "isHidden": true,
        "lineageTag": "744c043f-a37a-4724-a156-65479de178c6",
        "measures": [
          {
            "name": "Label < 3 Mins",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "\"< 3 Mins. \"& [< 3 Mins]",
            "isHidden": true,
            "lineageTag": "f547f052-15bf-4eef-ab4b-13f06192081b"
          },
          {
            "name": "Label < 5 Mins",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "\"< 5 Mins. \"& [< 5 Mins]",
            "isHidden": true,
            "lineageTag": "47929ce3-7895-4ced-b1be-aa65717e8298"
          },
          {
            "name": "Label < 15 Mins",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "\"< 15 Mins. \"& [< 15 Mins]",
            "isHidden": true,
            "lineageTag": "a2324804-c040-46b0-b1f8-95da4b8ed97e"
          },
          {
            "name": "Label Calls Trend DL Charts %",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "Labels[Label Selected DM % Selection Calls] & \" by \" &Labels[Label Selected DL Calls Selection]",
            "isHidden": true,
            "lineageTag": "dd12f487-e28e-4566-a442-52b00489b6b9"
          },
          {
            "name": "Label Selected DM % Selection Calls",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "SELECTEDVALUE('KPI Calls Dynamic Measures %'[DM % Selection Calls])",
            "isHidden": true,
            "lineageTag": "4f8aac0c-45e0-41c4-8811-ae5734f70040"
          },
          {
            "name": "Label Selected DL Calls Selection",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "SELECTEDVALUE('DynamicLegendCalls'[Field])",
            "isHidden": true,
            "lineageTag": "89e7ccd4-914d-4e5d-846b-54f6c7ba556e"
          },
          {
            "name": "Label Selected DL Cases Selection",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "SELECTEDVALUE('DynamicLegendCases'[Field])",
            "isHidden": true,
            "lineageTag": "08ccffb2-4a59-4f3a-bc51-b2bc8d1c527a"
          },
          {
            "name": "Label Calls Trend DL Charts Volume",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "Labels[Label Selected DM Cnt Selection Calls] & \" by \" &Labels[Label Selected DL Calls Selection]",
            "isHidden": true,
            "lineageTag": "a25660ab-660e-433f-add4-a0cbadc74049"
          },
          {
            "name": "Label Selected DM Cnt Selection Calls",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "SELECTEDVALUE('KPI Calls Dynamic Measures Cnt'[DM Cnt Selection Calls])",
            "isHidden": true,
            "lineageTag": "166c2126-8d23-4681-9c4d-ebeb0225ba36"
          },
          {
            "name": "Label Cases Trend DL Charts %",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "Labels[Label Selected DM % Selection Cases] & \" by \" &Labels[Label Selected DL Cases Selection]",
            "isHidden": true,
            "lineageTag": "375a2cb6-3bb8-4d29-8b08-57273c2d1737"
          },
          {
            "name": "Label Selected DM % Selection Cases",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "SELECTEDVALUE('KPI Cases Dynamic Measures %'[DM % Selection Cases])",
            "isHidden": true,
            "lineageTag": "8243261c-ba12-4932-a872-925749dc017d"
          },
          {
            "name": "Label Selected DM Cnt Selection Cases",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "SELECTEDVALUE('KPI Cases Dynamic Measures Cnt'[DM Cnt Selections Cases])",
            "isHidden": true,
            "lineageTag": "25b2caf1-15d5-460f-9cb9-1720dc1a14b0"
          },
          {
            "name": "Label Cases Trend DL Charts Volume",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "Labels[Label Selected DM Cnt Selection Cases] & \" by \" &Labels[Label Selected DL Cases Selection]",
            "isHidden": true,
            "lineageTag": "c07ad908-e9bd-4a20-89cf-5f54d213c469"
          },
          {
            "name": "Label Community Cases Trend DL Charts %",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "Labels[Label Selected DM % Selection Community Cases] & \" by \" &Labels[Label Selected DL Community Cases Selection]",
            "isHidden": true,
            "lineageTag": "261fa679-ecc4-4add-a00b-2ce5cdd2dcd1"
          },
          {
            "name": "Label Selected DL Community Cases Selection",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "SELECTEDVALUE('DynamicLegendCommunityCases'[Field])",
            "isHidden": true,
            "lineageTag": "76bb0990-cd99-4e78-85a2-5314ca3a9567"
          },
          {
            "name": "Label Selected DM % Selection Community Cases",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "SELECTEDVALUE('KPI Community Cases Dynamic Measures %'[DM % Selection Community Cases])",
            "isHidden": true,
            "lineageTag": "de9d2347-590a-476b-9118-ef9f6af58f8b"
          },
          {
            "name": "Label Selected DM Cnt Selection Community Cases",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "SELECTEDVALUE('KPI Community Cases Dynamic Measures Cnt'[DM Cnt Selection Community Cases])",
            "isHidden": true,
            "lineageTag": "d9360f07-6a98-4fd8-bc77-3147e6419120"
          },
          {
            "name": "Label Community Cases Trend DL Charts TTTA",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "\"Time to Assign Avg in Hours by \" &Labels[Label Selected DL Community Cases Selection]",
            "isHidden": true,
            "lineageTag": "4b4add2b-62ef-459a-a834-fe355cb63649"
          },
          {
            "name": "Label Community Cases Trend DL Charts Volume",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "Labels[Label Selected DM Cnt Selection Community Cases] & \" by \" &Labels[Label Selected DL Community Cases Selection]",
            "isHidden": true,
            "lineageTag": "8cf41314-bd4a-4009-8f9f-604231ec7212"
          },
          {
            "name": "Label AHT Trend DL Charts Volume",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "SELECTEDVALUE('KPI AMBD Dynamic Measures Cnt'[DM Cnt Selection AMBD]) & \" by \" & SELECTEDVALUE(DynamicLegendAgentMetricsbyDay[Field])",
            "isHidden": true,
            "lineageTag": "227809bf-aae9-4dd4-955b-548b92af7e91"
          },
          {
            "name": "Label Selected DL AHT Selection",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "SELECTEDVALUE('KPI AMBD Dynamic Measures Cnt'[DM Cnt Selection AMBD])",
            "isHidden": true,
            "lineageTag": "f7bc3c3c-3dba-42c8-a554-7cea5941b85d"
          },
          {
            "name": "Current Selections",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR MaxFilters = 3",
              "RETURN",
              "IF ( ",
              "    ISFILTERED ( 'Actual VQ'[Actual VQ] ), ",
              "    VAR ___f = FILTERS ( 'Actual VQ'[Actual VQ] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Actual VQ'[Actual VQ] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Actual VQ'[Actual VQ], \", \" )",
              "    VAR ___x = \"'Actual VQ'[Actual VQ] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Actual VQ'[Index] ), ",
              "    VAR ___f = FILTERS ( 'Actual VQ'[Index] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Actual VQ'[Index] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Actual VQ'[Index], \", \" )",
              "    VAR ___x = \"'Actual VQ'[Index] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[ACW Time] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[ACW Time] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[ACW Time] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[ACW Time], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[ACW Time] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Agent] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Agent] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Agent] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Agent], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Agent] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[AUX Case Escalation Duration] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[AUX Case Escalation Duration] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[AUX Case Escalation Duration] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[AUX Case Escalation Duration], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[AUX Case Escalation Duration] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[AUX Inbound Case Work Duration] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[AUX Inbound Case Work Duration] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[AUX Inbound Case Work Duration] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[AUX Inbound Case Work Duration], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[AUX Inbound Case Work Duration] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[AUX Ready For Case Duration] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[AUX Ready For Case Duration] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[AUX Ready For Case Duration] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[AUX Ready For Case Duration], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[AUX Ready For Case Duration] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Available Time] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Available Time] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Available Time] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Available Time], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Available Time] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Break Time] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Break Time] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Break Time] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Break Time], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Break Time] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Call Consult] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Call Consult] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Call Consult] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Call Consult], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Call Consult] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Call Dialing] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Call Dialing] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Call Dialing] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Call Dialing], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Call Dialing] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Call Inbound Talk] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Call Inbound Talk] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Call Inbound Talk] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Call Inbound Talk], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Call Inbound Talk] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Call Internal Talk] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Call Internal Talk] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Call Internal Talk] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Call Internal Talk], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Call Internal Talk] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Call On Hold] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Call On Hold] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Call On Hold] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Call On Hold], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Call On Hold] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Call Ringing] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Call Ringing] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Call Ringing] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Call Ringing], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Call Ringing] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Calls Answered] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Calls Answered] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Calls Answered] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Calls Answered], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Calls Answered] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Cases Closed] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Cases Closed] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Cases Closed] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Cases Closed], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Cases Closed] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Cases Closed Dispatched] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Cases Closed Dispatched] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Cases Closed Dispatched] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Cases Closed Dispatched], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Cases Closed Dispatched] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Cases Closed Non Dispatched] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Cases Closed Non Dispatched] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Cases Closed Non Dispatched] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Cases Closed Non Dispatched], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Cases Closed Non Dispatched] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Cases Opened] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Cases Opened] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Cases Opened] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Cases Opened], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Cases Opened] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[CaseWorkTime] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[CaseWorkTime] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[CaseWorkTime] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[CaseWorkTime], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[CaseWorkTime] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[CoachingTime] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[CoachingTime] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[CoachingTime] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[CoachingTime], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[CoachingTime] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Date] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Date], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Date - Copy] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Date - Copy] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Date - Copy] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Date - Copy], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Date - Copy] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Employee ID] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Employee ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Employee ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Employee ID], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Employee ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[EmployeeID|Date] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[EmployeeID|Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[EmployeeID|Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[EmployeeID|Date], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[EmployeeID|Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Idle Time] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Idle Time] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Idle Time] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Idle Time], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Idle Time] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[It Issue Time] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[It Issue Time] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[It Issue Time] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[It Issue Time], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[It Issue Time] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Logged In Time] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Logged In Time] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Logged In Time] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Logged In Time], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Logged In Time] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[LunchTime] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[LunchTime] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[LunchTime] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[LunchTime], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[LunchTime] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[MeetingTime] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[MeetingTime] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[MeetingTime] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[MeetingTime], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[MeetingTime] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Mentor Time] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Mentor Time] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Mentor Time] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Mentor Time], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Mentor Time] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Mngr Level 1] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Mngr Level 1] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Mngr Level 1] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Mngr Level 1], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Mngr Level 1] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[PCP Time] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[PCP Time] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[PCP Time] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[PCP Time], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[PCP Time] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Personal Time] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Personal Time] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Personal Time] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Personal Time], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Personal Time] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[PP] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[PP] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[PP] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[PP], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[PP] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[PPG] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[PPG] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[PPG] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[PPG], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[PPG] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Primary Product] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Primary Product] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Primary Product] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Primary Product], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Primary Product] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Primary Product Group] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Primary Product Group] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Primary Product Group] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Primary Product Group], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Primary Product Group] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Special Projects Time] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Special Projects Time] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Special Projects Time] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Special Projects Time], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Special Projects Time] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Talk Time Outbound Personal] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Talk Time Outbound Personal] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Talk Time Outbound Personal] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Talk Time Outbound Personal], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Talk Time Outbound Personal] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Metrics by Day'[Training Time] ), ",
              "    VAR ___f = FILTERS ( 'Agent Metrics by Day'[Training Time] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Metrics by Day'[Training Time] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Metrics by Day'[Training Time], \", \" )",
              "    VAR ___x = \"'Agent Metrics by Day'[Training Time] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Product Assignment'[Employee ID] ), ",
              "    VAR ___f = FILTERS ( 'Agent Product Assignment'[Employee ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Product Assignment'[Employee ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Product Assignment'[Employee ID], \", \" )",
              "    VAR ___x = \"'Agent Product Assignment'[Employee ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Product Assignment'[EmployeeID|ExtractDate] ), ",
              "    VAR ___f = FILTERS ( 'Agent Product Assignment'[EmployeeID|ExtractDate] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Product Assignment'[EmployeeID|ExtractDate] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Product Assignment'[EmployeeID|ExtractDate], \", \" )",
              "    VAR ___x = \"'Agent Product Assignment'[EmployeeID|ExtractDate] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Product Assignment'[Extract Date] ), ",
              "    VAR ___f = FILTERS ( 'Agent Product Assignment'[Extract Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Product Assignment'[Extract Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Product Assignment'[Extract Date], \", \" )",
              "    VAR ___x = \"'Agent Product Assignment'[Extract Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Product Assignment'[ExtractDate - Copy] ), ",
              "    VAR ___f = FILTERS ( 'Agent Product Assignment'[ExtractDate - Copy] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Product Assignment'[ExtractDate - Copy] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Product Assignment'[ExtractDate - Copy], \", \" )",
              "    VAR ___x = \"'Agent Product Assignment'[ExtractDate - Copy] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Product Assignment'[Location] ), ",
              "    VAR ___f = FILTERS ( 'Agent Product Assignment'[Location] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Product Assignment'[Location] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Product Assignment'[Location], \", \" )",
              "    VAR ___x = \"'Agent Product Assignment'[Location] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Product Assignment'[Primary Product] ), ",
              "    VAR ___f = FILTERS ( 'Agent Product Assignment'[Primary Product] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Product Assignment'[Primary Product] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Product Assignment'[Primary Product], \", \" )",
              "    VAR ___x = \"'Agent Product Assignment'[Primary Product] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Product Assignment'[Primary Product Group] ), ",
              "    VAR ___f = FILTERS ( 'Agent Product Assignment'[Primary Product Group] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Product Assignment'[Primary Product Group] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Product Assignment'[Primary Product Group], \", \" )",
              "    VAR ___x = \"'Agent Product Assignment'[Primary Product Group] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Product Assignment'[Secondary Product] ), ",
              "    VAR ___f = FILTERS ( 'Agent Product Assignment'[Secondary Product] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Product Assignment'[Secondary Product] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Product Assignment'[Secondary Product], \", \" )",
              "    VAR ___x = \"'Agent Product Assignment'[Secondary Product] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Agent Product Assignment'[Tertiary Product] ), ",
              "    VAR ___f = FILTERS ( 'Agent Product Assignment'[Tertiary Product] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Agent Product Assignment'[Tertiary Product] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Agent Product Assignment'[Tertiary Product], \", \" )",
              "    VAR ___x = \"'Agent Product Assignment'[Tertiary Product] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( AgentProductMapping[EmployeeId] ), ",
              "    VAR ___f = FILTERS ( AgentProductMapping[EmployeeId] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, AgentProductMapping[EmployeeId] )",
              "    VAR ___d = CONCATENATEX ( ___t, AgentProductMapping[EmployeeId], \", \" )",
              "    VAR ___x = \"AgentProductMapping[EmployeeId] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( AgentProductMapping[EmployeeID|ExtractDate] ), ",
              "    VAR ___f = FILTERS ( AgentProductMapping[EmployeeID|ExtractDate] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, AgentProductMapping[EmployeeID|ExtractDate] )",
              "    VAR ___d = CONCATENATEX ( ___t, AgentProductMapping[EmployeeID|ExtractDate], \", \" )",
              "    VAR ___x = \"AgentProductMapping[EmployeeID|ExtractDate] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( AgentProductMapping[ExtractDate] ), ",
              "    VAR ___f = FILTERS ( AgentProductMapping[ExtractDate] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, AgentProductMapping[ExtractDate] )",
              "    VAR ___d = CONCATENATEX ( ___t, AgentProductMapping[ExtractDate], \", \" )",
              "    VAR ___x = \"AgentProductMapping[ExtractDate] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( AgentProductMapping[ExtractDate - Copy] ), ",
              "    VAR ___f = FILTERS ( AgentProductMapping[ExtractDate - Copy] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, AgentProductMapping[ExtractDate - Copy] )",
              "    VAR ___d = CONCATENATEX ( ___t, AgentProductMapping[ExtractDate - Copy], \", \" )",
              "    VAR ___x = \"AgentProductMapping[ExtractDate - Copy] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( AgentProductMapping[Location] ), ",
              "    VAR ___f = FILTERS ( AgentProductMapping[Location] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, AgentProductMapping[Location] )",
              "    VAR ___d = CONCATENATEX ( ___t, AgentProductMapping[Location], \", \" )",
              "    VAR ___x = \"AgentProductMapping[Location] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( AgentProductMapping[PP] ), ",
              "    VAR ___f = FILTERS ( AgentProductMapping[PP] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, AgentProductMapping[PP] )",
              "    VAR ___d = CONCATENATEX ( ___t, AgentProductMapping[PP], \", \" )",
              "    VAR ___x = \"AgentProductMapping[PP] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( AgentProductMapping[PPG] ), ",
              "    VAR ___f = FILTERS ( AgentProductMapping[PPG] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, AgentProductMapping[PPG] )",
              "    VAR ___d = CONCATENATEX ( ___t, AgentProductMapping[PPG], \", \" )",
              "    VAR ___x = \"AgentProductMapping[PPG] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( AgentProductMapping[PrimaryProduct] ), ",
              "    VAR ___f = FILTERS ( AgentProductMapping[PrimaryProduct] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, AgentProductMapping[PrimaryProduct] )",
              "    VAR ___d = CONCATENATEX ( ___t, AgentProductMapping[PrimaryProduct], \", \" )",
              "    VAR ___x = \"AgentProductMapping[PrimaryProduct] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( AgentProductMapping[PrimaryProductGroup] ), ",
              "    VAR ___f = FILTERS ( AgentProductMapping[PrimaryProductGroup] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, AgentProductMapping[PrimaryProductGroup] )",
              "    VAR ___d = CONCATENATEX ( ___t, AgentProductMapping[PrimaryProductGroup], \", \" )",
              "    VAR ___x = \"AgentProductMapping[PrimaryProductGroup] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( AgentProductMapping[SecondaryProduct] ), ",
              "    VAR ___f = FILTERS ( AgentProductMapping[SecondaryProduct] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, AgentProductMapping[SecondaryProduct] )",
              "    VAR ___d = CONCATENATEX ( ___t, AgentProductMapping[SecondaryProduct], \", \" )",
              "    VAR ___x = \"AgentProductMapping[SecondaryProduct] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( AgentProductMapping[TertiaryProduct] ), ",
              "    VAR ___f = FILTERS ( AgentProductMapping[TertiaryProduct] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, AgentProductMapping[TertiaryProduct] )",
              "    VAR ___d = CONCATENATEX ( ___t, AgentProductMapping[TertiaryProduct], \", \" )",
              "    VAR ___x = \"AgentProductMapping[TertiaryProduct] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Associate[Business Site Name] ), ",
              "    VAR ___f = FILTERS ( Associate[Business Site Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Associate[Business Site Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, Associate[Business Site Name], \", \" )",
              "    VAR ___x = \"Associate[Business Site Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Associate[Display Name] ), ",
              "    VAR ___f = FILTERS ( Associate[Display Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Associate[Display Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, Associate[Display Name], \", \" )",
              "    VAR ___x = \"Associate[Display Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Associate[Employee Status] ), ",
              "    VAR ___f = FILTERS ( Associate[Employee Status] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Associate[Employee Status] )",
              "    VAR ___d = CONCATENATEX ( ___t, Associate[Employee Status], \", \" )",
              "    VAR ___x = \"Associate[Employee Status] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Associate[EmployeeID|ExtractDate] ), ",
              "    VAR ___f = FILTERS ( Associate[EmployeeID|ExtractDate] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Associate[EmployeeID|ExtractDate] )",
              "    VAR ___d = CONCATENATEX ( ___t, Associate[EmployeeID|ExtractDate], \", \" )",
              "    VAR ___x = \"Associate[EmployeeID|ExtractDate] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Associate[Extract Date] ), ",
              "    VAR ___f = FILTERS ( Associate[Extract Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Associate[Extract Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, Associate[Extract Date], \", \" )",
              "    VAR ___x = \"Associate[Extract Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Associate[Location] ), ",
              "    VAR ___f = FILTERS ( Associate[Location] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Associate[Location] )",
              "    VAR ___d = CONCATENATEX ( ___t, Associate[Location], \", \" )",
              "    VAR ___x = \"Associate[Location] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Associate[Manager Level 1] ), ",
              "    VAR ___f = FILTERS ( Associate[Manager Level 1] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Associate[Manager Level 1] )",
              "    VAR ___d = CONCATENATEX ( ___t, Associate[Manager Level 1], \", \" )",
              "    VAR ___x = \"Associate[Manager Level 1] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Associate[Manager Level 2] ), ",
              "    VAR ___f = FILTERS ( Associate[Manager Level 2] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Associate[Manager Level 2] )",
              "    VAR ___d = CONCATENATEX ( ___t, Associate[Manager Level 2], \", \" )",
              "    VAR ___x = \"Associate[Manager Level 2] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Associate[Max Extract Date] ), ",
              "    VAR ___f = FILTERS ( Associate[Max Extract Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Associate[Max Extract Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, Associate[Max Extract Date], \", \" )",
              "    VAR ___x = \"Associate[Max Extract Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Associate[Org Unit] ), ",
              "    VAR ___f = FILTERS ( Associate[Org Unit] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Associate[Org Unit] )",
              "    VAR ___d = CONCATENATEX ( ___t, Associate[Org Unit], \", \" )",
              "    VAR ___x = \"Associate[Org Unit] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Associate[Primary Product] ), ",
              "    VAR ___f = FILTERS ( Associate[Primary Product] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Associate[Primary Product] )",
              "    VAR ___d = CONCATENATEX ( ___t, Associate[Primary Product], \", \" )",
              "    VAR ___x = \"Associate[Primary Product] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Associate[Primary Product Group] ), ",
              "    VAR ___f = FILTERS ( Associate[Primary Product Group] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Associate[Primary Product Group] )",
              "    VAR ___d = CONCATENATEX ( ___t, Associate[Primary Product Group], \", \" )",
              "    VAR ___x = \"Associate[Primary Product Group] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Actual Product Skill] ), ",
              "    VAR ___f = FILTERS ( Calls[Actual Product Skill] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Actual Product Skill] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Actual Product Skill], \", \" )",
              "    VAR ___x = \"Calls[Actual Product Skill] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[ActualVQ] ), ",
              "    VAR ___f = FILTERS ( Calls[ActualVQ] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[ActualVQ] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[ActualVQ], \", \" )",
              "    VAR ___x = \"Calls[ActualVQ] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Agent] ), ",
              "    VAR ___f = FILTERS ( Calls[Agent] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Agent] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Agent], \", \" )",
              "    VAR ___x = \"Calls[Agent] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[ANI] ), ",
              "    VAR ___f = FILTERS ( Calls[ANI] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[ANI] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[ANI], \", \" )",
              "    VAR ___x = \"Calls[ANI] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Call Date] ), ",
              "    VAR ___f = FILTERS ( Calls[Call Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Call Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Call Date], \", \" )",
              "    VAR ___x = \"Calls[Call Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Call Rona] ), ",
              "    VAR ___f = FILTERS ( Calls[Call Rona] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Call Rona] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Call Rona], \", \" )",
              "    VAR ___x = \"Calls[Call Rona] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Calls Abandoned] ), ",
              "    VAR ___f = FILTERS ( Calls[Calls Abandoned] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Calls Abandoned] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Calls Abandoned], \", \" )",
              "    VAR ___x = \"Calls[Calls Abandoned] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Calls Answered] ), ",
              "    VAR ___f = FILTERS ( Calls[Calls Answered] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Calls Answered] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Calls Answered], \", \" )",
              "    VAR ___x = \"Calls[Calls Answered] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Calls Answered In 15 Minutes] ), ",
              "    VAR ___f = FILTERS ( Calls[Calls Answered In 15 Minutes] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Calls Answered In 15 Minutes] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Calls Answered In 15 Minutes], \", \" )",
              "    VAR ___x = \"Calls[Calls Answered In 15 Minutes] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Calls Answered In 3 Minutes] ), ",
              "    VAR ___f = FILTERS ( Calls[Calls Answered In 3 Minutes] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Calls Answered In 3 Minutes] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Calls Answered In 3 Minutes], \", \" )",
              "    VAR ___x = \"Calls[Calls Answered In 3 Minutes] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Calls Answered In 5 Minutes] ), ",
              "    VAR ___f = FILTERS ( Calls[Calls Answered In 5 Minutes] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Calls Answered In 5 Minutes] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Calls Answered In 5 Minutes], \", \" )",
              "    VAR ___x = \"Calls[Calls Answered In 5 Minutes] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Calls Handled] ), ",
              "    VAR ___f = FILTERS ( Calls[Calls Handled] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Calls Handled] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Calls Handled], \", \" )",
              "    VAR ___x = \"Calls[Calls Handled] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Calls Offered] ), ",
              "    VAR ___f = FILTERS ( Calls[Calls Offered] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Calls Offered] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Calls Offered], \", \" )",
              "    VAR ___x = \"Calls[Calls Offered] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Case ID] ), ",
              "    VAR ___f = FILTERS ( Calls[Case ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Case ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Case ID], \", \" )",
              "    VAR ___x = \"Calls[Case ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Case Rona] ), ",
              "    VAR ___f = FILTERS ( Calls[Case Rona] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Case Rona] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Case Rona], \", \" )",
              "    VAR ___x = \"Calls[Case Rona] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Connection ID] ), ",
              "    VAR ___f = FILTERS ( Calls[Connection ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Connection ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Connection ID], \", \" )",
              "    VAR ___x = \"Calls[Connection ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Customer ID] ), ",
              "    VAR ___f = FILTERS ( Calls[Customer ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Customer ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Customer ID], \", \" )",
              "    VAR ___x = \"Calls[Customer ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Dial Duration] ), ",
              "    VAR ___f = FILTERS ( Calls[Dial Duration] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Dial Duration] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Dial Duration], \", \" )",
              "    VAR ___x = \"Calls[Dial Duration] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Direct Calls] ), ",
              "    VAR ___f = FILTERS ( Calls[Direct Calls] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Direct Calls] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Direct Calls], \", \" )",
              "    VAR ___x = \"Calls[Direct Calls] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[DNIS] ), ",
              "    VAR ___f = FILTERS ( Calls[DNIS] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[DNIS] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[DNIS], \", \" )",
              "    VAR ___x = \"Calls[DNIS] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[DNIS Routing Modified] ), ",
              "    VAR ___f = FILTERS ( Calls[DNIS Routing Modified] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[DNIS Routing Modified] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[DNIS Routing Modified], \", \" )",
              "    VAR ___x = \"Calls[DNIS Routing Modified] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Employee Department] ), ",
              "    VAR ___f = FILTERS ( Calls[Employee Department] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Employee Department] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Employee Department], \", \" )",
              "    VAR ___x = \"Calls[Employee Department] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Employee ID] ), ",
              "    VAR ___f = FILTERS ( Calls[Employee ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Employee ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Employee ID], \", \" )",
              "    VAR ___x = \"Calls[Employee ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[GMTEndTime] ), ",
              "    VAR ___f = FILTERS ( Calls[GMTEndTime] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[GMTEndTime] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[GMTEndTime], \", \" )",
              "    VAR ___x = \"Calls[GMTEndTime] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[GMTStartTime] ), ",
              "    VAR ___f = FILTERS ( Calls[GMTStartTime] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[GMTStartTime] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[GMTStartTime], \", \" )",
              "    VAR ___x = \"Calls[GMTStartTime] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Handle Type] ), ",
              "    VAR ___f = FILTERS ( Calls[Handle Type] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Handle Type] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Handle Type], \", \" )",
              "    VAR ___x = \"Calls[Handle Type] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Hardware] ), ",
              "    VAR ___f = FILTERS ( Calls[Hardware] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Hardware] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Hardware], \", \" )",
              "    VAR ___x = \"Calls[Hardware] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Hold Time] ), ",
              "    VAR ___f = FILTERS ( Calls[Hold Time] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Hold Time] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Hold Time], \", \" )",
              "    VAR ___x = \"Calls[Hold Time] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Interaction ID] ), ",
              "    VAR ___f = FILTERS ( Calls[Interaction ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Interaction ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Interaction ID], \", \" )",
              "    VAR ___x = \"Calls[Interaction ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Interaction Resource ID] ), ",
              "    VAR ___f = FILTERS ( Calls[Interaction Resource ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Interaction Resource ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Interaction Resource ID], \", \" )",
              "    VAR ___x = \"Calls[Interaction Resource ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[InteractionType] ), ",
              "    VAR ___f = FILTERS ( Calls[InteractionType] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[InteractionType] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[InteractionType], \", \" )",
              "    VAR ___x = \"Calls[InteractionType] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Media Type] ), ",
              "    VAR ___f = FILTERS ( Calls[Media Type] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Media Type] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Media Type], \", \" )",
              "    VAR ___x = \"Calls[Media Type] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Mgr1] ), ",
              "    VAR ___f = FILTERS ( Calls[Mgr1] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Mgr1] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Mgr1], \", \" )",
              "    VAR ___x = \"Calls[Mgr1] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Missing Wrap Up] ), ",
              "    VAR ___f = FILTERS ( Calls[Missing Wrap Up] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Missing Wrap Up] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Missing Wrap Up], \", \" )",
              "    VAR ___x = \"Calls[Missing Wrap Up] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Primary Product] ), ",
              "    VAR ___f = FILTERS ( Calls[Primary Product] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Primary Product] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Primary Product], \", \" )",
              "    VAR ___x = \"Calls[Primary Product] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Primary Product Group] ), ",
              "    VAR ___f = FILTERS ( Calls[Primary Product Group] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Primary Product Group] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Primary Product Group], \", \" )",
              "    VAR ___x = \"Calls[Primary Product Group] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Product Category] ), ",
              "    VAR ___f = FILTERS ( Calls[Product Category] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Product Category] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Product Category], \", \" )",
              "    VAR ___x = \"Calls[Product Category] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Queue Name] ), ",
              "    VAR ___f = FILTERS ( Calls[Queue Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Queue Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Queue Name], \", \" )",
              "    VAR ___x = \"Calls[Queue Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[QueueNameIndex] ), ",
              "    VAR ___f = FILTERS ( Calls[QueueNameIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[QueueNameIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[QueueNameIndex], \", \" )",
              "    VAR ___x = \"Calls[QueueNameIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[RequestedVQ] ), ",
              "    VAR ___f = FILTERS ( Calls[RequestedVQ] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[RequestedVQ] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[RequestedVQ], \", \" )",
              "    VAR ___x = \"Calls[RequestedVQ] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[RequiredSkill] ), ",
              "    VAR ___f = FILTERS ( Calls[RequiredSkill] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[RequiredSkill] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[RequiredSkill], \", \" )",
              "    VAR ___x = \"Calls[RequiredSkill] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[ResourceRole] ), ",
              "    VAR ___f = FILTERS ( Calls[ResourceRole] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[ResourceRole] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[ResourceRole], \", \" )",
              "    VAR ___x = \"Calls[ResourceRole] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[ResourceType] ), ",
              "    VAR ___f = FILTERS ( Calls[ResourceType] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[ResourceType] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[ResourceType], \", \" )",
              "    VAR ___x = \"Calls[ResourceType] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[ResultReason] ), ",
              "    VAR ___f = FILTERS ( Calls[ResultReason] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[ResultReason] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[ResultReason], \", \" )",
              "    VAR ___x = \"Calls[ResultReason] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Ring Duration] ), ",
              "    VAR ___f = FILTERS ( Calls[Ring Duration] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Ring Duration] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Ring Duration], \", \" )",
              "    VAR ___x = \"Calls[Ring Duration] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Skills] ), ",
              "    VAR ___f = FILTERS ( Calls[Skills] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Skills] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Skills], \", \" )",
              "    VAR ___x = \"Calls[Skills] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Talk Time Inbound] ), ",
              "    VAR ___f = FILTERS ( Calls[Talk Time Inbound] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Talk Time Inbound] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Talk Time Inbound], \", \" )",
              "    VAR ___x = \"Calls[Talk Time Inbound] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Talk Time Internal] ), ",
              "    VAR ___f = FILTERS ( Calls[Talk Time Internal] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Talk Time Internal] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Talk Time Internal], \", \" )",
              "    VAR ___x = \"Calls[Talk Time Internal] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Talk Time Outbound] ), ",
              "    VAR ___f = FILTERS ( Calls[Talk Time Outbound] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Talk Time Outbound] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Talk Time Outbound], \", \" )",
              "    VAR ___x = \"Calls[Talk Time Outbound] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[TechnicalResult] ), ",
              "    VAR ___f = FILTERS ( Calls[TechnicalResult] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[TechnicalResult] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[TechnicalResult], \", \" )",
              "    VAR ___x = \"Calls[TechnicalResult] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Transfer Calls] ), ",
              "    VAR ___f = FILTERS ( Calls[Transfer Calls] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Transfer Calls] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Transfer Calls], \", \" )",
              "    VAR ___x = \"Calls[Transfer Calls] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[VH Success Flag] ), ",
              "    VAR ___f = FILTERS ( Calls[VH Success Flag] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[VH Success Flag] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[VH Success Flag], \", \" )",
              "    VAR ___x = \"Calls[VH Success Flag] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Wait Duration] ), ",
              "    VAR ___f = FILTERS ( Calls[Wait Duration] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Wait Duration] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Wait Duration], \", \" )",
              "    VAR ___x = \"Calls[Wait Duration] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Calls[Wait Duration (Formatted)] ), ",
              "    VAR ___f = FILTERS ( Calls[Wait Duration (Formatted)] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Calls[Wait Duration (Formatted)] )",
              "    VAR ___d = CONCATENATEX ( ___t, Calls[Wait Duration (Formatted)], \", \" )",
              "    VAR ___x = \"Calls[Wait Duration (Formatted)] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Agent] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Agent] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Agent] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Agent], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Agent] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Case Disposition] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Case Disposition] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Case Disposition] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Case Disposition], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Case Disposition] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Category Code Description] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Category Code Description] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Category Code Description] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Category Code Description], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Category Code Description] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Close 24 Hour Flag] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Close 24 Hour Flag] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Close 24 Hour Flag] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Close 24 Hour Flag], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Close 24 Hour Flag] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Closed By Department] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Closed By Department] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Closed By Department] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Closed By Department], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Closed By Department] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Closed By Employee] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Closed By Employee] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Closed By Employee] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Closed By Employee], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Closed By Employee] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Closed By ManagerLevel1] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Closed By ManagerLevel1] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Closed By ManagerLevel1] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Closed By ManagerLevel1], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Closed By ManagerLevel1] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Community Case Flag] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Community Case Flag] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Community Case Flag] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Community Case Flag], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Community Case Flag] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[CommunityCaseEligible] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[CommunityCaseEligible] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[CommunityCaseEligible] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[CommunityCaseEligible], \", \" )",
              "    VAR ___x = \"'Case Metrics'[CommunityCaseEligible] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Created By Department] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Created By Department] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Created By Department] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Created By Department], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Created By Department] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Created By Employee] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Created By Employee] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Created By Employee] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Created By Employee], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Created By Employee] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Created By ManagerLevel1] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Created By ManagerLevel1] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Created By ManagerLevel1] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Created By ManagerLevel1], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Created By ManagerLevel1] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Customer ID] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Customer ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Customer ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Customer ID], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Customer ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Department ID] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Department ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Department ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Department ID], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Department ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Dispatch Flag] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Dispatch Flag] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Dispatch Flag] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Dispatch Flag], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Dispatch Flag] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Dispensing/Infusion] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Dispensing/Infusion] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Dispensing/Infusion] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Dispensing/Infusion], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Dispensing/Infusion] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Employee ID] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Employee ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Employee ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Employee ID], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Employee ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Minutes To Close Service Request] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Minutes To Close Service Request] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Minutes To Close Service Request] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Minutes To Close Service Request], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Minutes To Close Service Request] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Mngr Level 1] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Mngr Level 1] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Mngr Level 1] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Mngr Level 1], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Mngr Level 1] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Number of Reassignments] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Number of Reassignments] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Number of Reassignments] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Number of Reassignments], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Number of Reassignments] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[PHL4] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[PHL4] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[PHL4] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[PHL4], \", \" )",
              "    VAR ___x = \"'Case Metrics'[PHL4] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[PHL5] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[PHL5] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[PHL5] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[PHL5], \", \" )",
              "    VAR ___x = \"'Case Metrics'[PHL5] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Primary Product] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Primary Product] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Primary Product] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Primary Product], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Primary Product] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Primary Product Group] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Primary Product Group] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Primary Product Group] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Primary Product Group], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Primary Product Group] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Priority Description] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Priority Description] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Priority Description] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Priority Description], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Priority Description] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Product] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Product] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Product] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Product], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Product] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Product Category] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Product Category] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Product Category] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Product Category], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Product Category] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Service Request ID] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Service Request ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Service Request ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Service Request ID], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Service Request ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Time To Assign Duration Minutes] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Time To Assign Duration Minutes] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Time To Assign Duration Minutes] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Time To Assign Duration Minutes], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Time To Assign Duration Minutes] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[Transaction Date] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[Transaction Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[Transaction Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[Transaction Date], \", \" )",
              "    VAR ___x = \"'Case Metrics'[Transaction Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Case Metrics'[TSC Complete Flag] ), ",
              "    VAR ___f = FILTERS ( 'Case Metrics'[TSC Complete Flag] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Case Metrics'[TSC Complete Flag] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Case Metrics'[TSC Complete Flag], \", \" )",
              "    VAR ___x = \"'Case Metrics'[TSC Complete Flag] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Category Code Description] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Category Code Description] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Category Code Description] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Category Code Description], \", \" )",
              "    VAR ___x = \"'Cases'[Category Code Description] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[CategoryCodeDescription] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[CategoryCodeDescription] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[CategoryCodeDescription] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[CategoryCodeDescription], \", \" )",
              "    VAR ___x = \"'Cases'[CategoryCodeDescription] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Close 24 Hour Flag] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Close 24 Hour Flag] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Close 24 Hour Flag] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Close 24 Hour Flag], \", \" )",
              "    VAR ___x = \"'Cases'[Close 24 Hour Flag] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Closed by Employee ID] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Closed by Employee ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Closed by Employee ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Closed by Employee ID], \", \" )",
              "    VAR ___x = \"'Cases'[Closed by Employee ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Community Case Eligible] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Community Case Eligible] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Community Case Eligible] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Community Case Eligible], \", \" )",
              "    VAR ___x = \"'Cases'[Community Case Eligible] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[ComplaintTypeDescription] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[ComplaintTypeDescription] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[ComplaintTypeDescription] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[ComplaintTypeDescription], \", \" )",
              "    VAR ___x = \"'Cases'[ComplaintTypeDescription] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[ContactCustomerBPartner] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[ContactCustomerBPartner] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[ContactCustomerBPartner] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[ContactCustomerBPartner], \", \" )",
              "    VAR ___x = \"'Cases'[ContactCustomerBPartner] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[CRM Description] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[CRM Description] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[CRM Description] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[CRM Description], \", \" )",
              "    VAR ___x = \"'Cases'[CRM Description] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Customer Contact B Partner] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Customer Contact B Partner] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Customer Contact B Partner] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Customer Contact B Partner], \", \" )",
              "    VAR ___x = \"'Cases'[Customer Contact B Partner] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Dispatch Flag] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Dispatch Flag] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Dispatch Flag] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Dispatch Flag], \", \" )",
              "    VAR ___x = \"'Cases'[Dispatch Flag] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Employee Closed By] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Employee Closed By] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Employee Closed By] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Employee Closed By], \", \" )",
              "    VAR ___x = \"'Cases'[Employee Closed By] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Employee Department Closed By] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Employee Department Closed By] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Employee Department Closed By] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Employee Department Closed By], \", \" )",
              "    VAR ___x = \"'Cases'[Employee Department Closed By] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Employee Department Opened By] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Employee Department Opened By] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Employee Department Opened By] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Employee Department Opened By], \", \" )",
              "    VAR ___x = \"'Cases'[Employee Department Opened By] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Employee Responsible] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Employee Responsible] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Employee Responsible] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Employee Responsible], \", \" )",
              "    VAR ___x = \"'Cases'[Employee Responsible] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[First Non Queue Owner] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[First Non Queue Owner] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[First Non Queue Owner] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[First Non Queue Owner], \", \" )",
              "    VAR ___x = \"'Cases'[First Non Queue Owner] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[First Non Queue Owner Assign Date] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[First Non Queue Owner Assign Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[First Non Queue Owner Assign Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[First Non Queue Owner Assign Date], \", \" )",
              "    VAR ___x = \"'Cases'[First Non Queue Owner Assign Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[iObject ID] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[iObject ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[iObject ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[iObject ID], \", \" )",
              "    VAR ___x = \"'Cases'[iObject ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[IObject ID No Leading Zeros] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[IObject ID No Leading Zeros] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[IObject ID No Leading Zeros] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[IObject ID No Leading Zeros], \", \" )",
              "    VAR ___x = \"'Cases'[IObject ID No Leading Zeros] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Knowledge Article ID] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Knowledge Article ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Knowledge Article ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Knowledge Article ID], \", \" )",
              "    VAR ___x = \"'Cases'[Knowledge Article ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Minutes to Close Bucket] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Minutes to Close Bucket] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Minutes to Close Bucket] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Minutes to Close Bucket], \", \" )",
              "    VAR ___x = \"'Cases'[Minutes to Close Bucket] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Minutes to Close Service Request] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Minutes to Close Service Request] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Minutes to Close Service Request] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Minutes to Close Service Request], \", \" )",
              "    VAR ___x = \"'Cases'[Minutes to Close Service Request] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Number of Reassignments] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Number of Reassignments] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Number of Reassignments] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Number of Reassignments], \", \" )",
              "    VAR ___x = \"'Cases'[Number of Reassignments] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Opened by Employee ID] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Opened by Employee ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Opened by Employee ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Opened by Employee ID], \", \" )",
              "    VAR ___x = \"'Cases'[Opened by Employee ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Original Minutes to Close Service Request] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Original Minutes to Close Service Request] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Original Minutes to Close Service Request] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Original Minutes to Close Service Request], \", \" )",
              "    VAR ___x = \"'Cases'[Original Minutes to Close Service Request] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[PHL4] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[PHL4] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[PHL4] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[PHL4], \", \" )",
              "    VAR ___x = \"'Cases'[PHL4] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[PHL5] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[PHL5] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[PHL5] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[PHL5], \", \" )",
              "    VAR ___x = \"'Cases'[PHL5] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Priority Description] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Priority Description] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Priority Description] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Priority Description], \", \" )",
              "    VAR ___x = \"'Cases'[Priority Description] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[PriorityDescription] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[PriorityDescription] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[PriorityDescription] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[PriorityDescription], \", \" )",
              "    VAR ___x = \"'Cases'[PriorityDescription] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Product Category] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Product Category] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Product Category] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Product Category], \", \" )",
              "    VAR ___x = \"'Cases'[Product Category] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Product Hierarchy Level 5] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Product Hierarchy Level 5] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Product Hierarchy Level 5] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Product Hierarchy Level 5], \", \" )",
              "    VAR ___x = \"'Cases'[Product Hierarchy Level 5] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Product Sub Category] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Product Sub Category] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Product Sub Category] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Product Sub Category], \", \" )",
              "    VAR ___x = \"'Cases'[Product Sub Category] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Self Service Flag] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Self Service Flag] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Self Service Flag] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Self Service Flag], \", \" )",
              "    VAR ___x = \"'Cases'[Self Service Flag] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Service Order Flag] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Service Order Flag] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Service Order Flag] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Service Order Flag], \", \" )",
              "    VAR ___x = \"'Cases'[Service Order Flag] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Service Request ID] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Service Request ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Service Request ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Service Request ID], \", \" )",
              "    VAR ___x = \"'Cases'[Service Request ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Service Request Start Date] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Service Request Start Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Service Request Start Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Service Request Start Date], \", \" )",
              "    VAR ___x = \"'Cases'[Service Request Start Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Ship to Customer] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Ship to Customer] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Ship to Customer] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Ship to Customer], \", \" )",
              "    VAR ___x = \"'Cases'[Ship to Customer] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[StatusDescription] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[StatusDescription] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[StatusDescription] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[StatusDescription], \", \" )",
              "    VAR ___x = \"'Cases'[StatusDescription] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[Time to Assign Duration Minutess] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[Time to Assign Duration Minutess] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[Time to Assign Duration Minutess] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[Time to Assign Duration Minutess], \", \" )",
              "    VAR ___x = \"'Cases'[Time to Assign Duration Minutess] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[TSC Closed by Date] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[TSC Closed by Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[TSC Closed by Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[TSC Closed by Date], \", \" )",
              "    VAR ___x = \"'Cases'[TSC Closed by Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[TSC Complete Flag] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[TSC Complete Flag] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[TSC Complete Flag] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[TSC Complete Flag], \", \" )",
              "    VAR ___x = \"'Cases'[TSC Complete Flag] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases'[TSCClosedByDate - Copy] ), ",
              "    VAR ___f = FILTERS ( 'Cases'[TSCClosedByDate - Copy] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases'[TSCClosedByDate - Copy] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases'[TSCClosedByDate - Copy], \", \" )",
              "    VAR ___x = \"'Cases'[TSCClosedByDate - Copy] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases Closed'[Closed By Department] ), ",
              "    VAR ___f = FILTERS ( 'Cases Closed'[Closed By Department] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases Closed'[Closed By Department] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases Closed'[Closed By Department], \", \" )",
              "    VAR ___x = \"'Cases Closed'[Closed By Department] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases Closed'[Closed By Employee] ), ",
              "    VAR ___f = FILTERS ( 'Cases Closed'[Closed By Employee] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases Closed'[Closed By Employee] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases Closed'[Closed By Employee], \", \" )",
              "    VAR ___x = \"'Cases Closed'[Closed By Employee] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases Closed'[Closed By Manager Level 1] ), ",
              "    VAR ___f = FILTERS ( 'Cases Closed'[Closed By Manager Level 1] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases Closed'[Closed By Manager Level 1] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases Closed'[Closed By Manager Level 1], \", \" )",
              "    VAR ___x = \"'Cases Closed'[Closed By Manager Level 1] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases Closed'[Service Request ID] ), ",
              "    VAR ___f = FILTERS ( 'Cases Closed'[Service Request ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases Closed'[Service Request ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases Closed'[Service Request ID], \", \" )",
              "    VAR ___x = \"'Cases Closed'[Service Request ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases Open'[Created By Department] ), ",
              "    VAR ___f = FILTERS ( 'Cases Open'[Created By Department] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases Open'[Created By Department] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases Open'[Created By Department], \", \" )",
              "    VAR ___x = \"'Cases Open'[Created By Department] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases Open'[Created By Employee] ), ",
              "    VAR ___f = FILTERS ( 'Cases Open'[Created By Employee] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases Open'[Created By Employee] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases Open'[Created By Employee], \", \" )",
              "    VAR ___x = \"'Cases Open'[Created By Employee] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases Open'[Created By Manager Level 1] ), ",
              "    VAR ___f = FILTERS ( 'Cases Open'[Created By Manager Level 1] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases Open'[Created By Manager Level 1] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases Open'[Created By Manager Level 1], \", \" )",
              "    VAR ___x = \"'Cases Open'[Created By Manager Level 1] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Cases Open'[Service Request ID] ), ",
              "    VAR ___f = FILTERS ( 'Cases Open'[Service Request ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Cases Open'[Service Request ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Cases Open'[Service Request ID], \", \" )",
              "    VAR ___x = \"'Cases Open'[Service Request ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Category Code Description'[Category Code Description] ), ",
              "    VAR ___f = FILTERS ( 'Category Code Description'[Category Code Description] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Category Code Description'[Category Code Description] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Category Code Description'[Category Code Description], \", \" )",
              "    VAR ___x = \"'Category Code Description'[Category Code Description] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Category Code Description'[Index] ), ",
              "    VAR ___f = FILTERS ( 'Category Code Description'[Index] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Category Code Description'[Index] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Category Code Description'[Index], \", \" )",
              "    VAR ___x = \"'Category Code Description'[Index] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Complaint Type Description'[Complaint Type Description] ), ",
              "    VAR ___f = FILTERS ( 'Complaint Type Description'[Complaint Type Description] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Complaint Type Description'[Complaint Type Description] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Complaint Type Description'[Complaint Type Description], \", \" )",
              "    VAR ___x = \"'Complaint Type Description'[Complaint Type Description] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Complaint Type Description'[Index] ), ",
              "    VAR ___f = FILTERS ( 'Complaint Type Description'[Index] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Complaint Type Description'[Index] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Complaint Type Description'[Index], \", \" )",
              "    VAR ___x = \"'Complaint Type Description'[Index] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Customer Contacts'[Competency] ), ",
              "    VAR ___f = FILTERS ( 'Customer Contacts'[Competency] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Customer Contacts'[Competency] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Customer Contacts'[Competency], \", \" )",
              "    VAR ___x = \"'Customer Contacts'[Competency] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Customer Contacts'[ContactBPartner] ), ",
              "    VAR ___f = FILTERS ( 'Customer Contacts'[ContactBPartner] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Customer Contacts'[ContactBPartner] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Customer Contacts'[ContactBPartner], \", \" )",
              "    VAR ___x = \"'Customer Contacts'[ContactBPartner] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Customer Contacts'[ContactCustomerBPartner] ), ",
              "    VAR ___f = FILTERS ( 'Customer Contacts'[ContactCustomerBPartner] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Customer Contacts'[ContactCustomerBPartner] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Customer Contacts'[ContactCustomerBPartner], \", \" )",
              "    VAR ___x = \"'Customer Contacts'[ContactCustomerBPartner] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Customer Contacts'[ContactName] ), ",
              "    VAR ___f = FILTERS ( 'Customer Contacts'[ContactName] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Customer Contacts'[ContactName] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Customer Contacts'[ContactName], \", \" )",
              "    VAR ___x = \"'Customer Contacts'[ContactName] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Customer Contacts'[CreatedDate] ), ",
              "    VAR ___f = FILTERS ( 'Customer Contacts'[CreatedDate] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Customer Contacts'[CreatedDate] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Customer Contacts'[CreatedDate], \", \" )",
              "    VAR ___x = \"'Customer Contacts'[CreatedDate] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Customer Contacts'[CustomerContactsIndex] ), ",
              "    VAR ___f = FILTERS ( 'Customer Contacts'[CustomerContactsIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Customer Contacts'[CustomerContactsIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Customer Contacts'[CustomerContactsIndex], \", \" )",
              "    VAR ___x = \"'Customer Contacts'[CustomerContactsIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Customer Contacts'[Department] ), ",
              "    VAR ___f = FILTERS ( 'Customer Contacts'[Department] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Customer Contacts'[Department] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Customer Contacts'[Department], \", \" )",
              "    VAR ___x = \"'Customer Contacts'[Department] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Customer Contacts'[EmailAddress] ), ",
              "    VAR ___f = FILTERS ( 'Customer Contacts'[EmailAddress] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Customer Contacts'[EmailAddress] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Customer Contacts'[EmailAddress], \", \" )",
              "    VAR ___x = \"'Customer Contacts'[EmailAddress] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Customer Contacts'[FaxNumber] ), ",
              "    VAR ___f = FILTERS ( 'Customer Contacts'[FaxNumber] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Customer Contacts'[FaxNumber] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Customer Contacts'[FaxNumber], \", \" )",
              "    VAR ___x = \"'Customer Contacts'[FaxNumber] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Customer Contacts'[FirstName] ), ",
              "    VAR ___f = FILTERS ( 'Customer Contacts'[FirstName] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Customer Contacts'[FirstName] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Customer Contacts'[FirstName], \", \" )",
              "    VAR ___x = \"'Customer Contacts'[FirstName] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Customer Contacts'[LastName] ), ",
              "    VAR ___f = FILTERS ( 'Customer Contacts'[LastName] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Customer Contacts'[LastName] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Customer Contacts'[LastName], \", \" )",
              "    VAR ___x = \"'Customer Contacts'[LastName] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Customer Contacts'[MiddleName] ), ",
              "    VAR ___f = FILTERS ( 'Customer Contacts'[MiddleName] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Customer Contacts'[MiddleName] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Customer Contacts'[MiddleName], \", \" )",
              "    VAR ___x = \"'Customer Contacts'[MiddleName] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Customer Contacts'[SourceSystem] ), ",
              "    VAR ___f = FILTERS ( 'Customer Contacts'[SourceSystem] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Customer Contacts'[SourceSystem] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Customer Contacts'[SourceSystem], \", \" )",
              "    VAR ___x = \"'Customer Contacts'[SourceSystem] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Customer Contacts'[TelePhoneNumber] ), ",
              "    VAR ___f = FILTERS ( 'Customer Contacts'[TelePhoneNumber] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Customer Contacts'[TelePhoneNumber] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Customer Contacts'[TelePhoneNumber], \", \" )",
              "    VAR ___x = \"'Customer Contacts'[TelePhoneNumber] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Customer Contacts'[Title] ), ",
              "    VAR ___f = FILTERS ( 'Customer Contacts'[Title] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Customer Contacts'[Title] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Customer Contacts'[Title], \", \" )",
              "    VAR ___x = \"'Customer Contacts'[Title] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Account Group] ), ",
              "    VAR ___f = FILTERS ( Customers[Account Group] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Account Group] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Account Group], \", \" )",
              "    VAR ___x = \"Customers[Account Group] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Account Group Name] ), ",
              "    VAR ___f = FILTERS ( Customers[Account Group Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Account Group Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Account Group Name], \", \" )",
              "    VAR ___x = \"Customers[Account Group Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Account Type] ), ",
              "    VAR ___f = FILTERS ( Customers[Account Type] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Account Type] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Account Type], \", \" )",
              "    VAR ___x = \"Customers[Account Type] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Account Type Description] ), ",
              "    VAR ___f = FILTERS ( Customers[Account Type Description] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Account Type Description] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Account Type Description], \", \" )",
              "    VAR ___x = \"Customers[Account Type Description] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Active ISMS] ), ",
              "    VAR ___f = FILTERS ( Customers[Active ISMS] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Active ISMS] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Active ISMS], \", \" )",
              "    VAR ___x = \"Customers[Active ISMS] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Active SW Maintenance] ), ",
              "    VAR ___f = FILTERS ( Customers[Active SW Maintenance] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Active SW Maintenance] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Active SW Maintenance], \", \" )",
              "    VAR ___x = \"Customers[Active SW Maintenance] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[City] ), ",
              "    VAR ___f = FILTERS ( Customers[City] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[City] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[City], \", \" )",
              "    VAR ___x = \"Customers[City] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Classification Code] ), ",
              "    VAR ___f = FILTERS ( Customers[Classification Code] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Classification Code] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Classification Code], \", \" )",
              "    VAR ___x = \"Customers[Classification Code] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Classification Description] ), ",
              "    VAR ___f = FILTERS ( Customers[Classification Description] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Classification Description] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Classification Description], \", \" )",
              "    VAR ___x = \"Customers[Classification Description] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Country] ), ",
              "    VAR ___f = FILTERS ( Customers[Country] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Country] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Country], \", \" )",
              "    VAR ___x = \"Customers[Country] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Customer ID] ), ",
              "    VAR ___f = FILTERS ( Customers[Customer ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Customer ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Customer ID], \", \" )",
              "    VAR ___x = \"Customers[Customer ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Customer ID No Leading Zero] ), ",
              "    VAR ___f = FILTERS ( Customers[Customer ID No Leading Zero] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Customer ID No Leading Zero] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Customer ID No Leading Zero], \", \" )",
              "    VAR ___x = \"Customers[Customer ID No Leading Zero] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Customer Name - Id] ), ",
              "    VAR ___f = FILTERS ( Customers[Customer Name - Id] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Customer Name - Id] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Customer Name - Id], \", \" )",
              "    VAR ___x = \"Customers[Customer Name - Id] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Customer Software Version Infusion] ), ",
              "    VAR ___f = FILTERS ( Customers[Customer Software Version Infusion] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Customer Software Version Infusion] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Customer Software Version Infusion], \", \" )",
              "    VAR ___x = \"Customers[Customer Software Version Infusion] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Deletion Flag] ), ",
              "    VAR ___f = FILTERS ( Customers[Deletion Flag] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Deletion Flag] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Deletion Flag], \", \" )",
              "    VAR ___x = \"Customers[Deletion Flag] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Enterprise Account Name] ), ",
              "    VAR ___f = FILTERS ( Customers[Enterprise Account Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Enterprise Account Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Enterprise Account Name], \", \" )",
              "    VAR ___x = \"Customers[Enterprise Account Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Enterprise Account Network] ), ",
              "    VAR ___f = FILTERS ( Customers[Enterprise Account Network] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Enterprise Account Network] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Enterprise Account Network], \", \" )",
              "    VAR ___x = \"Customers[Enterprise Account Network] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Enterprise Account Network Name] ), ",
              "    VAR ___f = FILTERS ( Customers[Enterprise Account Network Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Enterprise Account Network Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Enterprise Account Network Name], \", \" )",
              "    VAR ___x = \"Customers[Enterprise Account Network Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Enterprise Account Network Parent] ), ",
              "    VAR ___f = FILTERS ( Customers[Enterprise Account Network Parent] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Enterprise Account Network Parent] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Enterprise Account Network Parent], \", \" )",
              "    VAR ___x = \"Customers[Enterprise Account Network Parent] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Enterprise Account Network Parent Name] ), ",
              "    VAR ___f = FILTERS ( Customers[Enterprise Account Network Parent Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Enterprise Account Network Parent Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Enterprise Account Network Parent Name], \", \" )",
              "    VAR ___x = \"Customers[Enterprise Account Network Parent Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Enterprise Account Number] ), ",
              "    VAR ___f = FILTERS ( Customers[Enterprise Account Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Enterprise Account Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Enterprise Account Number], \", \" )",
              "    VAR ___x = \"Customers[Enterprise Account Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Enterprise Account Number SFID] ), ",
              "    VAR ___f = FILTERS ( Customers[Enterprise Account Number SFID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Enterprise Account Number SFID] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Enterprise Account Number SFID], \", \" )",
              "    VAR ___x = \"Customers[Enterprise Account Number SFID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[FSM Employee ID Dispensing] ), ",
              "    VAR ___f = FILTERS ( Customers[FSM Employee ID Dispensing] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[FSM Employee ID Dispensing] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[FSM Employee ID Dispensing], \", \" )",
              "    VAR ___x = \"Customers[FSM Employee ID Dispensing] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[FSM Name] ), ",
              "    VAR ___f = FILTERS ( Customers[FSM Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[FSM Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[FSM Name], \", \" )",
              "    VAR ___x = \"Customers[FSM Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Industry] ), ",
              "    VAR ___f = FILTERS ( Customers[Industry] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Industry] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Industry], \", \" )",
              "    VAR ___x = \"Customers[Industry] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Industry Code] ), ",
              "    VAR ___f = FILTERS ( Customers[Industry Code] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Industry Code] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Industry Code], \", \" )",
              "    VAR ___x = \"Customers[Industry Code] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Infusion Area Name] ), ",
              "    VAR ___f = FILTERS ( Customers[Infusion Area Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Infusion Area Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Infusion Area Name], \", \" )",
              "    VAR ___x = \"Customers[Infusion Area Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Infusion Area Number] ), ",
              "    VAR ___f = FILTERS ( Customers[Infusion Area Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Infusion Area Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Infusion Area Number], \", \" )",
              "    VAR ___x = \"Customers[Infusion Area Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Infusion Area Rep Employee ID] ), ",
              "    VAR ___f = FILTERS ( Customers[Infusion Area Rep Employee ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Infusion Area Rep Employee ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Infusion Area Rep Employee ID], \", \" )",
              "    VAR ___x = \"Customers[Infusion Area Rep Employee ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Infusion Area Rep Name] ), ",
              "    VAR ___f = FILTERS ( Customers[Infusion Area Rep Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Infusion Area Rep Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Infusion Area Rep Name], \", \" )",
              "    VAR ___x = \"Customers[Infusion Area Rep Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Infusion Region Name] ), ",
              "    VAR ___f = FILTERS ( Customers[Infusion Region Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Infusion Region Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Infusion Region Name], \", \" )",
              "    VAR ___x = \"Customers[Infusion Region Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Infusion Region Number] ), ",
              "    VAR ___f = FILTERS ( Customers[Infusion Region Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Infusion Region Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Infusion Region Number], \", \" )",
              "    VAR ___x = \"Customers[Infusion Region Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Infusion Region Rep Employee ID] ), ",
              "    VAR ___f = FILTERS ( Customers[Infusion Region Rep Employee ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Infusion Region Rep Employee ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Infusion Region Rep Employee ID], \", \" )",
              "    VAR ___x = \"Customers[Infusion Region Rep Employee ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Infusion Region Rep Name] ), ",
              "    VAR ___f = FILTERS ( Customers[Infusion Region Rep Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Infusion Region Rep Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Infusion Region Rep Name], \", \" )",
              "    VAR ___x = \"Customers[Infusion Region Rep Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Infusion Territory Name] ), ",
              "    VAR ___f = FILTERS ( Customers[Infusion Territory Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Infusion Territory Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Infusion Territory Name], \", \" )",
              "    VAR ___x = \"Customers[Infusion Territory Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Infusion Territory Number] ), ",
              "    VAR ___f = FILTERS ( Customers[Infusion Territory Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Infusion Territory Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Infusion Territory Number], \", \" )",
              "    VAR ___x = \"Customers[Infusion Territory Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Infusion Territory Rep Employee ID] ), ",
              "    VAR ___f = FILTERS ( Customers[Infusion Territory Rep Employee ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Infusion Territory Rep Employee ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Infusion Territory Rep Employee ID], \", \" )",
              "    VAR ___x = \"Customers[Infusion Territory Rep Employee ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Infusion Territory Rep Name] ), ",
              "    VAR ___f = FILTERS ( Customers[Infusion Territory Rep Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Infusion Territory Rep Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Infusion Territory Rep Name], \", \" )",
              "    VAR ___x = \"Customers[Infusion Territory Rep Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Latest Server Software Version] ), ",
              "    VAR ___f = FILTERS ( Customers[Latest Server Software Version] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Latest Server Software Version] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Latest Server Software Version], \", \" )",
              "    VAR ___x = \"Customers[Latest Server Software Version] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Name] ), ",
              "    VAR ___f = FILTERS ( Customers[Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Name], \", \" )",
              "    VAR ___x = \"Customers[Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[Server Customer] ), ",
              "    VAR ___f = FILTERS ( Customers[Server Customer] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[Server Customer] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[Server Customer], \", \" )",
              "    VAR ___x = \"Customers[Server Customer] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[State] ), ",
              "    VAR ___f = FILTERS ( Customers[State] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[State] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[State], \", \" )",
              "    VAR ___x = \"Customers[State] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[With Alaris PCU] ), ",
              "    VAR ___f = FILTERS ( Customers[With Alaris PCU] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[With Alaris PCU] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[With Alaris PCU], \", \" )",
              "    VAR ___x = \"Customers[With Alaris PCU] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[ZSC3 Contract End Date] ), ",
              "    VAR ___f = FILTERS ( Customers[ZSC3 Contract End Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[ZSC3 Contract End Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[ZSC3 Contract End Date], \", \" )",
              "    VAR ___x = \"Customers[ZSC3 Contract End Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customers[ZSC3 Contract Start Date] ), ",
              "    VAR ___f = FILTERS ( Customers[ZSC3 Contract Start Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customers[ZSC3 Contract Start Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customers[ZSC3 Contract Start Date], \", \" )",
              "    VAR ___x = \"Customers[ZSC3 Contract Start Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Departments[DepartmentID] ), ",
              "    VAR ___f = FILTERS ( Departments[DepartmentID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Departments[DepartmentID] )",
              "    VAR ___d = CONCATENATEX ( ___t, Departments[DepartmentID], \", \" )",
              "    VAR ___x = \"Departments[DepartmentID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Departments[Employee Department] ), ",
              "    VAR ___f = FILTERS ( Departments[Employee Department] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Departments[Employee Department] )",
              "    VAR ___d = CONCATENATEX ( ___t, Departments[Employee Department], \", \" )",
              "    VAR ___x = \"Departments[Employee Department] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Departments[Employee Org Description] ), ",
              "    VAR ___f = FILTERS ( Departments[Employee Org Description] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Departments[Employee Org Description] )",
              "    VAR ___d = CONCATENATEX ( ___t, Departments[Employee Org Description], \", \" )",
              "    VAR ___x = \"Departments[Employee Org Description] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_aht_01_primaryproductgroup[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( dl_aht_01_primaryproductgroup[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_aht_01_primaryproductgroup[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_aht_01_primaryproductgroup[CategoryValue], \", \" )",
              "    VAR ___x = \"dl_aht_01_primaryproductgroup[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_aht_01_primaryproductgroup[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( dl_aht_01_primaryproductgroup[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_aht_01_primaryproductgroup[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_aht_01_primaryproductgroup[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"dl_aht_01_primaryproductgroup[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_aht_01_primaryproductgroup[Field] ), ",
              "    VAR ___f = FILTERS ( dl_aht_01_primaryproductgroup[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_aht_01_primaryproductgroup[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_aht_01_primaryproductgroup[Field], \", \" )",
              "    VAR ___x = \"dl_aht_01_primaryproductgroup[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_aht_01_primaryproductgroup[Sort] ), ",
              "    VAR ___f = FILTERS ( dl_aht_01_primaryproductgroup[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_aht_01_primaryproductgroup[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_aht_01_primaryproductgroup[Sort], \", \" )",
              "    VAR ___x = \"dl_aht_01_primaryproductgroup[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_aht_02_primaryproduct[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( dl_aht_02_primaryproduct[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_aht_02_primaryproduct[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_aht_02_primaryproduct[CategoryValue], \", \" )",
              "    VAR ___x = \"dl_aht_02_primaryproduct[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_aht_02_primaryproduct[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( dl_aht_02_primaryproduct[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_aht_02_primaryproduct[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_aht_02_primaryproduct[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"dl_aht_02_primaryproduct[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_aht_02_primaryproduct[Field] ), ",
              "    VAR ___f = FILTERS ( dl_aht_02_primaryproduct[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_aht_02_primaryproduct[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_aht_02_primaryproduct[Field], \", \" )",
              "    VAR ___x = \"dl_aht_02_primaryproduct[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_aht_02_primaryproduct[Sort] ), ",
              "    VAR ___f = FILTERS ( dl_aht_02_primaryproduct[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_aht_02_primaryproduct[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_aht_02_primaryproduct[Sort], \", \" )",
              "    VAR ___x = \"dl_aht_02_primaryproduct[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_00_queuename[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( dl_calls_00_queuename[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_00_queuename[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_00_queuename[CategoryValue], \", \" )",
              "    VAR ___x = \"dl_calls_00_queuename[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_00_queuename[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( dl_calls_00_queuename[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_00_queuename[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_00_queuename[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"dl_calls_00_queuename[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_00_queuename[Field] ), ",
              "    VAR ___f = FILTERS ( dl_calls_00_queuename[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_00_queuename[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_00_queuename[Field], \", \" )",
              "    VAR ___x = \"dl_calls_00_queuename[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_00_queuename[Sort] ), ",
              "    VAR ___f = FILTERS ( dl_calls_00_queuename[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_00_queuename[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_00_queuename[Sort], \", \" )",
              "    VAR ___x = \"dl_calls_00_queuename[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_01_productcategory[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( dl_calls_01_productcategory[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_01_productcategory[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_01_productcategory[CategoryValue], \", \" )",
              "    VAR ___x = \"dl_calls_01_productcategory[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_01_productcategory[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( dl_calls_01_productcategory[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_01_productcategory[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_01_productcategory[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"dl_calls_01_productcategory[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_01_productcategory[Field] ), ",
              "    VAR ___f = FILTERS ( dl_calls_01_productcategory[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_01_productcategory[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_01_productcategory[Field], \", \" )",
              "    VAR ___x = \"dl_calls_01_productcategory[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_01_productcategory[Sort] ), ",
              "    VAR ___f = FILTERS ( dl_calls_01_productcategory[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_01_productcategory[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_01_productcategory[Sort], \", \" )",
              "    VAR ___x = \"dl_calls_01_productcategory[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_02_skill[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( dl_calls_02_skill[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_02_skill[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_02_skill[CategoryValue], \", \" )",
              "    VAR ___x = \"dl_calls_02_skill[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_02_skill[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( dl_calls_02_skill[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_02_skill[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_02_skill[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"dl_calls_02_skill[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_02_skill[Filed] ), ",
              "    VAR ___f = FILTERS ( dl_calls_02_skill[Filed] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_02_skill[Filed] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_02_skill[Filed], \", \" )",
              "    VAR ___x = \"dl_calls_02_skill[Filed] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_02_skill[Sort] ), ",
              "    VAR ___f = FILTERS ( dl_calls_02_skill[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_02_skill[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_02_skill[Sort], \", \" )",
              "    VAR ___x = \"dl_calls_02_skill[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_03_mgr1[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( dl_calls_03_mgr1[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_03_mgr1[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_03_mgr1[CategoryValue], \", \" )",
              "    VAR ___x = \"dl_calls_03_mgr1[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_03_mgr1[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( dl_calls_03_mgr1[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_03_mgr1[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_03_mgr1[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"dl_calls_03_mgr1[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_03_mgr1[Field] ), ",
              "    VAR ___f = FILTERS ( dl_calls_03_mgr1[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_03_mgr1[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_03_mgr1[Field], \", \" )",
              "    VAR ___x = \"dl_calls_03_mgr1[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_03_mgr1[Sort] ), ",
              "    VAR ___f = FILTERS ( dl_calls_03_mgr1[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_03_mgr1[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_03_mgr1[Sort], \", \" )",
              "    VAR ___x = \"dl_calls_03_mgr1[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_04_agent[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( dl_calls_04_agent[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_04_agent[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_04_agent[CategoryValue], \", \" )",
              "    VAR ___x = \"dl_calls_04_agent[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_04_agent[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( dl_calls_04_agent[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_04_agent[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_04_agent[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"dl_calls_04_agent[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_04_agent[Field] ), ",
              "    VAR ___f = FILTERS ( dl_calls_04_agent[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_04_agent[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_04_agent[Field], \", \" )",
              "    VAR ___x = \"dl_calls_04_agent[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_calls_04_agent[Sort] ), ",
              "    VAR ___f = FILTERS ( dl_calls_04_agent[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_calls_04_agent[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_calls_04_agent[Sort], \", \" )",
              "    VAR ___x = \"dl_calls_04_agent[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_01_productcategory[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( dl_cases_01_productcategory[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_01_productcategory[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_01_productcategory[CategoryValue], \", \" )",
              "    VAR ___x = \"dl_cases_01_productcategory[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_01_productcategory[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( dl_cases_01_productcategory[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_01_productcategory[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_01_productcategory[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"dl_cases_01_productcategory[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_01_productcategory[Field] ), ",
              "    VAR ___f = FILTERS ( dl_cases_01_productcategory[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_01_productcategory[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_01_productcategory[Field], \", \" )",
              "    VAR ___x = \"dl_cases_01_productcategory[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_01_productcategory[Sort] ), ",
              "    VAR ___f = FILTERS ( dl_cases_01_productcategory[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_01_productcategory[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_01_productcategory[Sort], \", \" )",
              "    VAR ___x = \"dl_cases_01_productcategory[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_02_category[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( dl_cases_02_category[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_02_category[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_02_category[CategoryValue], \", \" )",
              "    VAR ___x = \"dl_cases_02_category[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_02_category[CategroyValueIndex] ), ",
              "    VAR ___f = FILTERS ( dl_cases_02_category[CategroyValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_02_category[CategroyValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_02_category[CategroyValueIndex], \", \" )",
              "    VAR ___x = \"dl_cases_02_category[CategroyValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_02_category[Field] ), ",
              "    VAR ___f = FILTERS ( dl_cases_02_category[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_02_category[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_02_category[Field], \", \" )",
              "    VAR ___x = \"dl_cases_02_category[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_02_category[Sort] ), ",
              "    VAR ___f = FILTERS ( dl_cases_02_category[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_02_category[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_02_category[Sort], \", \" )",
              "    VAR ___x = \"dl_cases_02_category[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_03_priority[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( dl_cases_03_priority[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_03_priority[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_03_priority[CategoryValue], \", \" )",
              "    VAR ___x = \"dl_cases_03_priority[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_03_priority[CategroyValueIndex] ), ",
              "    VAR ___f = FILTERS ( dl_cases_03_priority[CategroyValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_03_priority[CategroyValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_03_priority[CategroyValueIndex], \", \" )",
              "    VAR ___x = \"dl_cases_03_priority[CategroyValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_03_priority[Field] ), ",
              "    VAR ___f = FILTERS ( dl_cases_03_priority[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_03_priority[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_03_priority[Field], \", \" )",
              "    VAR ___x = \"dl_cases_03_priority[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_03_priority[Sort] ), ",
              "    VAR ___f = FILTERS ( dl_cases_03_priority[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_03_priority[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_03_priority[Sort], \", \" )",
              "    VAR ___x = \"dl_cases_03_priority[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_04_community[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( dl_cases_04_community[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_04_community[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_04_community[CategoryValue], \", \" )",
              "    VAR ___x = \"dl_cases_04_community[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_04_community[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( dl_cases_04_community[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_04_community[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_04_community[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"dl_cases_04_community[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_04_community[Field] ), ",
              "    VAR ___f = FILTERS ( dl_cases_04_community[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_04_community[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_04_community[Field], \", \" )",
              "    VAR ___x = \"dl_cases_04_community[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_04_community[Sort] ), ",
              "    VAR ___f = FILTERS ( dl_cases_04_community[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_04_community[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_04_community[Sort], \", \" )",
              "    VAR ___x = \"dl_cases_04_community[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_05_phl4[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( dl_cases_05_phl4[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_05_phl4[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_05_phl4[CategoryValue], \", \" )",
              "    VAR ___x = \"dl_cases_05_phl4[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_05_phl4[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( dl_cases_05_phl4[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_05_phl4[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_05_phl4[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"dl_cases_05_phl4[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_05_phl4[Field] ), ",
              "    VAR ___f = FILTERS ( dl_cases_05_phl4[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_05_phl4[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_05_phl4[Field], \", \" )",
              "    VAR ___x = \"dl_cases_05_phl4[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_05_phl4[Sort] ), ",
              "    VAR ___f = FILTERS ( dl_cases_05_phl4[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_05_phl4[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_05_phl4[Sort], \", \" )",
              "    VAR ___x = \"dl_cases_05_phl4[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'dl_cases_05_phl4*'[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( 'dl_cases_05_phl4*'[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'dl_cases_05_phl4*'[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'dl_cases_05_phl4*'[CategoryValue], \", \" )",
              "    VAR ___x = \"'dl_cases_05_phl4*'[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'dl_cases_05_phl4*'[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( 'dl_cases_05_phl4*'[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'dl_cases_05_phl4*'[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'dl_cases_05_phl4*'[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"'dl_cases_05_phl4*'[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'dl_cases_05_phl4*'[Field] ), ",
              "    VAR ___f = FILTERS ( 'dl_cases_05_phl4*'[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'dl_cases_05_phl4*'[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'dl_cases_05_phl4*'[Field], \", \" )",
              "    VAR ___x = \"'dl_cases_05_phl4*'[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'dl_cases_05_phl4*'[Sort] ), ",
              "    VAR ___f = FILTERS ( 'dl_cases_05_phl4*'[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'dl_cases_05_phl4*'[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'dl_cases_05_phl4*'[Sort], \", \" )",
              "    VAR ___x = \"'dl_cases_05_phl4*'[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_05_phl4_NULLs[Value1] ), ",
              "    VAR ___f = FILTERS ( dl_cases_05_phl4_NULLs[Value1] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_05_phl4_NULLs[Value1] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_05_phl4_NULLs[Value1], \", \" )",
              "    VAR ___x = \"dl_cases_05_phl4_NULLs[Value1] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_05_phl4_NULLs[Value2] ), ",
              "    VAR ___f = FILTERS ( dl_cases_05_phl4_NULLs[Value2] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_05_phl4_NULLs[Value2] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_05_phl4_NULLs[Value2], \", \" )",
              "    VAR ___x = \"dl_cases_05_phl4_NULLs[Value2] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_05_phl4_NULLs[Value3] ), ",
              "    VAR ___f = FILTERS ( dl_cases_05_phl4_NULLs[Value3] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_05_phl4_NULLs[Value3] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_05_phl4_NULLs[Value3], \", \" )",
              "    VAR ___x = \"dl_cases_05_phl4_NULLs[Value3] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_05_phl4_NULLs[Value4] ), ",
              "    VAR ___f = FILTERS ( dl_cases_05_phl4_NULLs[Value4] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_05_phl4_NULLs[Value4] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_05_phl4_NULLs[Value4], \", \" )",
              "    VAR ___x = \"dl_cases_05_phl4_NULLs[Value4] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_06_phl5[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( dl_cases_06_phl5[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_06_phl5[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_06_phl5[CategoryValue], \", \" )",
              "    VAR ___x = \"dl_cases_06_phl5[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_06_phl5[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( dl_cases_06_phl5[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_06_phl5[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_06_phl5[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"dl_cases_06_phl5[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_06_phl5[Field] ), ",
              "    VAR ___f = FILTERS ( dl_cases_06_phl5[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_06_phl5[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_06_phl5[Field], \", \" )",
              "    VAR ___x = \"dl_cases_06_phl5[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_06_phl5[Sort] ), ",
              "    VAR ___f = FILTERS ( dl_cases_06_phl5[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_06_phl5[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_06_phl5[Sort], \", \" )",
              "    VAR ___x = \"dl_cases_06_phl5[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'dl_cases_06_phl5*'[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( 'dl_cases_06_phl5*'[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'dl_cases_06_phl5*'[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'dl_cases_06_phl5*'[CategoryValue], \", \" )",
              "    VAR ___x = \"'dl_cases_06_phl5*'[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'dl_cases_06_phl5*'[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( 'dl_cases_06_phl5*'[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'dl_cases_06_phl5*'[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'dl_cases_06_phl5*'[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"'dl_cases_06_phl5*'[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'dl_cases_06_phl5*'[Field] ), ",
              "    VAR ___f = FILTERS ( 'dl_cases_06_phl5*'[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'dl_cases_06_phl5*'[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'dl_cases_06_phl5*'[Field], \", \" )",
              "    VAR ___x = \"'dl_cases_06_phl5*'[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'dl_cases_06_phl5*'[Sort] ), ",
              "    VAR ___f = FILTERS ( 'dl_cases_06_phl5*'[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'dl_cases_06_phl5*'[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'dl_cases_06_phl5*'[Sort], \", \" )",
              "    VAR ___x = \"'dl_cases_06_phl5*'[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_06_phl5_NULLs[Value1] ), ",
              "    VAR ___f = FILTERS ( dl_cases_06_phl5_NULLs[Value1] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_06_phl5_NULLs[Value1] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_06_phl5_NULLs[Value1], \", \" )",
              "    VAR ___x = \"dl_cases_06_phl5_NULLs[Value1] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_06_phl5_NULLs[Value2] ), ",
              "    VAR ___f = FILTERS ( dl_cases_06_phl5_NULLs[Value2] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_06_phl5_NULLs[Value2] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_06_phl5_NULLs[Value2], \", \" )",
              "    VAR ___x = \"dl_cases_06_phl5_NULLs[Value2] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_06_phl5_NULLs[Value3] ), ",
              "    VAR ___f = FILTERS ( dl_cases_06_phl5_NULLs[Value3] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_06_phl5_NULLs[Value3] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_06_phl5_NULLs[Value3], \", \" )",
              "    VAR ___x = \"dl_cases_06_phl5_NULLs[Value3] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_06_phl5_NULLs[Value4] ), ",
              "    VAR ___f = FILTERS ( dl_cases_06_phl5_NULLs[Value4] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_06_phl5_NULLs[Value4] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_06_phl5_NULLs[Value4], \", \" )",
              "    VAR ___x = \"dl_cases_06_phl5_NULLs[Value4] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_07_mgr1[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( dl_cases_07_mgr1[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_07_mgr1[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_07_mgr1[CategoryValue], \", \" )",
              "    VAR ___x = \"dl_cases_07_mgr1[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_07_mgr1[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( dl_cases_07_mgr1[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_07_mgr1[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_07_mgr1[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"dl_cases_07_mgr1[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_07_mgr1[Field] ), ",
              "    VAR ___f = FILTERS ( dl_cases_07_mgr1[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_07_mgr1[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_07_mgr1[Field], \", \" )",
              "    VAR ___x = \"dl_cases_07_mgr1[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_07_mgr1[Sort] ), ",
              "    VAR ___f = FILTERS ( dl_cases_07_mgr1[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_07_mgr1[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_07_mgr1[Sort], \", \" )",
              "    VAR ___x = \"dl_cases_07_mgr1[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'dl_cases_07_mgr1*'[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( 'dl_cases_07_mgr1*'[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'dl_cases_07_mgr1*'[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'dl_cases_07_mgr1*'[CategoryValue], \", \" )",
              "    VAR ___x = \"'dl_cases_07_mgr1*'[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'dl_cases_07_mgr1*'[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( 'dl_cases_07_mgr1*'[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'dl_cases_07_mgr1*'[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'dl_cases_07_mgr1*'[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"'dl_cases_07_mgr1*'[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'dl_cases_07_mgr1*'[Field] ), ",
              "    VAR ___f = FILTERS ( 'dl_cases_07_mgr1*'[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'dl_cases_07_mgr1*'[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'dl_cases_07_mgr1*'[Field], \", \" )",
              "    VAR ___x = \"'dl_cases_07_mgr1*'[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'dl_cases_07_mgr1*'[Sort] ), ",
              "    VAR ___f = FILTERS ( 'dl_cases_07_mgr1*'[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'dl_cases_07_mgr1*'[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'dl_cases_07_mgr1*'[Sort], \", \" )",
              "    VAR ___x = \"'dl_cases_07_mgr1*'[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_07_mgr1_NULLs[Value1] ), ",
              "    VAR ___f = FILTERS ( dl_cases_07_mgr1_NULLs[Value1] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_07_mgr1_NULLs[Value1] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_07_mgr1_NULLs[Value1], \", \" )",
              "    VAR ___x = \"dl_cases_07_mgr1_NULLs[Value1] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_07_mgr1_NULLs[Value2] ), ",
              "    VAR ___f = FILTERS ( dl_cases_07_mgr1_NULLs[Value2] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_07_mgr1_NULLs[Value2] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_07_mgr1_NULLs[Value2], \", \" )",
              "    VAR ___x = \"dl_cases_07_mgr1_NULLs[Value2] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_07_mgr1_NULLs[Value3] ), ",
              "    VAR ___f = FILTERS ( dl_cases_07_mgr1_NULLs[Value3] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_07_mgr1_NULLs[Value3] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_07_mgr1_NULLs[Value3], \", \" )",
              "    VAR ___x = \"dl_cases_07_mgr1_NULLs[Value3] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_07_mgr1_NULLs[Value4] ), ",
              "    VAR ___f = FILTERS ( dl_cases_07_mgr1_NULLs[Value4] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_07_mgr1_NULLs[Value4] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_07_mgr1_NULLs[Value4], \", \" )",
              "    VAR ___x = \"dl_cases_07_mgr1_NULLs[Value4] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_08_agent[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( dl_cases_08_agent[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_08_agent[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_08_agent[CategoryValue], \", \" )",
              "    VAR ___x = \"dl_cases_08_agent[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_08_agent[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( dl_cases_08_agent[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_08_agent[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_08_agent[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"dl_cases_08_agent[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_08_agent[Field] ), ",
              "    VAR ___f = FILTERS ( dl_cases_08_agent[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_08_agent[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_08_agent[Field], \", \" )",
              "    VAR ___x = \"dl_cases_08_agent[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_08_agent[Sort] ), ",
              "    VAR ___f = FILTERS ( dl_cases_08_agent[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_08_agent[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_08_agent[Sort], \", \" )",
              "    VAR ___x = \"dl_cases_08_agent[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'dl_cases_08_agent*'[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( 'dl_cases_08_agent*'[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'dl_cases_08_agent*'[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'dl_cases_08_agent*'[CategoryValue], \", \" )",
              "    VAR ___x = \"'dl_cases_08_agent*'[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'dl_cases_08_agent*'[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( 'dl_cases_08_agent*'[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'dl_cases_08_agent*'[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'dl_cases_08_agent*'[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"'dl_cases_08_agent*'[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'dl_cases_08_agent*'[Field] ), ",
              "    VAR ___f = FILTERS ( 'dl_cases_08_agent*'[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'dl_cases_08_agent*'[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'dl_cases_08_agent*'[Field], \", \" )",
              "    VAR ___x = \"'dl_cases_08_agent*'[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'dl_cases_08_agent*'[Sort] ), ",
              "    VAR ___f = FILTERS ( 'dl_cases_08_agent*'[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'dl_cases_08_agent*'[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'dl_cases_08_agent*'[Sort], \", \" )",
              "    VAR ___x = \"'dl_cases_08_agent*'[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_08_agent_NULLs[Value1] ), ",
              "    VAR ___f = FILTERS ( dl_cases_08_agent_NULLs[Value1] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_08_agent_NULLs[Value1] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_08_agent_NULLs[Value1], \", \" )",
              "    VAR ___x = \"dl_cases_08_agent_NULLs[Value1] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_08_agent_NULLs[Value2] ), ",
              "    VAR ___f = FILTERS ( dl_cases_08_agent_NULLs[Value2] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_08_agent_NULLs[Value2] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_08_agent_NULLs[Value2], \", \" )",
              "    VAR ___x = \"dl_cases_08_agent_NULLs[Value2] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_08_agent_NULLs[Value3] ), ",
              "    VAR ___f = FILTERS ( dl_cases_08_agent_NULLs[Value3] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_08_agent_NULLs[Value3] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_08_agent_NULLs[Value3], \", \" )",
              "    VAR ___x = \"dl_cases_08_agent_NULLs[Value3] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( dl_cases_08_agent_NULLs[Value4] ), ",
              "    VAR ___f = FILTERS ( dl_cases_08_agent_NULLs[Value4] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, dl_cases_08_agent_NULLs[Value4] )",
              "    VAR ___d = CONCATENATEX ( ___t, dl_cases_08_agent_NULLs[Value4], \", \" )",
              "    VAR ___x = \"dl_cases_08_agent_NULLs[Value4] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DNIS[DNIS] ), ",
              "    VAR ___f = FILTERS ( DNIS[DNIS] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DNIS[DNIS] )",
              "    VAR ___d = CONCATENATEX ( ___t, DNIS[DNIS], \", \" )",
              "    VAR ___x = \"DNIS[DNIS] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DNIS[Index] ), ",
              "    VAR ___f = FILTERS ( DNIS[Index] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DNIS[Index] )",
              "    VAR ___d = CONCATENATEX ( ___t, DNIS[Index], \", \" )",
              "    VAR ___x = \"DNIS[Index] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendAgentMetricsbyDay[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendAgentMetricsbyDay[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendAgentMetricsbyDay[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendAgentMetricsbyDay[CategoryValue], \", \" )",
              "    VAR ___x = \"DynamicLegendAgentMetricsbyDay[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendAgentMetricsbyDay[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendAgentMetricsbyDay[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendAgentMetricsbyDay[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendAgentMetricsbyDay[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"DynamicLegendAgentMetricsbyDay[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendAgentMetricsbyDay[Field] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendAgentMetricsbyDay[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendAgentMetricsbyDay[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendAgentMetricsbyDay[Field], \", \" )",
              "    VAR ___x = \"DynamicLegendAgentMetricsbyDay[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendAgentMetricsbyDay[Sort] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendAgentMetricsbyDay[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendAgentMetricsbyDay[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendAgentMetricsbyDay[Sort], \", \" )",
              "    VAR ___x = \"DynamicLegendAgentMetricsbyDay[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendCalls[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendCalls[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendCalls[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendCalls[CategoryValue], \", \" )",
              "    VAR ___x = \"DynamicLegendCalls[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendCalls[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendCalls[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendCalls[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendCalls[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"DynamicLegendCalls[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendCalls[Field] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendCalls[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendCalls[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendCalls[Field], \", \" )",
              "    VAR ___x = \"DynamicLegendCalls[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendCalls[Sort] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendCalls[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendCalls[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendCalls[Sort], \", \" )",
              "    VAR ___x = \"DynamicLegendCalls[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendCallStats[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendCallStats[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendCallStats[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendCallStats[CategoryValue], \", \" )",
              "    VAR ___x = \"DynamicLegendCallStats[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendCallStats[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendCallStats[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendCallStats[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendCallStats[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"DynamicLegendCallStats[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendCallStats[Field] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendCallStats[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendCallStats[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendCallStats[Field], \", \" )",
              "    VAR ___x = \"DynamicLegendCallStats[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendCallStats[Sort] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendCallStats[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendCallStats[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendCallStats[Sort], \", \" )",
              "    VAR ___x = \"DynamicLegendCallStats[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendCases[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendCases[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendCases[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendCases[CategoryValue], \", \" )",
              "    VAR ___x = \"DynamicLegendCases[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendCases[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendCases[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendCases[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendCases[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"DynamicLegendCases[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendCases[Field] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendCases[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendCases[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendCases[Field], \", \" )",
              "    VAR ___x = \"DynamicLegendCases[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendCases[Sort] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendCases[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendCases[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendCases[Sort], \", \" )",
              "    VAR ___x = \"DynamicLegendCases[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendCommunityCases[CategoryValue] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendCommunityCases[CategoryValue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendCommunityCases[CategoryValue] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendCommunityCases[CategoryValue], \", \" )",
              "    VAR ___x = \"DynamicLegendCommunityCases[CategoryValue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendCommunityCases[CategoryValueIndex] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendCommunityCases[CategoryValueIndex] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendCommunityCases[CategoryValueIndex] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendCommunityCases[CategoryValueIndex], \", \" )",
              "    VAR ___x = \"DynamicLegendCommunityCases[CategoryValueIndex] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendCommunityCases[Field] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendCommunityCases[Field] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendCommunityCases[Field] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendCommunityCases[Field], \", \" )",
              "    VAR ___x = \"DynamicLegendCommunityCases[Field] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DynamicLegendCommunityCases[Sort] ), ",
              "    VAR ___f = FILTERS ( DynamicLegendCommunityCases[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DynamicLegendCommunityCases[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, DynamicLegendCommunityCases[Sort], \", \" )",
              "    VAR ___x = \"DynamicLegendCommunityCases[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Employee[Agent (EmployeeID)] ), ",
              "    VAR ___f = FILTERS ( Employee[Agent (EmployeeID)] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Employee[Agent (EmployeeID)] )",
              "    VAR ___d = CONCATENATEX ( ___t, Employee[Agent (EmployeeID)], \", \" )",
              "    VAR ___x = \"Employee[Agent (EmployeeID)] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Employee[Business Site Name] ), ",
              "    VAR ___f = FILTERS ( Employee[Business Site Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Employee[Business Site Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, Employee[Business Site Name], \", \" )",
              "    VAR ___x = \"Employee[Business Site Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Employee[Display Name] ), ",
              "    VAR ___f = FILTERS ( Employee[Display Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Employee[Display Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, Employee[Display Name], \", \" )",
              "    VAR ___x = \"Employee[Display Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Employee[Employee ID] ), ",
              "    VAR ___f = FILTERS ( Employee[Employee ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Employee[Employee ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, Employee[Employee ID], \", \" )",
              "    VAR ___x = \"Employee[Employee ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Employee[Employee Status] ), ",
              "    VAR ___f = FILTERS ( Employee[Employee Status] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Employee[Employee Status] )",
              "    VAR ___d = CONCATENATEX ( ___t, Employee[Employee Status], \", \" )",
              "    VAR ___x = \"Employee[Employee Status] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Employee[EmployeeIdLatest] ), ",
              "    VAR ___f = FILTERS ( Employee[EmployeeIdLatest] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Employee[EmployeeIdLatest] )",
              "    VAR ___d = CONCATENATEX ( ___t, Employee[EmployeeIdLatest], \", \" )",
              "    VAR ___x = \"Employee[EmployeeIdLatest] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Employee[Manager Level 1] ), ",
              "    VAR ___f = FILTERS ( Employee[Manager Level 1] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Employee[Manager Level 1] )",
              "    VAR ___d = CONCATENATEX ( ___t, Employee[Manager Level 1], \", \" )",
              "    VAR ___x = \"Employee[Manager Level 1] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Employee[Manager Level 2] ), ",
              "    VAR ___f = FILTERS ( Employee[Manager Level 2] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Employee[Manager Level 2] )",
              "    VAR ___d = CONCATENATEX ( ___t, Employee[Manager Level 2], \", \" )",
              "    VAR ___x = \"Employee[Manager Level 2] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Employee[Manager Level 3] ), ",
              "    VAR ___f = FILTERS ( Employee[Manager Level 3] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Employee[Manager Level 3] )",
              "    VAR ___d = CONCATENATEX ( ___t, Employee[Manager Level 3], \", \" )",
              "    VAR ___x = \"Employee[Manager Level 3] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Employee[Manager Level 4] ), ",
              "    VAR ___f = FILTERS ( Employee[Manager Level 4] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Employee[Manager Level 4] )",
              "    VAR ___d = CONCATENATEX ( ___t, Employee[Manager Level 4], \", \" )",
              "    VAR ___x = \"Employee[Manager Level 4] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Employee[Mgr1] ), ",
              "    VAR ___f = FILTERS ( Employee[Mgr1] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Employee[Mgr1] )",
              "    VAR ___d = CONCATENATEX ( ___t, Employee[Mgr1], \", \" )",
              "    VAR ___x = \"Employee[Mgr1] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Employee[Org Unit] ), ",
              "    VAR ___f = FILTERS ( Employee[Org Unit] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Employee[Org Unit] )",
              "    VAR ___d = CONCATENATEX ( ___t, Employee[Org Unit], \", \" )",
              "    VAR ___x = \"Employee[Org Unit] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Employee Site'[BusinessSiteName] ), ",
              "    VAR ___f = FILTERS ( 'Employee Site'[BusinessSiteName] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Employee Site'[BusinessSiteName] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Employee Site'[BusinessSiteName], \", \" )",
              "    VAR ___x = \"'Employee Site'[BusinessSiteName] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Employee Site'[Employee Site] ), ",
              "    VAR ___f = FILTERS ( 'Employee Site'[Employee Site] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Employee Site'[Employee Site] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Employee Site'[Employee Site], \", \" )",
              "    VAR ___x = \"'Employee Site'[Employee Site] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Handle Type'[HandleType] ), ",
              "    VAR ___f = FILTERS ( 'Handle Type'[HandleType] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Handle Type'[HandleType] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Handle Type'[HandleType], \", \" )",
              "    VAR ___x = \"'Handle Type'[HandleType] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Handle Type'[Index] ), ",
              "    VAR ___f = FILTERS ( 'Handle Type'[Index] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Handle Type'[Index] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Handle Type'[Index], \", \" )",
              "    VAR ___x = \"'Handle Type'[Index] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( IBase[Destroyed Date] ), ",
              "    VAR ___f = FILTERS ( IBase[Destroyed Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, IBase[Destroyed Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, IBase[Destroyed Date], \", \" )",
              "    VAR ___x = \"IBase[Destroyed Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( IBase[In Transit Date] ), ",
              "    VAR ___f = FILTERS ( IBase[In Transit Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, IBase[In Transit Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, IBase[In Transit Date], \", \" )",
              "    VAR ___x = \"IBase[In Transit Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( IBase[Iobject Id No Leading Zero] ), ",
              "    VAR ___f = FILTERS ( IBase[Iobject Id No Leading Zero] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, IBase[Iobject Id No Leading Zero] )",
              "    VAR ___d = CONCATENATEX ( ___t, IBase[Iobject Id No Leading Zero], \", \" )",
              "    VAR ___x = \"IBase[Iobject Id No Leading Zero] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( IBase[IObject ID No Leading Zeros] ), ",
              "    VAR ___f = FILTERS ( IBase[IObject ID No Leading Zeros] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, IBase[IObject ID No Leading Zeros] )",
              "    VAR ___d = CONCATENATEX ( ___t, IBase[IObject ID No Leading Zeros], \", \" )",
              "    VAR ___x = \"IBase[IObject ID No Leading Zeros] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( IBase[Live Date] ), ",
              "    VAR ___f = FILTERS ( IBase[Live Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, IBase[Live Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, IBase[Live Date], \", \" )",
              "    VAR ___x = \"IBase[Live Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( IBase[Location] ), ",
              "    VAR ___f = FILTERS ( IBase[Location] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, IBase[Location] )",
              "    VAR ___d = CONCATENATEX ( ___t, IBase[Location], \", \" )",
              "    VAR ___x = \"IBase[Location] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( IBase[Pending Return Date] ), ",
              "    VAR ___f = FILTERS ( IBase[Pending Return Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, IBase[Pending Return Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, IBase[Pending Return Date], \", \" )",
              "    VAR ___x = \"IBase[Pending Return Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( IBase[Reference Product No Leading Zero] ), ",
              "    VAR ___f = FILTERS ( IBase[Reference Product No Leading Zero] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, IBase[Reference Product No Leading Zero] )",
              "    VAR ___d = CONCATENATEX ( ___t, IBase[Reference Product No Leading Zero], \", \" )",
              "    VAR ___x = \"IBase[Reference Product No Leading Zero] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( IBase[Serial Number No Leading Zero] ), ",
              "    VAR ___f = FILTERS ( IBase[Serial Number No Leading Zero] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, IBase[Serial Number No Leading Zero] )",
              "    VAR ___d = CONCATENATEX ( ___t, IBase[Serial Number No Leading Zero], \", \" )",
              "    VAR ___x = \"IBase[Serial Number No Leading Zero] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( IBase[Ship To Customer Id] ), ",
              "    VAR ___f = FILTERS ( IBase[Ship To Customer Id] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, IBase[Ship To Customer Id] )",
              "    VAR ___d = CONCATENATEX ( ___t, IBase[Ship To Customer Id], \", \" )",
              "    VAR ___x = \"IBase[Ship To Customer Id] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( IBase[Software Versions] ), ",
              "    VAR ___f = FILTERS ( IBase[Software Versions] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, IBase[Software Versions] )",
              "    VAR ___d = CONCATENATEX ( ___t, IBase[Software Versions], \", \" )",
              "    VAR ___x = \"IBase[Software Versions] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( IBase[Sold To Customer Id] ), ",
              "    VAR ___f = FILTERS ( IBase[Sold To Customer Id] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, IBase[Sold To Customer Id] )",
              "    VAR ___d = CONCATENATEX ( ___t, IBase[Sold To Customer Id], \", \" )",
              "    VAR ___x = \"IBase[Sold To Customer Id] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( IBase[User Status] ), ",
              "    VAR ___f = FILTERS ( IBase[User Status] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, IBase[User Status] )",
              "    VAR ___d = CONCATENATEX ( ___t, IBase[User Status], \", \" )",
              "    VAR ___x = \"IBase[User Status] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Interaction Type'[Index] ), ",
              "    VAR ___f = FILTERS ( 'Interaction Type'[Index] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Interaction Type'[Index] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Interaction Type'[Index], \", \" )",
              "    VAR ___x = \"'Interaction Type'[Index] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Interaction Type'[InteractionType] ), ",
              "    VAR ___f = FILTERS ( 'Interaction Type'[InteractionType] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Interaction Type'[InteractionType] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Interaction Type'[InteractionType], \", \" )",
              "    VAR ___x = \"'Interaction Type'[InteractionType] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Knowledge Article'[Article Number] ), ",
              "    VAR ___f = FILTERS ( 'Knowledge Article'[Article Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Knowledge Article'[Article Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Knowledge Article'[Article Number], \", \" )",
              "    VAR ___x = \"'Knowledge Article'[Article Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Knowledge Article'[KnowledgeArticleId] ), ",
              "    VAR ___f = FILTERS ( 'Knowledge Article'[KnowledgeArticleId] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Knowledge Article'[KnowledgeArticleId] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Knowledge Article'[KnowledgeArticleId], \", \" )",
              "    VAR ___x = \"'Knowledge Article'[KnowledgeArticleId] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'KPI AMBD Dynamic Measures Cnt'[DM Cnt Selection AMBD] ), ",
              "    VAR ___f = FILTERS ( 'KPI AMBD Dynamic Measures Cnt'[DM Cnt Selection AMBD] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'KPI AMBD Dynamic Measures Cnt'[DM Cnt Selection AMBD] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'KPI AMBD Dynamic Measures Cnt'[DM Cnt Selection AMBD], \", \" )",
              "    VAR ___x = \"'KPI AMBD Dynamic Measures Cnt'[DM Cnt Selection AMBD] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'KPI AMBD Dynamic Measures Cnt'[Sort] ), ",
              "    VAR ___f = FILTERS ( 'KPI AMBD Dynamic Measures Cnt'[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'KPI AMBD Dynamic Measures Cnt'[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'KPI AMBD Dynamic Measures Cnt'[Sort], \", \" )",
              "    VAR ___x = \"'KPI AMBD Dynamic Measures Cnt'[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'KPI Calls Dynamic Measures %'[DM % Selection Calls] ), ",
              "    VAR ___f = FILTERS ( 'KPI Calls Dynamic Measures %'[DM % Selection Calls] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'KPI Calls Dynamic Measures %'[DM % Selection Calls] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'KPI Calls Dynamic Measures %'[DM % Selection Calls], \", \" )",
              "    VAR ___x = \"'KPI Calls Dynamic Measures %'[DM % Selection Calls] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'KPI Calls Dynamic Measures %'[Sort] ), ",
              "    VAR ___f = FILTERS ( 'KPI Calls Dynamic Measures %'[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'KPI Calls Dynamic Measures %'[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'KPI Calls Dynamic Measures %'[Sort], \", \" )",
              "    VAR ___x = \"'KPI Calls Dynamic Measures %'[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'KPI Calls Dynamic Measures Cnt'[DM Cnt Selection Calls] ), ",
              "    VAR ___f = FILTERS ( 'KPI Calls Dynamic Measures Cnt'[DM Cnt Selection Calls] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'KPI Calls Dynamic Measures Cnt'[DM Cnt Selection Calls] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'KPI Calls Dynamic Measures Cnt'[DM Cnt Selection Calls], \", \" )",
              "    VAR ___x = \"'KPI Calls Dynamic Measures Cnt'[DM Cnt Selection Calls] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'KPI Calls Dynamic Measures Cnt'[Sort] ), ",
              "    VAR ___f = FILTERS ( 'KPI Calls Dynamic Measures Cnt'[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'KPI Calls Dynamic Measures Cnt'[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'KPI Calls Dynamic Measures Cnt'[Sort], \", \" )",
              "    VAR ___x = \"'KPI Calls Dynamic Measures Cnt'[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'KPI Cases Dynamic Measures %'[DM % Selection Cases] ), ",
              "    VAR ___f = FILTERS ( 'KPI Cases Dynamic Measures %'[DM % Selection Cases] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'KPI Cases Dynamic Measures %'[DM % Selection Cases] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'KPI Cases Dynamic Measures %'[DM % Selection Cases], \", \" )",
              "    VAR ___x = \"'KPI Cases Dynamic Measures %'[DM % Selection Cases] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'KPI Cases Dynamic Measures %'[Sort] ), ",
              "    VAR ___f = FILTERS ( 'KPI Cases Dynamic Measures %'[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'KPI Cases Dynamic Measures %'[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'KPI Cases Dynamic Measures %'[Sort], \", \" )",
              "    VAR ___x = \"'KPI Cases Dynamic Measures %'[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'KPI Cases Dynamic Measures Cnt'[DM Cnt Selections Cases] ), ",
              "    VAR ___f = FILTERS ( 'KPI Cases Dynamic Measures Cnt'[DM Cnt Selections Cases] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'KPI Cases Dynamic Measures Cnt'[DM Cnt Selections Cases] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'KPI Cases Dynamic Measures Cnt'[DM Cnt Selections Cases], \", \" )",
              "    VAR ___x = \"'KPI Cases Dynamic Measures Cnt'[DM Cnt Selections Cases] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'KPI Cases Dynamic Measures Cnt'[Sort] ), ",
              "    VAR ___f = FILTERS ( 'KPI Cases Dynamic Measures Cnt'[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'KPI Cases Dynamic Measures Cnt'[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'KPI Cases Dynamic Measures Cnt'[Sort], \", \" )",
              "    VAR ___x = \"'KPI Cases Dynamic Measures Cnt'[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'KPI Community Cases Dynamic Measures %'[DM % Selection Community Cases] ), ",
              "    VAR ___f = FILTERS ( 'KPI Community Cases Dynamic Measures %'[DM % Selection Community Cases] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'KPI Community Cases Dynamic Measures %'[DM % Selection Community Cases] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'KPI Community Cases Dynamic Measures %'[DM % Selection Community Cases], \", \" )",
              "    VAR ___x = \"'KPI Community Cases Dynamic Measures %'[DM % Selection Community Cases] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'KPI Community Cases Dynamic Measures %'[Sort] ), ",
              "    VAR ___f = FILTERS ( 'KPI Community Cases Dynamic Measures %'[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'KPI Community Cases Dynamic Measures %'[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'KPI Community Cases Dynamic Measures %'[Sort], \", \" )",
              "    VAR ___x = \"'KPI Community Cases Dynamic Measures %'[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'KPI Community Cases Dynamic Measures Cnt'[DM Cnt Selection Community Cases] ), ",
              "    VAR ___f = FILTERS ( 'KPI Community Cases Dynamic Measures Cnt'[DM Cnt Selection Community Cases] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'KPI Community Cases Dynamic Measures Cnt'[DM Cnt Selection Community Cases] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'KPI Community Cases Dynamic Measures Cnt'[DM Cnt Selection Community Cases], \", \" )",
              "    VAR ___x = \"'KPI Community Cases Dynamic Measures Cnt'[DM Cnt Selection Community Cases] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'KPI Community Cases Dynamic Measures Cnt'[Sort] ), ",
              "    VAR ___f = FILTERS ( 'KPI Community Cases Dynamic Measures Cnt'[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'KPI Community Cases Dynamic Measures Cnt'[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'KPI Community Cases Dynamic Measures Cnt'[Sort], \", \" )",
              "    VAR ___x = \"'KPI Community Cases Dynamic Measures Cnt'[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'KPI Time to Assign in Hours Dynamic Measures Cnt'[DM Cnt Selection Time to Assign in Hours] ), ",
              "    VAR ___f = FILTERS ( 'KPI Time to Assign in Hours Dynamic Measures Cnt'[DM Cnt Selection Time to Assign in Hours] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'KPI Time to Assign in Hours Dynamic Measures Cnt'[DM Cnt Selection Time to Assign in Hours] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'KPI Time to Assign in Hours Dynamic Measures Cnt'[DM Cnt Selection Time to Assign in Hours], \", \" )",
              "    VAR ___x = \"'KPI Time to Assign in Hours Dynamic Measures Cnt'[DM Cnt Selection Time to Assign in Hours] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'KPI Time to Assign in Hours Dynamic Measures Cnt'[Sort] ), ",
              "    VAR ___f = FILTERS ( 'KPI Time to Assign in Hours Dynamic Measures Cnt'[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'KPI Time to Assign in Hours Dynamic Measures Cnt'[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'KPI Time to Assign in Hours Dynamic Measures Cnt'[Sort], \", \" )",
              "    VAR ___x = \"'KPI Time to Assign in Hours Dynamic Measures Cnt'[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[ES Non ES] ), ",
              "    VAR ___f = FILTERS ( Materials[ES Non ES] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[ES Non ES] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[ES Non ES], \", \" )",
              "    VAR ___x = \"Materials[ES Non ES] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[Material Description] ), ",
              "    VAR ___f = FILTERS ( Materials[Material Description] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[Material Description] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[Material Description], \", \" )",
              "    VAR ___x = \"Materials[Material Description] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[Material ID] ), ",
              "    VAR ___f = FILTERS ( Materials[Material ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[Material ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[Material ID], \", \" )",
              "    VAR ___x = \"Materials[Material ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[Material ID No Leading Zero] ), ",
              "    VAR ___f = FILTERS ( Materials[Material ID No Leading Zero] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[Material ID No Leading Zero] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[Material ID No Leading Zero], \", \" )",
              "    VAR ___x = \"Materials[Material ID No Leading Zero] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[Material Master Index] ), ",
              "    VAR ___f = FILTERS ( Materials[Material Master Index] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[Material Master Index] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[Material Master Index], \", \" )",
              "    VAR ___x = \"Materials[Material Master Index] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[PHL4] ), ",
              "    VAR ___f = FILTERS ( Materials[PHL4] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[PHL4] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[PHL4], \", \" )",
              "    VAR ___x = \"Materials[PHL4] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[PHL5] ), ",
              "    VAR ___f = FILTERS ( Materials[PHL5] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[PHL5] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[PHL5], \", \" )",
              "    VAR ___x = \"Materials[PHL5] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[Product Category] ), ",
              "    VAR ___f = FILTERS ( Materials[Product Category] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[Product Category] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[Product Category], \", \" )",
              "    VAR ___x = \"Materials[Product Category] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[Product Hierarchy Level 1] ), ",
              "    VAR ___f = FILTERS ( Materials[Product Hierarchy Level 1] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[Product Hierarchy Level 1] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[Product Hierarchy Level 1], \", \" )",
              "    VAR ___x = \"Materials[Product Hierarchy Level 1] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[Product Hierarchy Level 1 Description] ), ",
              "    VAR ___f = FILTERS ( Materials[Product Hierarchy Level 1 Description] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[Product Hierarchy Level 1 Description] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[Product Hierarchy Level 1 Description], \", \" )",
              "    VAR ___x = \"Materials[Product Hierarchy Level 1 Description] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[Product Hierarchy Level 2] ), ",
              "    VAR ___f = FILTERS ( Materials[Product Hierarchy Level 2] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[Product Hierarchy Level 2] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[Product Hierarchy Level 2], \", \" )",
              "    VAR ___x = \"Materials[Product Hierarchy Level 2] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[Product Hierarchy Level 2 Description] ), ",
              "    VAR ___f = FILTERS ( Materials[Product Hierarchy Level 2 Description] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[Product Hierarchy Level 2 Description] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[Product Hierarchy Level 2 Description], \", \" )",
              "    VAR ___x = \"Materials[Product Hierarchy Level 2 Description] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[Product Hierarchy Level 3] ), ",
              "    VAR ___f = FILTERS ( Materials[Product Hierarchy Level 3] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[Product Hierarchy Level 3] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[Product Hierarchy Level 3], \", \" )",
              "    VAR ___x = \"Materials[Product Hierarchy Level 3] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[Product Hierarchy Level 3 Description] ), ",
              "    VAR ___f = FILTERS ( Materials[Product Hierarchy Level 3 Description] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[Product Hierarchy Level 3 Description] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[Product Hierarchy Level 3 Description], \", \" )",
              "    VAR ___x = \"Materials[Product Hierarchy Level 3 Description] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[Product Hierarchy Level 4] ), ",
              "    VAR ___f = FILTERS ( Materials[Product Hierarchy Level 4] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[Product Hierarchy Level 4] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[Product Hierarchy Level 4], \", \" )",
              "    VAR ___x = \"Materials[Product Hierarchy Level 4] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[Product Hierarchy Level 4 Description] ), ",
              "    VAR ___f = FILTERS ( Materials[Product Hierarchy Level 4 Description] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[Product Hierarchy Level 4 Description] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[Product Hierarchy Level 4 Description], \", \" )",
              "    VAR ___x = \"Materials[Product Hierarchy Level 4 Description] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[Product Hierarchy Level 5] ), ",
              "    VAR ___f = FILTERS ( Materials[Product Hierarchy Level 5] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[Product Hierarchy Level 5] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[Product Hierarchy Level 5], \", \" )",
              "    VAR ___x = \"Materials[Product Hierarchy Level 5] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[Product Hierarchy Level 5 Description] ), ",
              "    VAR ___f = FILTERS ( Materials[Product Hierarchy Level 5 Description] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[Product Hierarchy Level 5 Description] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[Product Hierarchy Level 5 Description], \", \" )",
              "    VAR ___x = \"Materials[Product Hierarchy Level 5 Description] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[Product Sub Category] ), ",
              "    VAR ___f = FILTERS ( Materials[Product Sub Category] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[Product Sub Category] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[Product Sub Category], \", \" )",
              "    VAR ___x = \"Materials[Product Sub Category] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Materials[Reference Product No Leading Zero] ), ",
              "    VAR ___f = FILTERS ( Materials[Reference Product No Leading Zero] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Materials[Reference Product No Leading Zero] )",
              "    VAR ___d = CONCATENATEX ( ___t, Materials[Reference Product No Leading Zero], \", \" )",
              "    VAR ___x = \"Materials[Reference Product No Leading Zero] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Minutes to Close Bucket'[Index] ), ",
              "    VAR ___f = FILTERS ( 'Minutes to Close Bucket'[Index] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Minutes to Close Bucket'[Index] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Minutes to Close Bucket'[Index], \", \" )",
              "    VAR ___x = \"'Minutes to Close Bucket'[Index] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Minutes to Close Bucket'[Minutes to Close Bucket] ), ",
              "    VAR ___f = FILTERS ( 'Minutes to Close Bucket'[Minutes to Close Bucket] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Minutes to Close Bucket'[Minutes to Close Bucket] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Minutes to Close Bucket'[Minutes to Close Bucket], \", \" )",
              "    VAR ___x = \"'Minutes to Close Bucket'[Minutes to Close Bucket] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Minutes to Close Bucket'[Sort] ), ",
              "    VAR ___f = FILTERS ( 'Minutes to Close Bucket'[Sort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Minutes to Close Bucket'[Sort] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Minutes to Close Bucket'[Sort], \", \" )",
              "    VAR ___x = \"'Minutes to Close Bucket'[Sort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( MLC[Device Type] ), ",
              "    VAR ___f = FILTERS ( MLC[Device Type] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, MLC[Device Type] )",
              "    VAR ___d = CONCATENATEX ( ___t, MLC[Device Type], \", \" )",
              "    VAR ___x = \"MLC[Device Type] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( MLC[Problem Type] ), ",
              "    VAR ___f = FILTERS ( MLC[Problem Type] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, MLC[Problem Type] )",
              "    VAR ___d = CONCATENATEX ( ___t, MLC[Problem Type], \", \" )",
              "    VAR ___x = \"MLC[Problem Type] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( MLC[Service Request ID] ), ",
              "    VAR ___f = FILTERS ( MLC[Service Request ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, MLC[Service Request ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, MLC[Service Request ID], \", \" )",
              "    VAR ___x = \"MLC[Service Request ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( MLC[Symptom 1] ), ",
              "    VAR ___f = FILTERS ( MLC[Symptom 1] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, MLC[Symptom 1] )",
              "    VAR ___d = CONCATENATEX ( ___t, MLC[Symptom 1], \", \" )",
              "    VAR ___x = \"MLC[Symptom 1] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( PrimaryProduct[PP] ), ",
              "    VAR ___f = FILTERS ( PrimaryProduct[PP] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, PrimaryProduct[PP] )",
              "    VAR ___d = CONCATENATEX ( ___t, PrimaryProduct[PP], \", \" )",
              "    VAR ___x = \"PrimaryProduct[PP] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( PrimaryProduct[PrimaryProduct] ), ",
              "    VAR ___f = FILTERS ( PrimaryProduct[PrimaryProduct] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, PrimaryProduct[PrimaryProduct] )",
              "    VAR ___d = CONCATENATEX ( ___t, PrimaryProduct[PrimaryProduct], \", \" )",
              "    VAR ___x = \"PrimaryProduct[PrimaryProduct] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( PrimaryProductGroup[PPG] ), ",
              "    VAR ___f = FILTERS ( PrimaryProductGroup[PPG] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, PrimaryProductGroup[PPG] )",
              "    VAR ___d = CONCATENATEX ( ___t, PrimaryProductGroup[PPG], \", \" )",
              "    VAR ___x = \"PrimaryProductGroup[PPG] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( PrimaryProductGroup[PrimaryProductGroup] ), ",
              "    VAR ___f = FILTERS ( PrimaryProductGroup[PrimaryProductGroup] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, PrimaryProductGroup[PrimaryProductGroup] )",
              "    VAR ___d = CONCATENATEX ( ___t, PrimaryProductGroup[PrimaryProductGroup], \", \" )",
              "    VAR ___x = \"PrimaryProductGroup[PrimaryProductGroup] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Priority Description'[Index] ), ",
              "    VAR ___f = FILTERS ( 'Priority Description'[Index] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Priority Description'[Index] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Priority Description'[Index], \", \" )",
              "    VAR ___x = \"'Priority Description'[Index] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Priority Description'[Priority Description] ), ",
              "    VAR ___f = FILTERS ( 'Priority Description'[Priority Description] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Priority Description'[Priority Description] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Priority Description'[Priority Description], \", \" )",
              "    VAR ___x = \"'Priority Description'[Priority Description] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Products[Products] ), ",
              "    VAR ___f = FILTERS ( Products[Products] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Products[Products] )",
              "    VAR ___d = CONCATENATEX ( ___t, Products[Products], \", \" )",
              "    VAR ___x = \"Products[Products] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Queue[Queue Name] ), ",
              "    VAR ___f = FILTERS ( Queue[Queue Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Queue[Queue Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, Queue[Queue Name], \", \" )",
              "    VAR ___x = \"Queue[Queue Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Queue[Queue Name Index] ), ",
              "    VAR ___f = FILTERS ( Queue[Queue Name Index] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Queue[Queue Name Index] )",
              "    VAR ___d = CONCATENATEX ( ___t, Queue[Queue Name Index], \", \" )",
              "    VAR ___x = \"Queue[Queue Name Index] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Regions[Region] ), ",
              "    VAR ___f = FILTERS ( Regions[Region] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Regions[Region] )",
              "    VAR ___d = CONCATENATEX ( ___t, Regions[Region], \", \" )",
              "    VAR ___x = \"Regions[Region] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Regions[State] ), ",
              "    VAR ___f = FILTERS ( Regions[State] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Regions[State] )",
              "    VAR ___d = CONCATENATEX ( ___t, Regions[State], \", \" )",
              "    VAR ___x = \"Regions[State] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Requested VQ'[Index] ), ",
              "    VAR ___f = FILTERS ( 'Requested VQ'[Index] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Requested VQ'[Index] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Requested VQ'[Index], \", \" )",
              "    VAR ___x = \"'Requested VQ'[Index] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Requested VQ'[Requested VQ] ), ",
              "    VAR ___f = FILTERS ( 'Requested VQ'[Requested VQ] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Requested VQ'[Requested VQ] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Requested VQ'[Requested VQ], \", \" )",
              "    VAR ___x = \"'Requested VQ'[Requested VQ] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Required Skill'[Index] ), ",
              "    VAR ___f = FILTERS ( 'Required Skill'[Index] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Required Skill'[Index] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Required Skill'[Index], \", \" )",
              "    VAR ___x = \"'Required Skill'[Index] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Required Skill'[Required Skill] ), ",
              "    VAR ___f = FILTERS ( 'Required Skill'[Required Skill] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Required Skill'[Required Skill] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Required Skill'[Required Skill], \", \" )",
              "    VAR ___x = \"'Required Skill'[Required Skill] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Resource Role'[Index] ), ",
              "    VAR ___f = FILTERS ( 'Resource Role'[Index] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Resource Role'[Index] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Resource Role'[Index], \", \" )",
              "    VAR ___x = \"'Resource Role'[Index] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Resource Role'[Resource Role] ), ",
              "    VAR ___f = FILTERS ( 'Resource Role'[Resource Role] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Resource Role'[Resource Role] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Resource Role'[Resource Role], \", \" )",
              "    VAR ___x = \"'Resource Role'[Resource Role] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Resource Type'[Index] ), ",
              "    VAR ___f = FILTERS ( 'Resource Type'[Index] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Resource Type'[Index] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Resource Type'[Index], \", \" )",
              "    VAR ___x = \"'Resource Type'[Index] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Resource Type'[Resource Type] ), ",
              "    VAR ___f = FILTERS ( 'Resource Type'[Resource Type] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Resource Type'[Resource Type] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Resource Type'[Resource Type], \", \" )",
              "    VAR ___x = \"'Resource Type'[Resource Type] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Result Reason'[Index] ), ",
              "    VAR ___f = FILTERS ( 'Result Reason'[Index] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Result Reason'[Index] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Result Reason'[Index], \", \" )",
              "    VAR ___x = \"'Result Reason'[Index] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Result Reason'[Result Reason] ), ",
              "    VAR ___f = FILTERS ( 'Result Reason'[Result Reason] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Result Reason'[Result Reason] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Result Reason'[Result Reason], \", \" )",
              "    VAR ___x = \"'Result Reason'[Result Reason] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Status Description'[Index] ), ",
              "    VAR ___f = FILTERS ( 'Status Description'[Index] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Status Description'[Index] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Status Description'[Index], \", \" )",
              "    VAR ___x = \"'Status Description'[Index] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Status Description'[Status Description] ), ",
              "    VAR ___f = FILTERS ( 'Status Description'[Status Description] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Status Description'[Status Description] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Status Description'[Status Description], \", \" )",
              "    VAR ___x = \"'Status Description'[Status Description] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Technical Result'[Index] ), ",
              "    VAR ___f = FILTERS ( 'Technical Result'[Index] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Technical Result'[Index] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Technical Result'[Index], \", \" )",
              "    VAR ___x = \"'Technical Result'[Index] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Technical Result'[Technical Result] ), ",
              "    VAR ___f = FILTERS ( 'Technical Result'[Technical Result] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Technical Result'[Technical Result] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Technical Result'[Technical Result], \", \" )",
              "    VAR ___x = \"'Technical Result'[Technical Result] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Calendar Date Number] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Calendar Date Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Calendar Date Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Calendar Date Number], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Calendar Date Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Calendar Date Weekday] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Calendar Date Weekday] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Calendar Date Weekday] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Calendar Date Weekday], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Calendar Date Weekday] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Calendar Days in Month] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Calendar Days in Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Calendar Days in Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Calendar Days in Month], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Calendar Days in Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Calendar Month] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Calendar Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Calendar Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Calendar Month], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Calendar Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Calendar Month Number] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Calendar Month Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Calendar Month Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Calendar Month Number], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Calendar Month Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Calendar Quarter] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Calendar Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Calendar Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Calendar Quarter], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Calendar Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Calendar Quarter Number] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Calendar Quarter Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Calendar Quarter Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Calendar Quarter Number], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Calendar Quarter Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Calendar Year Month] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Calendar Year Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Calendar Year Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Calendar Year Month], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Calendar Year Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Calendar Year Quarter] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Calendar Year Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Calendar Year Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Calendar Year Quarter], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Calendar Year Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[calendar_date] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[calendar_date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[calendar_date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[calendar_date], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[calendar_date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[calendaryear] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[calendaryear] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[calendaryear] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[calendaryear], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[calendaryear] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Date] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Date], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Date of Month] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Date of Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Date of Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Date of Month], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Date of Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Date yyyymm] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Date yyyymm] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Date yyyymm] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Date yyyymm], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Date yyyymm] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Date yyyymmdd] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Date yyyymmdd] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Date yyyymmdd] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Date yyyymmdd], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Date yyyymmdd] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Day of Week Number] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Day of Week Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Day of Week Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Day of Week Number], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Day of Week Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Day of Year] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Day of Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Day of Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Day of Year], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Day of Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Days in Month Past] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Days in Month Past] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Days in Month Past] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Days in Month Past], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Days in Month Past] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Days in Month Remaining] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Days in Month Remaining] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Days in Month Remaining] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Days in Month Remaining], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Days in Month Remaining] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[First Date of Month] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[First Date of Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[First Date of Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[First Date of Month], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[First Date of Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Fiscal Month Number] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Fiscal Month Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Fiscal Month Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Fiscal Month Number], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Fiscal Month Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Fiscal Quarter] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Fiscal Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Fiscal Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Fiscal Quarter], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Fiscal Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Fiscal Quarter Number] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Fiscal Quarter Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Fiscal Quarter Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Fiscal Quarter Number], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Fiscal Quarter Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Fiscal Year] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Fiscal Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Fiscal Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Fiscal Year], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Fiscal Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Fiscal Year Month] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Fiscal Year Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Fiscal Year Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Fiscal Year Month], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Fiscal Year Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Fiscal Year Name] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Fiscal Year Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Fiscal Year Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Fiscal Year Name], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Fiscal Year Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Fiscal Year Negative] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Fiscal Year Negative] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Fiscal Year Negative] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Fiscal Year Negative], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Fiscal Year Negative] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Fiscal Year Quarter] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Fiscal Year Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Fiscal Year Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Fiscal Year Quarter], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Fiscal Year Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[FY Neg] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[FY Neg] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[FY Neg] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[FY Neg], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[FY Neg] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[FY Quarter] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[FY Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[FY Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[FY Quarter], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[FY Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[FYYYMonthSort] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[FYYYMonthSort] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[FYYYMonthSort] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[FYYYMonthSort], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[FYYYMonthSort] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[FYYYY Month Day] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[FYYYY Month Day] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[FYYYY Month Day] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[FYYYY Month Day], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[FYYYY Month Day] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[FYYYY Month Name] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[FYYYY Month Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[FYYYY Month Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[FYYYY Month Name], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[FYYYY Month Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[FYYYY Quarter] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[FYYYY Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[FYYYY Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[FYYYY Quarter], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[FYYYY Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[FYYYY Week Number] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[FYYYY Week Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[FYYYY Week Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[FYYYY Week Number], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[FYYYY Week Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[FYYYYMM] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[FYYYYMM] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[FYYYYMM] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[FYYYYMM], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[FYYYYMM] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Julian Date JDE] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Julian Date JDE] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Julian Date JDE] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Julian Date JDE], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Julian Date JDE] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Transaction Dates'[Julian Date STD] ), ",
              "    VAR ___f = FILTERS ( 'Transaction Dates'[Julian Date STD] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Transaction Dates'[Julian Date STD] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Transaction Dates'[Julian Date STD], \", \" )",
              "    VAR ___x = \"'Transaction Dates'[Julian Date STD] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'WaitDurations for ASA Calculations'[Call Date] ), ",
              "    VAR ___f = FILTERS ( 'WaitDurations for ASA Calculations'[Call Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'WaitDurations for ASA Calculations'[Call Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'WaitDurations for ASA Calculations'[Call Date], \", \" )",
              "    VAR ___x = \"'WaitDurations for ASA Calculations'[Call Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'WaitDurations for ASA Calculations'[Interaction ID] ), ",
              "    VAR ___f = FILTERS ( 'WaitDurations for ASA Calculations'[Interaction ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'WaitDurations for ASA Calculations'[Interaction ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'WaitDurations for ASA Calculations'[Interaction ID], \", \" )",
              "    VAR ___x = \"'WaitDurations for ASA Calculations'[Interaction ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'WaitDurations for ASA Calculations'[Wait Duration] ), ",
              "    VAR ___f = FILTERS ( 'WaitDurations for ASA Calculations'[Wait Duration] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'WaitDurations for ASA Calculations'[Wait Duration] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'WaitDurations for ASA Calculations'[Wait Duration], \", \" )",
              "    VAR ___x = \"'WaitDurations for ASA Calculations'[Wait Duration] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'WaitDurations for ASA Calculations'[Wait Duration (Formatted)] ), ",
              "    VAR ___f = FILTERS ( 'WaitDurations for ASA Calculations'[Wait Duration (Formatted)] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'WaitDurations for ASA Calculations'[Wait Duration (Formatted)] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'WaitDurations for ASA Calculations'[Wait Duration (Formatted)], \", \" )",
              "    VAR ___x = \"'WaitDurations for ASA Calculations'[Wait Duration (Formatted)] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              ""
            ],
            "isHidden": true,
            "lineageTag": "e1dee7bc-6d5f-41b2-b5b7-48d228ecda1d"
          }
        ],
        "partitions": [
          {
            "name": "Labels-c986a9d8-3ab6-4aea-9ba7-cbd7feaf43c5",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "  Source = Table.FromRows(",
                "    Json.Document(",
                "      Binary.Decompress(Binary.FromText(\"i45WMlSKjQUA\", BinaryEncoding.Base64), Compression.Deflate)",
                "    ),",
                "    let",
                "      _t = ((type nullable text) meta [Serialized.Text = true])",
                "    in",
                "      type table [Column1 = _t]",
                "  ),",
                "  #\"Changed Type\" = Table.TransformColumnTypes(Source, {{\"Column1\", Int64.Type}}),",
                "  #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\", {\"Column1\"})",
                "in",
                "  #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MLC",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Device Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6035f2b0-40ae-424e-a16e-529991f2061d",
            "sourceColumn": "Device Type",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Problem Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34fabfb8-9bf7-4fd2-8e2d-aa2623ccc296",
            "sourceColumn": "Problem Type",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Service Request ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a6ea0cc-8f54-44a4-b448-a6e77d6ee183",
            "sourceColumn": "Service Request ID",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          },
          {
            "name": "Symptom 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e27be49f-3b44-4bb5-b6a8-23068ac261fa",
            "sourceColumn": "Symptom 1",
            "sourceProviderType": "nvarchar(max)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "06279728-2d41-474f-a23f-4894d32dafab",
        "partitions": [
          {
            "name": "MLC-fce08a38-9b8b-4840-b49e-fe20f1854d2a",
            "mode": "import",
            "queryGroup": "Dim\\Cases",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows([]),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"2c75acb2-a0ef-4a66-a591-2e330011662f\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"2c75acb2-a0ef-4a66-a591-2e330011662f\"]}",
                "    [Data],",
                "  RV_trafero_semantic_canonical_tscmultilevelcat_ = #\"2c75acb2-a0ef-4a66-a591-2e330011662f\"",
                "    {[entity = \"RV_trafero_semantic_canonical_tscmultilevelcat\", version = \"\"]}",
                "    [Data],",
                "  #\"Removed Columns\" = Table.RemoveColumns(",
                "    RV_trafero_semantic_canonical_tscmultilevelcat_,",
                "    {",
                "      \"BusinessUnit\",",
                "      \"FailureBusinessUnit\",",
                "      \"FailureDevicetype\",",
                "      \"FailureProblemType\",",
                "      \"FailureResolution\",",
                "      \"FailureMode\",",
                "      \"MLCSourceSystem\",",
                "      \"LoadDateTime\",",
                "      \"Symptom2\"",
                "    }",
                "  ),",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    #\"Removed Columns\",",
                "    {",
                "      {\"DeviceType\", \"Device Type\"},",
                "      {\"ProblemType\", \"Problem Type\"},",
                "      {\"ServiceRequestId\", \"Service Request ID\"},",
                "      {\"Symptom1\", \"Symptom 1\"}",
                "    }",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Materials",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ES Non ES",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9d7a00aa-0323-4058-baa0-090e84abe155",
            "sourceColumn": "ES Non ES",
            "summarizeBy": "none"
          },
          {
            "name": "Material Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "53f2977b-f71e-42b1-9278-fe0ebc80c466",
            "sourceColumn": "Material Description",
            "summarizeBy": "none"
          },
          {
            "name": "Material ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e9a015b-2158-4582-a473-ce73d5c10e22",
            "sourceColumn": "Material ID",
            "summarizeBy": "none"
          },
          {
            "name": "Material ID No Leading Zero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c90d9028-2c11-45f5-85cc-15d3da691398",
            "sourceColumn": "Material ID No Leading Zero",
            "summarizeBy": "none"
          },
          {
            "name": "Material Master Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "24583e85-d321-4490-8710-ef33e9ab6c10",
            "sourceColumn": "Material Master Index",
            "summarizeBy": "none"
          },
          {
            "name": "PHL4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac0c8f6c-e7ed-490e-a535-560aedd223cb",
            "sourceColumn": "PHL4",
            "summarizeBy": "none"
          },
          {
            "name": "PHL5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d18dbad-5e9d-411f-bc0d-9a0e43e7e629",
            "sourceColumn": "PHL5",
            "summarizeBy": "none"
          },
          {
            "name": "Product Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "16c738c9-9db5-4b26-b59c-9009225b6c9d",
            "sourceColumn": "Product Category",
            "summarizeBy": "none"
          },
          {
            "name": "Product Hierarchy Level 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7dd2a65-02b7-4d1c-82b6-88331ffc9a58",
            "sourceColumn": "Product Hierarchy Level 1",
            "summarizeBy": "none"
          },
          {
            "name": "Product Hierarchy Level 1 Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f4565b0-3005-44ce-8ec9-37a326f94e4b",
            "sourceColumn": "Product Hierarchy Level 1 Description",
            "summarizeBy": "none"
          },
          {
            "name": "Product Hierarchy Level 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c69d116b-a5d7-434e-916f-60b357df7b98",
            "sourceColumn": "Product Hierarchy Level 2",
            "summarizeBy": "none"
          },
          {
            "name": "Product Hierarchy Level 2 Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b80b64b-0286-4b66-8ebb-edb62666ee2f",
            "sourceColumn": "Product Hierarchy Level 2 Description",
            "summarizeBy": "none"
          },
          {
            "name": "Product Hierarchy Level 3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aee977f7-bb8a-4b42-a0a7-5860bbf179a7",
            "sourceColumn": "Product Hierarchy Level 3",
            "summarizeBy": "none"
          },
          {
            "name": "Product Hierarchy Level 3 Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e359d4d4-48e7-4aae-b72e-447c0d4f9a95",
            "sourceColumn": "Product Hierarchy Level 3 Description",
            "summarizeBy": "none"
          },
          {
            "name": "Product Hierarchy Level 4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "074aa628-d7f1-44fa-8682-e2f37001e489",
            "sourceColumn": "Product Hierarchy Level 4",
            "summarizeBy": "none"
          },
          {
            "name": "Product Hierarchy Level 4 Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ce9f4d2-f102-4148-9779-30831e3c27ef",
            "sourceColumn": "Product Hierarchy Level 4 Description",
            "summarizeBy": "none"
          },
          {
            "name": "Product Hierarchy Level 5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6678318d-6a39-4162-a541-39d7a013f5e4",
            "sourceColumn": "Product Hierarchy Level 5",
            "summarizeBy": "none"
          },
          {
            "name": "Product Hierarchy Level 5 Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2324177f-6a4f-40af-a43b-0d969c7a281b",
            "sourceColumn": "Product Hierarchy Level 5 Description",
            "summarizeBy": "none"
          },
          {
            "name": "Product Sub Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c3910df-e006-4d5e-b699-7d1b1868c2c3",
            "sourceColumn": "Product Sub Category",
            "summarizeBy": "none"
          },
          {
            "name": "Reference Product No Leading Zero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7237f3c5-caec-4dfc-bfcd-267686ed4481",
            "sourceColumn": "Reference Product No Leading Zero",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f4175e97-80d2-48df-a58d-ea7bdfe5509b",
        "partitions": [
          {
            "name": "Materials-23c3dd37-ed04-467c-b6d7-05eaf1ba847f",
            "mode": "import",
            "queryGroup": "Dim\\Cases",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"79e504d4-45fb-4224-a774-b1871c6fdb1b\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"79e504d4-45fb-4224-a774-b1871c6fdb1b\"]}",
                "    [Data],",
                "  Materials_ = #\"79e504d4-45fb-4224-a774-b1871c6fdb1b\"{[entity = \"Materials\", version = \"\"]}[Data],",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    Materials_,",
                "    {",
                "      {\"ProductCategory\", \"Product Category\"},",
                "      {\"ProductSubCategory\", \"Product Sub Category\"},",
                "      {\"ESNonES\", \"ES Non ES\"},",
                "      {\"MaterialDescription\", \"Material Description\"},",
                "      {\"MaterialId\", \"Material ID\"},",
                "      {\"MaterialIdNoLeadingZero\", \"Material ID No Leading Zero\"},",
                "      {\"MaterialMasterIndex\", \"Material Master Index\"},",
                "      {\"ProductHierarchyLevel1\", \"Product Hierarchy Level 1\"},",
                "      {\"ProductHierarchyLevel1Description\", \"Product Hierarchy Level 1 Description\"},",
                "      {\"ProductHierarchyLevel2\", \"Product Hierarchy Level 2\"},",
                "      {\"ProductHierarchyLevel2Description\", \"Product Hierarchy Level 2 Description\"},",
                "      {\"ProductHierarchyLevel3\", \"Product Hierarchy Level 3\"},",
                "      {\"ProductHierarchyLevel3Description\", \"Product Hierarchy Level 3 Description\"},",
                "      {\"ProductHierarchyLevel4\", \"Product Hierarchy Level 4\"},",
                "      {\"ProductHierarchyLevel4Description\", \"Product Hierarchy Level 4 Description\"},",
                "      {\"ProductHierarchyLevel5\", \"Product Hierarchy Level 5\"},",
                "      {\"ProductHierarchyLevel5Description\", \"Product Hierarchy Level 5 Description\"}",
                "    }",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Minutes to Close Bucket",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6bbb3e46-cfe3-44ea-a155-96e69cd962fc",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          },
          {
            "name": "Minutes to Close Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecaf1019-0ffe-4a5c-ae99-7c336a5e855e",
            "sourceColumn": "Minutes to Close Bucket",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1fb2df25-f956-42d5-8010-94ad1de28029",
            "sourceColumn": "Sort",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0b1936ed-0e94-4ff8-8eb2-278943e62c7d",
        "partitions": [
          {
            "name": "Minutes to Close Bucket-9624ef24-01c9-4116-a0c2-c272af7c159c",
            "mode": "import",
            "queryGroup": "Dim\\Cases",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"0392bc48-71e2-4a13-bcf2-f9800ae1dd1e\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"0392bc48-71e2-4a13-bcf2-f9800ae1dd1e\"]}",
                "    [Data],",
                "  RV_trafero_semantic_canonical_tsc_minutestoclosebucket_ = #\"0392bc48-71e2-4a13-bcf2-f9800ae1dd1e\"",
                "    {[entity = \"RV_trafero_semantic_canonical_tsc_minutestoclosebucket\", version = \"\"]}",
                "    [Data],",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    RV_trafero_semantic_canonical_tsc_minutestoclosebucket_,",
                "    {{\"MinutesToCloseBucket\", \"Minutes to Close Bucket\"}}",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PrimaryProduct",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad301da2-86c4-452b-9ac9-796dec96e544",
            "sourceColumn": "PP",
            "summarizeBy": "none"
          },
          {
            "name": "PrimaryProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isKey": true,
            "lineageTag": "44da787a-364b-4513-b035-e9e3b9e29a75",
            "sourceColumn": "PrimaryProduct",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cb4ed66f-b056-442d-abd9-4986259bf6cb",
        "partitions": [
          {
            "name": "PrimaryProduct-56cc2133-6858-44e8-a40b-51f05a323872",
            "mode": "import",
            "queryGroup": "Dim\\Common",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"b85c5b01-590c-40a3-bdfb-610fa8b1429f\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"b85c5b01-590c-40a3-bdfb-610fa8b1429f\"]}",
                "    [Data],",
                "  PrimaryProduct_ = #\"b85c5b01-590c-40a3-bdfb-610fa8b1429f\"",
                "    {[entity = \"PrimaryProduct\", version = \"\"]}",
                "    [Data]",
                "in",
                "  PrimaryProduct_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PrimaryProductGroup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PPG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c579f7e-a8c8-4859-a40b-6366c51478ae",
            "sourceColumn": "PPG",
            "summarizeBy": "none"
          },
          {
            "name": "PrimaryProductGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isKey": true,
            "lineageTag": "d9a5dd03-858f-4b4a-98c7-7a56e3bab462",
            "sourceColumn": "PrimaryProductGroup",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5d1467d2-8d3e-4da3-be83-3bbcfbde849d",
        "partitions": [
          {
            "name": "PrimaryProductGroup-981a75ad-ff52-4701-8910-1396aa41a0eb",
            "mode": "import",
            "queryGroup": "Dim\\Common",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"b85c5b01-590c-40a3-bdfb-610fa8b1429f\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"b85c5b01-590c-40a3-bdfb-610fa8b1429f\"]}",
                "    [Data],",
                "  PrimaryProductGroup_ = #\"b85c5b01-590c-40a3-bdfb-610fa8b1429f\"",
                "    {[entity = \"PrimaryProductGroup\", version = \"\"]}",
                "    [Data]",
                "in",
                "  PrimaryProductGroup_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Priority Description",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9278417d-c4c4-45f0-bae7-33460602da60",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          },
          {
            "name": "Priority Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b63f57a0-04fb-4549-8a9d-a5c3c6f32c7f",
            "sourceColumn": "Priority Description",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1ce4c81d-54a1-450e-bed7-29c81b1f75b3",
        "partitions": [
          {
            "name": "Priority Description-e53e8371-5b6e-4e83-a50d-e3c20887866f",
            "mode": "import",
            "queryGroup": "Dim\\Cases",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"a5562717-b7b2-4dbb-a2c8-dd7c6aabef35\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"a5562717-b7b2-4dbb-a2c8-dd7c6aabef35\"]}",
                "    [Data],",
                "  RV_trafero_semantic_canonical_tsc_prioritydescription_ = #\"a5562717-b7b2-4dbb-a2c8-dd7c6aabef35\"",
                "    {[entity = \"RV_trafero_semantic_canonical_tsc_prioritydescription\", version = \"\"]}",
                "    [Data],",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    RV_trafero_semantic_canonical_tsc_prioritydescription_,",
                "    {{\"PriorityDescription\", \"Priority Description\"}}",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Products",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Products",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isKey": true,
            "lineageTag": "547dc89a-5ffa-4e56-a7a6-82d95ec64553",
            "sourceColumn": "Products",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "726421c5-fe1d-4143-be23-60d8dd70dc5b",
        "partitions": [
          {
            "name": "Products-c090c6dd-db57-4f87-96c7-a89b0763861d",
            "mode": "import",
            "queryGroup": "Dim\\Common",
            "source": {
              "expression": [
                "let",
                "  Source = Table.Combine({#\"CasesProduct\", #\"CallsProduct\"}),",
                "  #\"Grouped rows\" = Table.Group(",
                "    Source,",
                "    {\"Products\"},",
                "    {{\"Count\", each Table.RowCount(_), Int64.Type}}",
                "  ),",
                "  #\"Removed Columns\" = Table.RemoveColumns(#\"Grouped rows\", {\"Count\"})",
                "in",
                "  #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Queue",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Queue Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7513ed22-8f95-46bf-90ff-5003c171b53f",
            "sourceColumn": "Queue Name",
            "summarizeBy": "none"
          },
          {
            "name": "Queue Name Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51350596-239a-4dc1-bfeb-70c9903da0ce",
            "sourceColumn": "Queue Name Index",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8e699477-ab23-4e79-bcc1-cdd82ad6d312",
        "partitions": [
          {
            "name": "Queue-dbfd9906-61d0-4ce7-ac89-77d4944d323b",
            "mode": "import",
            "queryGroup": "Dim\\Calls",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces{[workspaceId=\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}[Data],",
                "    #\"2f604379-88e6-4253-b91e-33aa4068edae\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"{[dataflowId=\"2f604379-88e6-4253-b91e-33aa4068edae\"]}[Data],",
                "    Queue_ = #\"2f604379-88e6-4253-b91e-33aa4068edae\"{[entity=\"Queue\",version=\"\"]}[Data]",
                "in",
                "    Queue_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Regions",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea565cea-557f-4004-9ded-97cb6e361eeb",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isKey": true,
            "lineageTag": "aa08c7a6-1237-4bfe-a13f-ba4aaa11df41",
            "sourceColumn": "State",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9c73d94a-ad48-4765-81ed-9bc6f93eee87",
        "partitions": [
          {
            "name": "Regions-56df8e13-9557-49b9-8118-78a7979e1571",
            "mode": "import",
            "queryGroup": "Dim\\Common",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"7a46cf55-a296-4428-8cc0-e1184edcd5c9\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"7a46cf55-a296-4428-8cc0-e1184edcd5c9\"]}",
                "    [Data],",
                "  RV_trafero_semantic_canonical_regions_ = #\"7a46cf55-a296-4428-8cc0-e1184edcd5c9\"",
                "    {[entity = \"RV_trafero_semantic_canonical_regions\", version = \"\"]}",
                "    [Data]",
                "in",
                "  RV_trafero_semantic_canonical_regions_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Requested VQ",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c9dcdc82-33d3-4bfe-af03-333a3333ca18",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          },
          {
            "name": "Requested VQ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9cb75348-f0ab-46a1-9c21-eca8b0acfdb1",
            "sourceColumn": "Requested VQ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "137116b8-11bb-4a9c-b5c2-0640c7eb3e5f",
        "partitions": [
          {
            "name": "Requested VQ-f209b2dc-3fdb-42bf-a439-8448bb4d2d7e",
            "mode": "import",
            "queryGroup": "Dim\\Calls",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"cc059a8f-b367-4610-a930-22dd4415da87\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"cc059a8f-b367-4610-a930-22dd4415da87\"]}",
                "    [Data],",
                "  RV_trafero_semantic_canonical_tsc_requestedvq_ = #\"cc059a8f-b367-4610-a930-22dd4415da87\"",
                "    {[entity = \"RV_trafero_semantic_canonical_tsc_requestedvq\", version = \"\"]}",
                "    [Data],",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    RV_trafero_semantic_canonical_tsc_requestedvq_,",
                "    {{\"RequestedVQ\", \"Requested VQ\"}}",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Required Skill",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "36ea2303-340e-4b9d-a72e-8ea5689c3830",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          },
          {
            "name": "Required Skill",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3aba604b-1848-457a-8cb0-7c38d5f2cbaf",
            "sourceColumn": "Required Skill",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bca5e091-3e75-4a28-87f4-4739676ab203",
        "partitions": [
          {
            "name": "Required Skill-56646d48-7183-4f2a-98b4-846850b76364",
            "mode": "import",
            "queryGroup": "Dim\\Calls",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"72de190b-bea1-43af-832b-68f0d5e9a988\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"72de190b-bea1-43af-832b-68f0d5e9a988\"]}",
                "    [Data],",
                "  RV_trafero_semantic_canonical_tsc_requiredskill_ = #\"72de190b-bea1-43af-832b-68f0d5e9a988\"",
                "    {[entity = \"RV_trafero_semantic_canonical_tsc_requiredskill\", version = \"\"]}",
                "    [Data],",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    RV_trafero_semantic_canonical_tsc_requiredskill_,",
                "    {{\"RequiredSkill\", \"Required Skill\"}}",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Resource Role",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5818f4fa-8134-42ec-84d7-a90cc67a0221",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          },
          {
            "name": "Resource Role",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1cac8a6b-f92b-42c6-a047-77a33e51b835",
            "sourceColumn": "Resource Role",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "dbc75f82-a478-4394-98ec-a12a778caeca",
        "partitions": [
          {
            "name": "Resource Role-c094aad9-6af1-4c2b-a003-d130fba47f40",
            "mode": "import",
            "queryGroup": "Dim\\Calls",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"004d2149-76ad-4c5b-ab88-9b7be54fd389\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"004d2149-76ad-4c5b-ab88-9b7be54fd389\"]}",
                "    [Data],",
                "  RV_trafero_semantic_canonical_tsc_resourcerole_ = #\"004d2149-76ad-4c5b-ab88-9b7be54fd389\"",
                "    {[entity = \"RV_trafero_semantic_canonical_tsc_resourcerole\", version = \"\"]}",
                "    [Data],",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    RV_trafero_semantic_canonical_tsc_resourcerole_,",
                "    {{\"ResourceRole\", \"Resource Role\"}}",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Resource Type",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "31db8871-7735-4e07-a917-4071eba28014",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          },
          {
            "name": "Resource Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b658ec87-c4cd-4e6e-8363-7170655d9830",
            "sourceColumn": "Resource Type",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "24c9f31a-1ebd-48fe-9c18-8c8d18d4bbf0",
        "partitions": [
          {
            "name": "Resource Type-ff5bf0dc-2716-4445-bcdf-5141c067f441",
            "mode": "import",
            "queryGroup": "Dim\\Calls",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"6ddde07f-882c-4317-97de-84a5654a4b73\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"6ddde07f-882c-4317-97de-84a5654a4b73\"]}",
                "    [Data],",
                "  RV_trafero_semantic_canonical_tsc_resourcetype_ = #\"6ddde07f-882c-4317-97de-84a5654a4b73\"",
                "    {[entity = \"RV_trafero_semantic_canonical_tsc_resourcetype\", version = \"\"]}",
                "    [Data],",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    RV_trafero_semantic_canonical_tsc_resourcetype_,",
                "    {{\"ResourceType\", \"Resource Type\"}}",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Result Reason",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "52b4c1e4-446b-4e20-ac9c-c4743399dcd0",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          },
          {
            "name": "Result Reason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0747a56-68d2-401d-8c42-59b39c527584",
            "sourceColumn": "Result Reason",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "382eb7b3-fe50-40ef-af36-645552355003",
        "partitions": [
          {
            "name": "Result Reason-929c9134-c1f6-4279-8625-757293b1df65",
            "mode": "import",
            "queryGroup": "Dim\\Calls",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"6f70f21a-5a6e-4f67-9072-e4e6daa44f15\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"6f70f21a-5a6e-4f67-9072-e4e6daa44f15\"]}",
                "    [Data],",
                "  RV_trafero_semantic_canonical_tsc_resultreason_ = #\"6f70f21a-5a6e-4f67-9072-e4e6daa44f15\"",
                "    {[entity = \"RV_trafero_semantic_canonical_tsc_resultreason\", version = \"\"]}",
                "    [Data],",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    RV_trafero_semantic_canonical_tsc_resultreason_,",
                "    {{\"ResultReason\", \"Result Reason\"}}",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Slicers",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "isHidden": true,
        "lineageTag": "d43b3c12-ade8-4677-9556-f05f264c7927",
        "measures": [
          {
            "name": "Slicer_Highlight_ALL",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED ( 'Departments'[Employee Department])",
              "        || ISFILTERED ( Products[Products] )",
              "        || ISFILTERED ( Customers[Customer ID] )",
              "        || ISFILTERED ( Customers[Name] )",
              "        || ISFILTERED ( Customers[Enterprise Account Network Name])",
              "        || ISFILTERED ( Customers[Enterprise Account Network Parent Name])",
              "\t    || ISFILTERED ( Customers[Country])",
              "\t    || ISFILTERED ( Customers[State])",
              "\t    || ISFILTERED ( Customers[FSM Name])",
              "\t    || ISFILTERED ( Regions[Region])",
              "\t    || ISFILTERED ( Employee[Display Name])",
              "\t    || ISFILTERED ( Employee[Manager Level 1])",
              "\t    || ISFILTERED ( Employee[Manager Level 2])",
              "\t    || ISFILTERED ( Employee[Manager Level 3])",
              "\t    || ISFILTERED ( Employee[Manager Level 4])",
              "\t    || ISFILTERED ( 'Employee Site'[Employee Site])",
              "\t    || ISFILTERED ( 'Calls'[Product Category])",
              "\t    || ISFILTERED ( 'Calls'[Hardware])",
              "\t    || ISFILTERED ( 'Calls'[Queue Name])",
              "        || ISFILTERED ( 'Calls'[Direct Calls])",
              "        || ISFILTERED ( 'Calls'[Missing Wrap Up])",
              "        || ISFILTERED ( 'Calls'[Transfer Calls])      ",
              "        || ISFILTERED ( Materials[Product Hierarchy Level 3 Description])",
              "\t    || ISFILTERED ( Materials[Product Hierarchy Level 4 Description])",
              "\t    || ISFILTERED ( Materials[Product Hierarchy Level 5 Description])",
              "\t    || ISFILTERED ( 'Priority Description'[Priority Description])",
              "\t    || ISFILTERED ( 'Status Description'[Status Description])",
              "\t    || ISFILTERED ( 'Case Metrics'[Community Case Flag])",
              "\t    || ISFILTERED ( 'Cases'[Dispatch Flag])",
              "\t    || ISFILTERED ( 'Cases'[Service Request Id])",
              "\t    || ISFILTERED ( 'MLC'[Device Type])",
              "\t    || ISFILTERED ( 'MLC'[Problem Type])",
              "\t    || ISFILTERED ( 'MLC'[Symptom 1])",
              "        || ISFILTERED ( 'Complaint Type Description'[Complaint Type Description])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "cf4cdb2a-b2ec-4a5b-b78b-fdad50a411ce"
          },
          {
            "name": "Slicer_Highlight_Department",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED ( 'Departments'[Employee Department]),",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "2b1f16ad-7982-40d5-8f98-c9f8ce94c91e"
          },
          {
            "name": "Slicer_Highlight_Products",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (  Products[Products] )",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "b7ee412d-2520-4983-82b2-20f8ccce62e5"
          },
          {
            "name": "Slicer_Highlight_CustomerID",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED ( Customers[Customer ID] )",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "77b62c25-5bc9-4f89-97ff-2a0d87425ab7"
          },
          {
            "name": "Slicer_Highlight_CustomerName",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED ( Customers[Name] )",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "1924e4c7-7113-4c20-8646-fad1c4ac2d2c"
          },
          {
            "name": "Slicer_Highlight_NetworkName",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Customers[Enterprise Account Network Name])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "8719753e-10fb-4607-b58d-cadb5c359209"
          },
          {
            "name": "Slicer_Highlight_Country",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Customers[Country])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "8df561b9-7c9c-4e04-8193-b854be08026c"
          },
          {
            "name": "Slicer_Highlight_State",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Customers[State])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "c2148468-0f66-47bc-95d2-6283d2c0051c"
          },
          {
            "name": "Slicer_Highlight_FSMName",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Customers[FSM Name])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "cc42128b-06fd-4051-968b-d301aef201a8"
          },
          {
            "name": "Slicer_Highlight_ServiceRegion",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Regions[Region])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "fafcd5b3-28d0-49d4-958b-0fb0ad2cfdd4"
          },
          {
            "name": "Slicer_Highlight_Agent",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Employee[Display Name])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "b4cccb97-0d8a-49f9-9308-3ab6da490801"
          },
          {
            "name": "Slicer_Highlight_ML1",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Employee[Manager Level 1])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "8074adc2-1c6b-4cf0-9f19-5d3e14a55024"
          },
          {
            "name": "Slicer_Highlight_ML2",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Employee[Manager Level 2])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "564014ca-eb6b-4960-b16a-0629cf5a6de1"
          },
          {
            "name": "Slicer_Highlight_ML3",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Employee[Manager Level 3])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "49ff2835-fc9e-43d2-ba77-c8ec4d94c313"
          },
          {
            "name": "Slicer_Highlight_ML4",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Employee[Manager Level 3])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "3486deb7-1878-476a-a230-93b2d6a6817d"
          },
          {
            "name": "Slicer_Highlight_EmployeeSite",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED ('Employee Site'[Employee Site])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "e84d0ed4-267e-4860-8897-ddf73a9c11e0"
          },
          {
            "name": "Slicer_Highlight_PhoneSkills",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED ('Required Skill'[Required Skill])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "ad338812-941d-401c-b18d-2c93fe059069"
          },
          {
            "name": "Slicer_Highlight_Hardware",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Calls[Hardware])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "ddc2a0aa-598d-48d8-9918-d0fe987bdaaa"
          },
          {
            "name": "Slicer_Highlight_PHL3",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Materials[Product Hierarchy Level 3 Description])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "fe338743-0492-43fa-91bf-7b1737b6ff60"
          },
          {
            "name": "Slicer_Highlight_PHL4",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Materials[Product Hierarchy Level 4 Description])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "821c4ea8-217b-47d1-84bb-6f56724ec54e"
          },
          {
            "name": "Slicer_Highlight_PHL5",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Materials[Product Hierarchy Level 5 Description])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "21680c27-c495-43ce-80b4-8fbf1aa7f36d"
          },
          {
            "name": "Slicer_Highlight_PriorityDescription",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED ('Priority Description'[Priority Description])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "feef52aa-d20b-4824-865b-fa4ed68b9bf9"
          },
          {
            "name": "Slicer_Highlight_StatusDescription",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED ('Status Description'[Status Description])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "638e19e0-03be-4ccd-9d5d-6dc9a0e912f4"
          },
          {
            "name": "Slicer_Highlight_CommunityCaseFlag",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED ('Case Metrics'[Community Case Flag])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "7464f254-f4b2-4cee-a353-45d6fdfd2786"
          },
          {
            "name": "Slicer_Highlight_DispatchFlag",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED ('Cases'[Dispatch Flag])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "1f947765-a96d-442c-8c1f-0b30baec6410"
          },
          {
            "name": "Slicer_Highlight_ServiceRequestID",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED ('Case Metrics'[Service Request ID])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "91ae5fce-f72e-4b49-878b-0936db9761e8"
          },
          {
            "name": "Slicer_Highlight_DeviceType",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (MLC[Device Type])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "3b83b44d-d411-4fe5-a4dc-453056ff0dd4"
          },
          {
            "name": "Slicer_Highlight_ProblemType",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (MLC[Problem Type])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "9c4d3f20-01fd-41a1-8d63-fc3b91663c16"
          },
          {
            "name": "Slicer_Highlight_Symptom1",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (MLC[Symptom 1])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "1e399b9b-de7f-46f9-b432-cafdd18e84bb"
          },
          {
            "name": "Slicer_Highlight_ComplaintTypeDescription",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED ('Complaint Type Description'[Complaint Type Description])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "35e3182a-7314-49bd-8d43-5cf6f157d4d3"
          },
          {
            "name": "SlicerCheckFact",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "INT (",
              "        NOT ISEMPTY ('Calls')",
              "        ||",
              "        NOT ISEMPTY('Cases')",
              "//      ||",
              "//        NOT ISEMPTY('Case Metrics')",
              "//       ||",
              "//       NOT ISEMPTY('Agent Metrics by Day')",
              ")"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "327d47b7-814e-4cac-a6e6-6cdb111833db"
          },
          {
            "name": "Slicer_Highlight_NetworkParetnName",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Customers[Enterprise Account Network Parent Name])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "f2ba7169-2adc-42db-8e41-7b6175518024"
          },
          {
            "name": "Slicer_Highlight_CategoryCodeDescription",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED ('Category Code Description'[Category Code Description])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "dfa7ff81-14c1-4780-8e7d-ed223e8f0bbf"
          },
          {
            "name": "Slicer_Highlight_ClassificationDescription",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Customers[Classification Description])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "2912f395-20b6-4e44-bed7-ef6cac2a282e"
          },
          {
            "name": "Slicer_Highlight_Queue",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Calls[Queue Name])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "b9fe745c-6ac2-4748-8dea-41ff06dabfab"
          },
          {
            "name": "Slicer_Highlight_Direct",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Calls[Direct Calls])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "85bf1d7f-6f36-4ba2-8c19-92b84b8488c3"
          },
          {
            "name": "Slicer_Highlight_MissingWrapUp",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Calls[Missing Wrap Up])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "1aa76854-bdc9-4edb-9e05-b219d51f3cbb"
          },
          {
            "name": "Slicer_Highlight_TrasferCalls",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF (",
              "    ISFILTERED (Calls[Transfer Calls])",
              "\t,",
              "    \"#F27707\",",
              "    \"#E6E7E9\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "82a3aca0-aeaa-4805-bee4-d57ea45fe1aa"
          }
        ],
        "partitions": [
          {
            "name": "Slicers-f66c03a3-505a-4948-938f-659f314f1935",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "  Source = Table.FromRows(",
                "    Json.Document(",
                "      Binary.Decompress(Binary.FromText(\"i45WMlSKjQUA\", BinaryEncoding.Base64), Compression.Deflate)",
                "    ),",
                "    let",
                "      _t = ((type nullable text) meta [Serialized.Text = true])",
                "    in",
                "      type table [Column1 = _t]",
                "  ),",
                "  #\"Changed Type\" = Table.TransformColumnTypes(Source, {{\"Column1\", Int64.Type}}),",
                "  #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\", {\"Column1\"})",
                "in",
                "  #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Status Description",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6e828490-cd6d-4860-b518-85a7e30e776c",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          },
          {
            "name": "Status Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4af2a679-7bb8-47a7-86e6-a77bf3b303be",
            "sourceColumn": "Status Description",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f7f330c3-cf60-421e-b9a7-7eb0ae46c8af",
        "partitions": [
          {
            "name": "Status Description-7bff3d3b-76c6-4df0-84c1-f2f50b893bd7",
            "mode": "import",
            "queryGroup": "Dim\\Cases",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"bd4a56dd-2f40-4e99-9437-1a2c29d5e169\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"bd4a56dd-2f40-4e99-9437-1a2c29d5e169\"]}",
                "    [Data],",
                "  RV_trafero_semantic_canonical_tsc_statusdescription_ = #\"bd4a56dd-2f40-4e99-9437-1a2c29d5e169\"",
                "    {[entity = \"RV_trafero_semantic_canonical_tsc_statusdescription\", version = \"\"]}",
                "    [Data],",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    RV_trafero_semantic_canonical_tsc_statusdescription_,",
                "    {{\"StatusDescription\", \"Status Description\"}}",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Technical Result",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c6090ec7-ea81-49a1-8bff-949b1b2a6db9",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          },
          {
            "name": "Technical Result",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09818210-3382-4f86-929a-324fec2628c9",
            "sourceColumn": "Technical Result",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1d6ab41b-c91c-4b56-9d24-1815b833c1c0",
        "partitions": [
          {
            "name": "Technical Result-54e0594b-52fa-45b5-b7c2-b4c95e64fe25",
            "mode": "import",
            "queryGroup": "Dim\\Calls",
            "source": {
              "expression": [
                "let",
                "  Source = PowerPlatform.Dataflows(null),",
                "  Workspaces = Source{[Id = \"Workspaces\"]}[Data],",
                "  #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces",
                "    {[workspaceId = \"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}",
                "    [Data],",
                "  #\"3032041a-61e6-4eba-b36b-a15d8ddce900\" = #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"",
                "    {[dataflowId = \"3032041a-61e6-4eba-b36b-a15d8ddce900\"]}",
                "    [Data],",
                "  RV_trafero_semantic_canonical_tsc_technicalresult_ = #\"3032041a-61e6-4eba-b36b-a15d8ddce900\"",
                "    {[entity = \"RV_trafero_semantic_canonical_tsc_technicalresult\", version = \"\"]}",
                "    [Data],",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    RV_trafero_semantic_canonical_tsc_technicalresult_,",
                "    {{\"TechnicalResult\", \"Technical Result\"}}",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Transaction Dates",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Calendar Date Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e7423390-8347-4bc9-a98b-ecfe84bc4714",
            "sourceColumn": "Calendar Date Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Date Weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97f2dd25-2021-438c-803e-72b76b25fcff",
            "sourceColumn": "Calendar Date Weekday",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Days in Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8e3421cf-0a00-45c1-8626-4289c95b626a",
            "sourceColumn": "Calendar Days in Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f59bcc8-dbd2-4a0f-b80a-35fddb61f1f7",
            "sortByColumn": "Fiscal Month Number",
            "sourceColumn": "Calendar Month",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5873a32b-9218-43ca-82f5-12ae3d286bb2",
            "sourceColumn": "Calendar Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "276ef3f6-22af-43c4-b01a-2a2f899b3e67",
            "sourceColumn": "Calendar Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6e5d7de1-a6ec-48fe-b3b8-85d47419e04e",
            "sourceColumn": "Calendar Quarter Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Year Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1aa90351-8822-4cc2-bd44-3c8763e318d1",
            "sourceColumn": "Calendar Year Month",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Year Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d1e79632-4bb4-4d5c-ba44-ea7a3986d578",
            "sourceColumn": "Calendar Year Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isKey": true,
            "lineageTag": "8a4eda05-dc4f-48b8-8edd-c72c5c950f46",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Date of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c589eb36-d087-41a9-b744-331ce3a2538e",
            "sourceColumn": "Date of Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Date yyyymm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1b02a82c-b808-4d58-8882-d239ac7dae2a",
            "sourceColumn": "Date yyyymm",
            "summarizeBy": "sum"
          },
          {
            "name": "Date yyyymmdd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0e7835cf-1ee7-471b-9d86-d79bb78c6b03",
            "sourceColumn": "Date yyyymmdd",
            "summarizeBy": "sum"
          },
          {
            "name": "Day of Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d0b72407-b133-461e-be84-4dd36af24b0e",
            "sourceColumn": "Day of Week Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Day of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ab634ffc-6ba2-451e-a57f-de7c064bb105",
            "sourceColumn": "Day of Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Days in Month Past",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7165b004-ae95-404c-a39c-0bf6d2bf434c",
            "sourceColumn": "Days in Month Past",
            "summarizeBy": "sum"
          },
          {
            "name": "Days in Month Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7778be28-ee83-487a-9400-d903d2d0c7de",
            "sourceColumn": "Days in Month Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "FY Neg",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b85d878-518f-4028-9944-1575d3037c96",
            "sourceColumn": "FY Neg",
            "summarizeBy": "none"
          },
          {
            "name": "FY Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed7e8d07-4702-4371-8497-8ebc37c1b845",
            "sourceColumn": "FY Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "FYYYMonthSort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "71f6a504-805f-4493-b257-0f74f182af6e",
            "sourceColumn": "FYYYMonthSort",
            "summarizeBy": "sum"
          },
          {
            "name": "FYYYY Month Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "'Transaction Dates'[Fiscal Year] & \"-\"",
              "    & FORMAT ( MONTH ( 'Transaction Dates'[Date] ), \"00\" ) & \"-\"",
              "    & FORMAT ( DAY ( 'Transaction Dates'[Date] ), \"00\" )",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "c3591a64-b466-4e6a-9429-2e97d8a6bccb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "FYYYY Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6377e9f-1530-4219-be20-742641d447b9",
            "sortByColumn": "FYYYYMM",
            "sourceColumn": "FYYYY Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "FYYYY Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a9c83fd-689f-4cfd-ba7b-a58e0fb94c98",
            "sourceColumn": "FYYYY Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "FYYYY Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "'Transaction Dates'[Fiscal Year Name] & \"-\"",
              "    & FORMAT ( WEEKNUM ( 'Transaction Dates'[Date] ), \"00\" )",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "ec947b9e-a778-4409-871b-1961a050dc62",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "FYYYYMM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "'Transaction Dates'[Fiscal Year] * 100 + 'Transaction Dates'[Fiscal Month Number]",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "65f41606-f41f-42db-af73-13c9fe3ff3f3",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "First Date of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d132f50a-42c0-4e96-aa46-575d9e3f3441",
            "sourceColumn": "First Date of Month",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c38a4caf-13fd-462f-b595-a1fd91555fe6",
            "sourceColumn": "Fiscal Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "d61124ab-67f9-4022-8036-6e099b238c63",
            "sortByColumn": "Fiscal Quarter Number",
            "sourceColumn": "Fiscal Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a9af70e2-0c68-4890-9d83-14ccb7027a91",
            "sourceColumn": "Fiscal Quarter Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6d0f82ab-7b1b-4d82-aece-3d5ab028ab05",
            "sortByColumn": "FY Neg",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b95df44-3ac6-4bf9-ac03-f48a9e70514f",
            "sourceColumn": "Fiscal Year Month",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2f9f5b4-2f1a-4932-8a96-3c07d0d9eafc",
            "sourceColumn": "Fiscal Year Name",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year Negative",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "'Transaction Dates'[Fiscal Year] * -1",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "ca0b964e-74cc-45f9-b032-965836a1f575",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Fiscal Year Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5640d1ea-e645-4a2e-893e-18416d8a7ed2",
            "sourceColumn": "Fiscal Year Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Julian Date JDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "64d3fe97-c561-4b42-9248-6f6a54926616",
            "sourceColumn": "Julian Date JDE",
            "summarizeBy": "sum"
          },
          {
            "name": "Julian Date STD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a03ac675-3999-4441-bd2b-9890f701a1e6",
            "sourceColumn": "Julian Date STD",
            "summarizeBy": "sum"
          },
          {
            "name": "calendar_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1287bcaa-b50e-4c06-9058-3126ea5c31bf",
            "sourceColumn": "calendar_date",
            "summarizeBy": "none"
          },
          {
            "name": "calendaryear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fe555c22-a730-4010-a4bb-ceaad0aa9e32",
            "sourceColumn": "calendaryear",
            "summarizeBy": "sum"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Calendar Hierarchy",
            "levels": [
              {
                "name": "Fiscal Year Name",
                "column": "Fiscal Year Name",
                "lineageTag": "d35677fe-c4f9-4670-b036-0469f0553179",
                "ordinal": 0
              },
              {
                "name": "FYYYY Quarter",
                "column": "FYYYY Quarter",
                "lineageTag": "313768e9-dd84-4993-9ccb-bf55285e9cb3",
                "ordinal": 1
              },
              {
                "name": "FYYYY Month Name",
                "column": "FYYYY Month Name",
                "lineageTag": "c0a61ff8-1fa6-4ae5-8c03-a473f4e90d9b",
                "ordinal": 2
              },
              {
                "name": "FYYYY Week Number",
                "column": "FYYYY Week Number",
                "lineageTag": "6132b906-140d-4456-80ab-58ac2fa83e19",
                "ordinal": 3
              },
              {
                "name": "Date",
                "column": "Date",
                "lineageTag": "80cfde5e-ffd0-4fd0-a4d6-cdd89d783751",
                "ordinal": 4
              }
            ],
            "lineageTag": "39895556-03b7-43b5-9291-ab37350b9fe1"
          }
        ],
        "lineageTag": "f0e4afd2-1836-47a2-bd08-4abfa5083470",
        "partitions": [
          {
            "name": "Transaction Dates-f020c1b6-07ab-44fd-abfc-45aec3ff2ee9",
            "mode": "import",
            "queryGroup": "Dim\\Common",
            "source": {
              "expression": [
                "let",
                "  Source = DateList(#\"StartDate\", Number.From(#\"Today\" - #\"StartDate\"), #duration(1, 0, 0, 0)),",
                "  #\"Converted to Table\" = Table.FromList(",
                "    Source,",
                "    Splitter.SplitByNothing(),",
                "    null,",
                "    null,",
                "    ExtraValues.Error",
                "  ),",
                "  #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\", {{\"Column1\", \"Date\"}}),",
                "  #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Date\", type date}}),",
                "  #\"Merged Queries\" = Table.NestedJoin(",
                "    #\"Changed Type\",",
                "    {\"Date\"},",
                "    RV_canonical_calendar,",
                "    {\"calendar_date\"},",
                "    \"RV_canonical_calendar\",",
                "    JoinKind.Inner",
                "  ),",
                "  #\"Expanded RV_canonical_calendar\" = Table.ExpandTableColumn(",
                "    #\"Merged Queries\",",
                "    \"RV_canonical_calendar\",",
                "    {",
                "      \"date_yyyymmdd\",",
                "      \"calendar_date\",",
                "      \"first_date_of_month\",",
                "      \"calendaryear\",",
                "      \"fiscal_year\",",
                "      \"calendar_quarter_num\",",
                "      \"fiscal_quarter_num\",",
                "      \"calendar_quarter\",",
                "      \"fiscal_quarter\",",
                "      \"calendar_month_num\",",
                "      \"fiscal_month_num\",",
                "      \"calendar_month\",",
                "      \"calendar_date_weekday\",",
                "      \"date_of_month\",",
                "      \"day_of_week_number\",",
                "      \"days_in_month_remaining\",",
                "      \"days_in_month_past\",",
                "      \"calendar_days_in_month\",",
                "      \"calendar_date_number\",",
                "      \"day_of_year\",",
                "      \"julian_date_jde\",",
                "      \"julian_date_std\",",
                "      \"date_yyyymm\",",
                "      \"fiscal_year_month\",",
                "      \"calendar_year_month\",",
                "      \"fiscal_year_quarter\",",
                "      \"calendar_year_quarter\",",
                "      \"fiscal_year_name\",",
                "      \"fy_quarter\",",
                "      \"fyyyy_month_name\",",
                "      \"fyyyy_quarter\"",
                "    },",
                "    {",
                "      \"date_yyyymmdd\",",
                "      \"calendar_date\",",
                "      \"first_date_of_month\",",
                "      \"calendaryear\",",
                "      \"fiscal_year\",",
                "      \"calendar_quarter_num\",",
                "      \"fiscal_quarter_num\",",
                "      \"calendar_quarter\",",
                "      \"fiscal_quarter\",",
                "      \"calendar_month_num\",",
                "      \"fiscal_month_num\",",
                "      \"calendar_month\",",
                "      \"calendar_date_weekday\",",
                "      \"date_of_month\",",
                "      \"day_of_week_number\",",
                "      \"days_in_month_remaining\",",
                "      \"days_in_month_past\",",
                "      \"calendar_days_in_month\",",
                "      \"calendar_date_number\",",
                "      \"day_of_year\",",
                "      \"julian_date_jde\",",
                "      \"julian_date_std\",",
                "      \"date_yyyymm\",",
                "      \"fiscal_year_month\",",
                "      \"calendar_year_month\",",
                "      \"fiscal_year_quarter\",",
                "      \"calendar_year_quarter\",",
                "      \"fiscal_year_name\",",
                "      \"fy_quarter\",",
                "      \"fyyyy_month_name\",",
                "      \"fyyyy_quarter\"",
                "    }",
                "  ),",
                "  #\"Removed Other Columns\" = Table.SelectColumns(",
                "    #\"Expanded RV_canonical_calendar\",",
                "    {",
                "      \"Date\",",
                "      \"date_yyyymmdd\",",
                "      \"calendar_date\",",
                "      \"first_date_of_month\",",
                "      \"calendaryear\",",
                "      \"fiscal_year\",",
                "      \"calendar_quarter_num\",",
                "      \"fiscal_quarter_num\",",
                "      \"calendar_quarter\",",
                "      \"fiscal_quarter\",",
                "      \"calendar_month_num\",",
                "      \"fiscal_month_num\",",
                "      \"calendar_month\",",
                "      \"calendar_date_weekday\",",
                "      \"date_of_month\",",
                "      \"day_of_week_number\",",
                "      \"days_in_month_remaining\",",
                "      \"days_in_month_past\",",
                "      \"calendar_days_in_month\",",
                "      \"calendar_date_number\",",
                "      \"day_of_year\",",
                "      \"julian_date_jde\",",
                "      \"julian_date_std\",",
                "      \"date_yyyymm\",",
                "      \"fiscal_year_month\",",
                "      \"calendar_year_month\",",
                "      \"fiscal_year_quarter\",",
                "      \"calendar_year_quarter\",",
                "      \"fiscal_year_name\",",
                "      \"fy_quarter\",",
                "      \"fyyyy_month_name\",",
                "      \"fyyyy_quarter\"",
                "    }",
                "  ),",
                "  #\"Renamed Columns2\" = Table.RenameColumns(",
                "    #\"Removed Other Columns\",",
                "    {",
                "      {\"calendar_date_number\", \"Calendar Date Number\"},",
                "      {\"calendar_date_weekday\", \"Calendar Date Weekday\"},",
                "      {\"calendar_days_in_month\", \"Calendar Days in Month\"},",
                "      {\"calendar_month\", \"Calendar Month\"},",
                "      {\"calendar_month_num\", \"Calendar Month Number\"},",
                "      {\"calendar_quarter\", \"Calendar Quarter\"},",
                "      {\"calendar_quarter_num\", \"Calendar Quarter Number\"},",
                "      {\"calendar_year_month\", \"Calendar Year Month\"},",
                "      {\"calendar_year_quarter\", \"Calendar Year Quarter\"},",
                "      {\"date_of_month\", \"Date of Month\"},",
                "      {\"date_yyyymm\", \"Date yyyymm\"},",
                "      {\"date_yyyymmdd\", \"Date yyyymmdd\"},",
                "      {\"day_of_week_number\", \"Day of Week Number\"},",
                "      {\"day_of_year\", \"Day of Year\"},",
                "      {\"days_in_month_past\", \"Days in Month Past\"},",
                "      {\"days_in_month_remaining\", \"Days in Month Remaining\"},",
                "      {\"first_date_of_month\", \"First Date of Month\"},",
                "      {\"fiscal_month_num\", \"Fiscal Month Number\"},",
                "      {\"fiscal_quarter\", \"Fiscal Quarter\"},",
                "      {\"fiscal_quarter_num\", \"Fiscal Quarter Number\"},",
                "      {\"fiscal_year\", \"Fiscal Year\"},",
                "      {\"fiscal_year_month\", \"Fiscal Year Month\"},",
                "      {\"fiscal_year_name\", \"Fiscal Year Name\"},",
                "      {\"fiscal_year_quarter\", \"Fiscal Year Quarter\"},",
                "      {\"fy_quarter\", \"FY Quarter\"},",
                "      {\"fyyyy_month_name\", \"FYYYY Month Name\"},",
                "      {\"fyyyy_quarter\", \"FYYYY Quarter\"},",
                "      {\"julian_date_jde\", \"Julian Date JDE\"},",
                "      {\"julian_date_std\", \"Julian Date STD\"}",
                "    }",
                "  ),",
                "  #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns2\", \"FY Neg\", each [Fiscal Year] * - 1),",
                "  #\"Added Custom1\" = Table.AddColumn(",
                "    #\"Added Custom\",",
                "    \"FYYYMonthSort\",",
                "    each Number.From(Text.From([Fiscal Year]) & Text.From([Fiscal Month Number]))",
                "  ),",
                "  #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom1\", {{\"FYYYMonthSort\", Int64.Type}})",
                "in",
                "  #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "WaitDurations for ASA Calculations",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "65b117f48d0d4b3f93db3b823ac2d743"
          }
        ],
        "columns": [
          {
            "name": "Call Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b60c19da-6466-4f8c-8d53-3a2ea251ab4c",
            "sourceColumn": "Calls[Call Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Interaction ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5c1826a2-3bd0-4c0f-b50e-b91601d1c4df",
            "sourceColumn": "Calls[Interaction ID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Wait Duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "36cd67aa-0d05-441c-a9bc-33fce9f81617",
            "sourceColumn": "Calls[Wait Duration]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Wait Duration (Formatted)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "hh:nn:ss",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5cace52d-d3c2-4fc7-b639-4077aaf3ad8b",
            "sourceColumn": "Calls[Wait Duration (Formatted)]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "0ab2031e-3d9d-4385-9945-b5c0bdcf7a4f",
        "partitions": [
          {
            "name": "WaitDurations for ASA Calculations-d54abb7b-dc76-4730-95f2-7004b74b8f0f",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZECOLUMNS (",
                "    Calls[Wait Duration],",
                "    Calls[Wait Duration (Formatted)],",
                "    Calls[Call Date],",
                "    Calls[Interaction ID],",
                "    KEEPFILTERS ( TREATAS ( { \"Inbound\" }, 'Interaction Type'[InteractionType] ) ),",
                "    KEEPFILTERS ( TREATAS ( { 1 }, Calls[Calls Answered] ) )",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_aht_01_primaryproductgroup",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f95c01e2cdcb4168ac149b6a7a1cdbc4"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "TRIM ( REPLACE ( dl_aht_01_primaryproductgroup[CategoryValueIndex], 1, 5, \"\" ) )",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ed6afdd2-cafa-46b5-8ceb-d5625016590d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "7a55709f-2d28-437e-a41b-6ed38abfa2b4",
            "sourceColumn": "Agent Metrics by Day[PPG]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "\"Primary Product Group\"",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "775f7975-c7e4-4fa2-bb86-78e8fea110ad",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "1",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bc76cf37-d997-4357-9534-ae0470e8d2f5",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "c9a7b7c1-8c11-4e0b-a3c5-f50cf0890b82",
        "partitions": [
          {
            "name": "dl_aht_01_primaryproductgroup-aaf8f712-2fd2-4239-92d0-f333e94a9c39",
            "mode": "import",
            "source": {
              "expression": [
                "SUMMARIZECOLUMNS(",
                "    'Agent Metrics by Day'[PPG],",
                "    KEEPFILTERS( FILTER( ALL( 'Agent Metrics by Day'[PPG] ), NOT( ISBLANK( 'Agent Metrics by Day'[PPG] ))))",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_aht_02_primaryproduct",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "6a726c89e45549f48589ee172e8b30e5"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "TRIM ( REPLACE ( dl_aht_02_primaryproduct[CategoryValueIndex], 1, 4, \"\" ) )",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "30bbbc0b-524b-48df-8634-fef0d8c4cd84",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "df51d597-6f80-47db-93fb-e9de04454212",
            "sourceColumn": "Agent Metrics by Day[PP]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "\"Primary Product\"",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "46269bf9-44df-4684-82d6-6217d8aa58a0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "2",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "15cbe582-9d9e-4201-beac-4f0b2dcb5d3b",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "2b50c27c-2b41-4bd8-adce-acc6b1f27b6d",
        "partitions": [
          {
            "name": "dl_aht_02_primaryproduct-dbc06934-6cff-43b8-a7e9-43be32604f0c",
            "mode": "import",
            "source": {
              "expression": [
                "SUMMARIZECOLUMNS(",
                "    'Agent Metrics by Day'[PP],",
                "    KEEPFILTERS( FILTER( ALL( 'Agent Metrics by Day'[PP] ), NOT( ISBLANK( 'Agent Metrics by Day'[PP] ))))",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_calls_00_queuename",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e0d8d2f600df4f8b9f880eeaa1119e60"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "LEFT (",
              "    dl_calls_00_queuename[CategoryValueIndex],",
              "    SEARCH ( \"(\", dl_calls_00_queuename[CategoryValueIndex], 1 ) - 2",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "eb0f0e44-3efc-43e7-a401-c670f2cf01ea",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "d59f5724-e58c-4afb-b9aa-6e6b67b3b81e",
            "sourceColumn": "Calls[QueueNameIndex]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "\"Queue\"",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8fbff9f7-c5a8-4977-aa2e-7d6a37d2b483",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "0",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "01974a75-b918-4f47-b37a-fe4232a3e3a4",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "0beee221-d32d-4c9a-9417-0bac8c134273",
        "partitions": [
          {
            "name": "dl_calls_00_queuename-c5e03742-f2aa-41f0-9c0e-d9c45b5d26c1",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZECOLUMNS ( Calls[QueueNameIndex] )",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_calls_01_productcategory",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "6b5a429adc334b459004447661cbd27b"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "dl_calls_01_productcategory[CategoryValueIndex]",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a38f1473-329b-4e22-9669-9c80a8fe864b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "e3c364ba-d09a-4c50-b189-75c49bba12ba",
            "sourceColumn": "Calls[Product Category]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "\"Product\"",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3bbfed5b-2132-4ac8-b0a2-7117cfd1824d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "1",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d9af2fc4-c892-4b70-8f14-b77777374576",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "7898888b-fb60-426d-8055-ff4f50b8ff50",
        "partitions": [
          {
            "name": "dl_calls_01_productcategory-0237527d-3a23-4005-99f2-eb0edda19a20",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZECOLUMNS ( Calls[Product Category] )",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_calls_02_skill",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3efa8871557147748ffec79e4b8c7210"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "LEFT (",
              "    dl_calls_02_skill[CategoryValueIndex],",
              "    SEARCH ( \"(\", dl_calls_02_skill[CategoryValueIndex], 1 ) - 2",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a1e6ec70-6a70-425d-b141-b33440470a6c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "bb50de44-d97f-4e8f-b8cd-5d7f37a2edb9",
            "sourceColumn": "Calls[Skills]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Filed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "\"Skill\"",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a97c525f-fa7d-4aaa-99d2-733d1aef4c35",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "2",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0118e03b-dd5d-4470-8ab6-a71ba01f9354",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "021ebd53-7edf-4c61-a9ef-2e3ddd3f140b",
        "partitions": [
          {
            "name": "dl_calls_02_skill-809a27c2-3db8-41c2-86b7-a8a2f57bf326",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZECOLUMNS (",
                "    Calls[Skills],",
                "    KEEPFILTERS (",
                "        FILTER (",
                "            ALL ( Calls[Actual Product Skill] ),",
                "            NOT ( ISBLANK ( Calls[Actual Product Skill] ) )",
                "        )",
                "    )",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_calls_03_mgr1",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f4fc49d6ba6d41308a0be7abe44e8e95"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "TRIM ( REPLACE ( dl_calls_03_mgr1[CategoryValueIndex], 1, 6, \"\" ) )",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "33625718-e504-45d5-a977-4511f621389b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "255d15f7-6347-475c-a757-c70befb76d10",
            "sourceColumn": "Employee[Mgr1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "\"Mngr Level 1\"",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e15ba429-e6e7-4a6f-bab8-4da57d642d82",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "3",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9dec9688-5337-4018-bb0a-78c593d37737",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "a5ac232b-0843-4ebc-9387-2a5ec94bc466",
        "partitions": [
          {
            "name": "dl_calls_03_mgr1-7a4050f5-3bb1-43f2-a0f3-f1a2a704d92e",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZECOLUMNS (",
                "    Employee[Mgr1],",
                "    KEEPFILTERS (",
                "        FILTER (",
                "            ALL ( Employee[Manager Level 1] ),",
                "            (",
                "                NOT ( ISBLANK ( Employee[Manager Level 1] ) )",
                "                    && LEN ( Employee[Manager Level 1] ) <> 0",
                "            )",
                "        )",
                "    )",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_calls_04_agent",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "08ca834af4e44d5f8d7ce9307fa237bd"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "LEFT (",
              "    dl_calls_04_agent[CategoryValueIndex],",
              "    SEARCH ( \"(\", dl_calls_04_agent[CategoryValueIndex], 1 ) - 2",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3cd5cb66-2484-4027-b00f-14cc4f3fd76b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "110782bc-0610-4477-a8cc-f56d44932cc8",
            "sourceColumn": "Employee[Agent (EmployeeID)]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "\"Agent\"",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "55a92a2f-2220-44a7-ae6e-6f8de0c173dc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "4",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5c4bdc70-b6d7-4d35-9eaf-a5759440eccd",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "5dfc9486-6ee7-4d3c-82a9-ed28772088d7",
        "partitions": [
          {
            "name": "dl_calls_04_agent-f463f035-f922-453e-8731-46529200cb41",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZECOLUMNS (",
                "    Employee[Agent (EmployeeID)],",
                "    KEEPFILTERS (",
                "        FILTER (",
                "            ALL ( Employee[Agent (EmployeeID)] ),",
                "            NOT ( ISBLANK ( Employee[Agent (EmployeeID)] ) )",
                "        )",
                "    )",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_cases_01_productcategory",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "26589483020a41669027918f4d1c623a"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "dl_cases_01_productcategory[CategoryValueIndex]",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "001e2d38-fed3-44b5-a952-90171f8db790",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "99779c59-773e-44c2-8bb2-e767176a1bcc",
            "sourceColumn": "Case Metrics[Product]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "\"Product\"",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9bddf781-3203-4243-b2ef-e1575d93ac73",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "1",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b2033cd0-5924-46cc-a154-ed62a2c1c526",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "660a6767-2729-4690-b889-4d97989394e7",
        "partitions": [
          {
            "name": "dl_cases_01_productcategory-17851149-5ba7-4cbd-9880-97f6311b7d58",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZECOLUMNS (",
                "    'Case Metrics'[Product],",
                "    KEEPFILTERS (",
                "        FILTER (",
                "            ALL ( 'Case Metrics'[Product] ),",
                "            NOT ( ISBLANK ( 'Case Metrics'[Product] ) )",
                "        )",
                "    )",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_cases_02_category",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "39d29daf91e24ef1a5d06b3df4b101a9"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "dl_cases_02_category[CategroyValueIndex]",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9c13b6b3-3a96-4c5f-9893-1fd849d5921d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CategroyValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "4348640d-a162-46f2-a0c9-66cefc2f0fea",
            "sourceColumn": "Category Code Description[Category Code Description]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "\"Category\"",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "aa9ce991-506e-4160-9e30-27f63c9961ee",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "2",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "39fe3f14-a0c8-495e-99cd-fafb8345c758",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "1b5708fb-02d1-460b-933a-e5e159bb9a3a",
        "partitions": [
          {
            "name": "dl_cases_02_category-a5a0eae1-02ad-4d17-97fe-ae217aa4e56a",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZECOLUMNS (",
                "    'Category Code Description'[Category Code Description],",
                "    KEEPFILTERS (",
                "        FILTER (",
                "            ALL ( 'Category Code Description'[Category Code Description] ),",
                "            NOT ( ISBLANK ( 'Category Code Description'[Category Code Description] ) )",
                "        )",
                "    )",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_cases_03_priority",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c2f70fdd8a0b427c970d0c43c9ac9b26"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "dl_cases_03_priority[CategroyValueIndex]",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a2e6d06d-ca09-4c4f-a02d-a65069ddd48d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CategroyValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "02b5bcd5-3975-47c0-9297-94dd5def6d6c",
            "sourceColumn": "Priority Description[Priority Description]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "\"Priority\"",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "df78a3cd-3fc9-4382-9e45-d7ee241c3862",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "3",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cf26d765-4b40-4cc9-a6bb-bbefbea7dc19",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "51c067b1-f086-466b-874c-2e7ebd5ae74e",
        "partitions": [
          {
            "name": "dl_cases_03_priority-37882cd7-f8c2-4a54-a793-8086e7ba6af0",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZECOLUMNS (",
                "    'Priority Description'[Priority Description],",
                "    KEEPFILTERS (",
                "        FILTER (",
                "            ALL ( 'Priority Description'[Priority Description] ),",
                "            NOT ( ISBLANK ( 'Priority Description'[Priority Description] ) )",
                "        )",
                "    )",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_cases_04_community",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3a81a09945564a48b199cc7f5af60c19"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "dl_cases_04_community[CategoryValueIndex]",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "065ddc52-fcf8-4515-a1c8-fa45f61eaa63",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "3a81ef74-4bc1-4c33-a308-7f50c3c66145",
            "sourceColumn": "Case Metrics[Community Case Flag]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "\"Community\"",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4e0e6708-d58e-408c-811a-3d8d3db3b20f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "4",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b37b7ade-373d-42fc-bb9b-ed584aeb2f3a",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "a39f2eb2-3342-4166-b676-a6343d3f723d",
        "partitions": [
          {
            "name": "dl_cases_04_community-368ac658-9342-4231-a4e7-264538ee191d",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZECOLUMNS (",
                "    'Case Metrics'[Community Case Flag],",
                "    KEEPFILTERS (",
                "        FILTER (",
                "            ALL ( 'Case Metrics'[Community Case Flag] ),",
                "            NOT ( ISBLANK ( 'Case Metrics'[Community Case Flag] ) )",
                "        )",
                "    )",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_cases_05_phl4",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b25fd5a50f714f1a822280e9194878da"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "44d6a7eb-4868-4a0c-ba8e-145f61852dfb",
            "sourceColumn": "dl_cases_05_phl4*[CategoryValue]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5e794bef-ccb6-497d-ad38-b2e8197cec70",
            "sourceColumn": "dl_cases_05_phl4*[CategoryValueIndex]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c3b72151-2627-45a3-89e4-bb8c608cb144",
            "sourceColumn": "dl_cases_05_phl4*[Field]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f26d2efe-cd17-4bd6-9400-4b22a4efc21f",
            "sourceColumn": "dl_cases_05_phl4*[Sort]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "6a1bc94d-75ea-438b-b300-55c5daedddd8",
        "partitions": [
          {
            "name": "dl_cases_05_phl4-c8743c4f-936f-43f7-b866-da38ba1eb51f",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "UNION ( 'dl_cases_05_phl4*', 'dl_cases_05_phl4_NULLs' )",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_cases_05_phl4*",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d13782331c2942319202d881c21d59c6"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "TRIM ( REPLACE ( 'dl_cases_05_phl4*'[CategoryValueIndex], 1, 6, \"\" ) )",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2ae51248-f04c-40c2-a2dd-2585f2c0d27d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "156ccfac-866e-4256-8d24-8eab7c22c8d3",
            "sourceColumn": "Materials[PHL4]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "\"PHL4\"",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ee9bfbc4-c3af-4961-ab17-dba540befa09",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "5",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "efd98843-1bd6-457f-92f1-7d2ec6d1efd2",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "970255d7-98e8-42b3-9b09-c4ea68db3ba6",
        "partitions": [
          {
            "name": "dl_cases_05_phl4*-6a433937-f8a2-4645-8a40-e734d7d2f8b8",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZECOLUMNS (",
                "    Materials[PHL4],",
                "    KEEPFILTERS (",
                "        FILTER ( ALL ( Materials[PHL4] ), NOT ( ISBLANK ( Materials[PHL4] ) ) )",
                "    )",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_cases_05_phl4_NULLs",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f02103ca5d564329a2065738ffe5466c"
          }
        ],
        "columns": [
          {
            "name": "Value1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "df115646-843b-42fd-9fce-a600d0574abf",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b7febbc8-53d7-4e02-ba0f-057827537875",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "13a7db0f-83ac-4960-af71-436dfb750063",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0bb1315d-e9ec-41f4-b2c0-92307c17e2c9",
            "sourceColumn": "[Value4]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "53aa0a5f-a0f5-4bf3-ae85-ecf013fcf1f9",
        "partitions": [
          {
            "name": "dl_cases_05_phl4_NULLs-7517741a-40be-41c8-8288-3a64ac748821",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "{ ( \"PHL4 - NULL\", \"PHL4\", 5, \"PHL4 - NULL\" ) }",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_cases_06_phl5",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b00e8d3fb1b8494589cdd7930b246f57"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "40349390-8e84-4e12-b9cc-858567065a6f",
            "sourceColumn": "dl_cases_06_phl5*[CategoryValue]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "718ce996-b2a5-4ef3-ad62-767f501a4600",
            "sourceColumn": "dl_cases_06_phl5*[CategoryValueIndex]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "92316e90-1829-498b-bcc7-5c89940b0595",
            "sourceColumn": "dl_cases_06_phl5*[Field]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e3bb9a4b-55d9-4bc9-b185-5efe3e6b4ca3",
            "sourceColumn": "dl_cases_06_phl5*[Sort]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "7b421c43-e7a0-423f-adc3-5c7e57467a9f",
        "partitions": [
          {
            "name": "dl_cases_06_phl5-276ee5c5-910a-41ff-bd71-422fb6598f89",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "UNION ( 'dl_cases_06_phl5*', dl_cases_06_phl5_NULLs )",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_cases_06_phl5*",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5f97e329ca484174af032b1b94ca10c8"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "TRIM ( REPLACE ( 'dl_cases_06_phl5*'[CategoryValueIndex], 1, 6, \"\" ) )",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ba094c2b-f42b-46da-94ce-686724967c2c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "6a96dd3f-3eb6-49ce-9a72-84e2227e8fa6",
            "sourceColumn": "Materials[PHL5]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "\"PHL5\"",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3e567a60-6eb2-427e-8bfb-e4c734922da4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "6",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7673a607-6cff-417c-a6fa-38f52431aa75",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "92c6e096-4a9f-4dc6-89a8-43a0f5ea6565",
        "partitions": [
          {
            "name": "dl_cases_06_phl5*-c61242e0-9ce6-428f-9880-2bcb4318e786",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZECOLUMNS (",
                "    Materials[PHL5],",
                "    KEEPFILTERS (",
                "        FILTER ( ALL ( Materials[PHL5] ), NOT ( ISBLANK ( Materials[PHL5] ) ) )",
                "    )",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_cases_06_phl5_NULLs",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "730b3b0edb474f8d86c29ca52e0a6e96"
          }
        ],
        "columns": [
          {
            "name": "Value1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1ee3b8eb-e020-4c6c-9950-3cff4127de19",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "29126b02-48cf-4ade-adb0-1eecfc5c464a",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "42156f92-bc37-4a40-83f6-abfed343a5ee",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ca8a959c-eca3-4999-a2df-07827919be24",
            "sourceColumn": "[Value4]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "67bf9a71-8db3-4a90-81ae-b89dfe0c4c61",
        "partitions": [
          {
            "name": "dl_cases_06_phl5_NULLs-1463fc79-001d-4f6b-a5a1-497cdfc56f02",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "{ ( \"PHL5 - NULL\", \"PHL5\", 6, \"PHL5 - NULL\" ) }",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_cases_07_mgr1",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "05f4ac5258944442a92b0a1b17403553"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ff4717b8-44f8-45b8-b109-81847b81493e",
            "sourceColumn": "dl_cases_07_mgr1*[CategoryValue]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "611aa29d-c22e-4d37-b5a2-d650b46b9332",
            "sourceColumn": "dl_cases_07_mgr1*[CategoryValueIndex]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b15bce7d-9f79-4e18-9734-1d020d5d002c",
            "sourceColumn": "dl_cases_07_mgr1*[Field]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e16480c5-66ea-4205-9169-cf7a67173741",
            "sourceColumn": "dl_cases_07_mgr1*[Sort]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "b69feb18-e296-45d9-b3ad-54f4e90a8061",
        "partitions": [
          {
            "name": "dl_cases_07_mgr1-b639f7c8-4ef3-4668-a25f-eb44d81afbda",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "UNION ( 'dl_cases_07_mgr1*', dl_cases_07_mgr1_NULLs )",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_cases_07_mgr1*",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c237263f047447bf93974b552bc97852"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "TRIM ( REPLACE ( 'dl_cases_07_mgr1*'[CategoryValueIndex], 1, 6, \"\" ) )",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3ff616b7-4fae-479f-8110-53fb9a0ddad5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "53861fc2-6e5b-495a-be4e-67cdc193d417",
            "sourceColumn": "Employee[Mgr1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "\"Mngr Level 1\"",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "220f2d27-2da4-4f8d-b0c3-9dab0ab1ec87",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "7",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "839d936d-4024-4d23-803c-1612b3b030fb",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "7b415dc3-a1e8-42ff-a682-04443fe380b4",
        "partitions": [
          {
            "name": "dl_cases_07_mgr1*-46042183-dbc5-44c1-ac97-8cd8d8fbd4e7",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZECOLUMNS (",
                "    Employee[Mgr1],",
                "    KEEPFILTERS (",
                "        FILTER (",
                "            ALL ( Employee[Manager Level 1] ),",
                "            (",
                "                NOT ( ISBLANK ( Employee[Manager Level 1] ) )",
                "                    && LEN ( Employee[Manager Level 1] ) <> 0",
                "            )",
                "        )",
                "    )",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_cases_07_mgr1_NULLs",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8b2c5e4b1e8746c3830c3f1f90f2ec1d"
          }
        ],
        "columns": [
          {
            "name": "Value1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a07ae733-f82c-4929-bb6b-1377d786dc38",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3f708d90-fc38-4a97-98ca-4d440d478cbf",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "06c64755-3ca5-4e3a-a977-2abe40de9412",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f712518f-06d7-4922-89a9-76721d9652d7",
            "sourceColumn": "[Value4]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "b61c71d0-c804-4245-9714-af4facbb08bb",
        "partitions": [
          {
            "name": "dl_cases_07_mgr1_NULLs-e29648e8-beb7-4274-99d3-8d61a85635c2",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "{ ( \"Mgr1 - NULL\", \"Mngr Level 1\", 7, \"NULL\" ) }",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_cases_08_agent",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b5da74d1a63043b0826f73a1d32fbaa7"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b4ca93af-b6ff-49fd-bfde-cbdff1ba6d2b",
            "sourceColumn": "dl_cases_08_agent*[CategoryValue]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7235fb31-eb55-4030-b1ca-9ef306aca3c1",
            "sourceColumn": "dl_cases_08_agent*[CategoryValueIndex]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3093df01-71d2-45e4-b039-aea9578a5e73",
            "sourceColumn": "dl_cases_08_agent*[Field]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "83127a8d-1441-4101-b7cd-b6a8c67d9eda",
            "sourceColumn": "dl_cases_08_agent*[Sort]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "0e1748fb-20f4-4623-9a87-eb455029f337",
        "partitions": [
          {
            "name": "dl_cases_08_agent-4ba4b0a3-bf75-4be8-80e2-dabe0dba03d9",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "DISTINCT ( UNION ( 'dl_cases_08_agent*', dl_cases_08_agent_NULLs ) )",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_cases_08_agent*",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8f82d306cc7948f39feb27f227a829d6"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CategoryValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "LEFT (",
              "    'dl_cases_08_agent*'[CategoryValueIndex],",
              "    SEARCH ( \"(\", 'dl_cases_08_agent*'[CategoryValueIndex], 1 ) - 2",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7c083a37-0e5d-479e-ab56-f2bfb80ffab3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CategoryValueIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "dcb65bd6-2095-4ac9-bf11-c4ed9ae73456",
            "sourceColumn": "Employee[Agent (EmployeeID)]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "\"Agent\"",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d72d85a5-db8e-499a-819a-dfb7c6853049",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "8",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "38b71fa1-581f-4c60-869b-2dd749a78fa1",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "79ffdbea-1fa5-4c76-b53a-f272984e8715",
        "partitions": [
          {
            "name": "dl_cases_08_agent*-25d1f1ed-2264-4ae8-a238-72af9709b705",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZECOLUMNS (",
                "    Employee[Agent (EmployeeID)],",
                "    KEEPFILTERS (",
                "        FILTER (",
                "            ALL ( Employee[Agent (EmployeeID)] ),",
                "            NOT ( ISBLANK ( Employee[Agent (EmployeeID)] ) )",
                "        )",
                "    )",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dl_cases_08_agent_NULLs",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "32485a85dee34019840fdcb4ca909f9f"
          }
        ],
        "columns": [
          {
            "name": "Value1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c328bcc8-7534-4974-a57c-6561c6761910",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d109792f-03ab-458a-bb96-207bdf41246d",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d0813f4e-4dea-4bf1-a000-ff3c82e41d47",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3d409ee0-8d4e-48cf-a30a-d59833f6ec9b",
            "sourceColumn": "[Value4]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "2ac05332-bf63-4ffe-a178-f242a2b5ba7b",
        "partitions": [
          {
            "name": "dl_cases_08_agent_NULLs-168051a9-1944-470b-b78a-762f1136efb9",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "{ ( \"N/A (9999999999)\", \"Agent\", 8, \"N/A\" ) }",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}